== Runtime Fabric Architecture
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Supported Configurations

Anypoint Runtime Fabric is composed of a set of VMs, each serving as one of the following roles:

* *Controller* - VMs dedicated for operating Runtime Fabric, including orchestration services, distributed database, load balancing, and services enabling Anypoint Platform management.
* *Worker* - VMs dedicated for running Mule applications and API gateways.

This separation of responsibilities enables scaling of the worker VMs based on the number of Mule applications. It also enables scaling the controller VMs based on the the frequency of deployments, changes in application state, and amount of inbound traffic. To ensure resources are available to re-schedule and re-deploy applications in the event of a hardware failure, we recommended over-provisioning the number of worker VMs.

By default, the services operating Runtime Fabric are deployed across the controller VMs to avoid a single point of failure in the system.

Anypoint Runtime Fabric uses a set of technologies, including Docker and Kubernetes, which are tuned to operate well with Mule runtimes. Knowledge of these technologies is not required to deploy or manage Mules on Runtime Fabric. Managing Runtime Fabric requires the operational and infrastructure-level experience needed to support any system at scale. We recommend following best practices and running fire drill scenarios in controlled environments to help prepare for unexpected failures.

[NOTE]
Deployments of applications and gateways not powered by Mule on Anypoint Runtime Fabric is not supported.

== Network Architecture

== Installer Life-Cycle
