= Associate Business Groups and Environments to Anypoint Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before deploying applications or API gateways to Anypoint Runtime Fabric, you must associate a Runtime Fabric with one or more Anypoint Platform environments. When deploying a Mule application, you cannot select a Runtime Fabric as a deployment target until you have performed this step in the environment where you want to deploy.

To associate an environment to a Runtime Fabric:

. From Anypoint Platform, select *Runtime Manager*.
. Select the *Runtime Fabric* section on the left sidebar.
. Select the Runtime Fabric based on the name used during installation.
. From the *Associated Environments* tab, select the environment you want to associate with this Runtime Fabric.
. Click *Apply* to confirm the changes.

== Production Environments

When selecting a production environment, a dialog is displayed that verifies Runtime Fabric has been configured to operate in a production setting. This includes proper hardware configuration, log forwarding, alerting, and possible failure modes.

If your Runtime Fabric is running with an unsupported configuration or does not meet the requirements for a production environment, one of the following messages is displayed:

* `This Runtime Fabric is not supported for any workloads. Learn more.`
* `This Runtime Fabric is suitable for non-production workloads only. Learn more.`

Refer to xref:install-prereqs.adoc[Anypoint Runtime Fabric Installation Prerequisites] for additional information.

Proper configuration must be complete before operating and deploying production applications on Runtime Fabric.

== Share across Business Groups

You can share Runtime Fabric with an organization's business groups. This allows other business groups to deploy applications to a single Runtime Fabric. To use this feature, the business groups must fall under the scope of the organization the Runtime Fabric is registered to.

To share a Runtime Fabric across business groups:

. From Anypoint Platform, select *Runtime Manager*.
. Select the *Runtime Fabric* tab on the left sidebar.
. Select the Runtime Fabric to manage.
. On the *Associated Environments* tab, click *Add business group*.
. Select the business group you want to share with this Runtime Fabric.
+
A list of the environments for the business group appears.

. Select the environments under the business group to associate with this Runtime Fabric.
. Click *Apply* to confirm the changes.


== See Also

* xref:enable-inbound-traffic.adoc[Enable Inbound Traffic to Runtime Fabric]
* xref:runtime-fabric-logs.adoc[Configure Log Forwarding on Anypoint Runtime Fabric]
* xref:configure-alerting.adoc[Configure Alerting on Anypoint Runtime Fabric]
