= Associate Business Groups and Environments to Anypoint Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before you can deploy applications or API gateways to Anypoint Runtime Fabric, you must associate it with one or more Anypoint environments. You will not be able to select Runtime Fabric as a Deployment Target when deploying an application until this step has been completed for the environment you wish to deploy to.


. Navigate to Runtime Manager.
. Select the Runtime Fabric section on the left sidebar.
. Select the Runtime Fabric based on the name used during installation.
. On the Associated Environments tab, select the environment you want to associate with this Runtime Fabric.
. Click Apply to confirm the changes.

== Production Environments

When selecting a production environment, a dialog will appear to ensure Runtime Fabric has been set up appropriately to operate in a production setting. This includes proper hardware configuration, log forwarding, alerting and familiarity with possible failure modes. It's highly recommended to ensure all these steps have been completed before operating and deploying production applications on Runtime Fabric.

== Sharing across Business Groups

Runtime Fabric can be shared with the organization's business groups. This is useful to allow other business groups to deploy applications to a single Runtime Fabric. To use this feature, the business groups must fall under the scope of the organization the Runtime Fabric is registered to.


. Navigate to Runtime Manager.
. Select the Runtime Fabric section on the left sidebar.
. Select the Runtime Fabric to manage.
. On the Associated Environments tab, click Add business group.
. Select the business group to share this Runtime Fabric with. A list of the environments for the business group should be added.
. Select the environments under the business group you want to associate with this Runtime Fabric.
. Click Apply to confirm the changes.


== See Also

* xref:enable-inbound-traffic.adoc[Enable inbound traffic to Runtime Fabric]
* xref:configure-log-forwarding.adoc[Configure Log Forwarding on Anypoint Runtime Fabric]
* xref:configure-alerting.adoc[Configure Alerting on Anypoint Runtime Fabric]