= Associating Business Groups and Environments to Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before deploying applications or API gateways to Anypoint Runtime Fabric, you must associate a Runtime Fabric with one or more Anypoint Platform environments. When deploying a Mule application, you cannot select a Runtime Fabric as a deployment target until you have performed this step in the environment where you want to deploy.

== Associate Business Groups

You can share Runtime Fabric with an organization's business groups. This allows other business groups to deploy applications to a single Runtime Fabric. To use this feature, the business groups must fall under the scope of the organization the Runtime Fabric is registered to.

To associate a Runtime Fabric across business groups:

. From Anypoint Platform, select *Runtime Manager*.
. Select the *Runtime Fabric* tab on the left sidebar.
. Select the Runtime Fabric to manage.
. On the *Environments* tab, click *Add business group*.
. Select the business groups from the drop-down list:

** *This business group and its children*
+ 
This option allows you to select either all environments, all sandbox environment or all production environments for the selected business group and all its children.

** *Selected business groups* 
+
Enter the business group name in the *Add business group* field and select it from the list. This option allows you to select specific environments for specific child business groups.

[start=6]
. Click *Save Changes* or *Discard Changes* to discard or confirm the association.

== Associate Environments

To associate an environment to a Runtime Fabric:

. From Anypoint Platform, select *Runtime Manager*.
. Select the *Runtime Fabric* section on the left sidebar.
. Select the Runtime Fabric based on the name used during installation.
. Click the *Environments* tab.
. Select the environments from the drop-down list:

** *All Environment* +
Associates the private space with all sandbox and production environments in the business group and all its children, or in specific child business organizations.

** *All Sandbox Environments*
Associates the private space with only sandbox environments in the business group and all its children, or in specific child business organizations.
** *All Production Environments*
+
Associates the private space with only production environments in the business group and all its children, or in specific child business organizations.
** *Select Environments Manually*
+
Allows you to associate the private space with specific environments in specific child business groups.
+
*** Check the *Sandbox* or *Production* box to bulk select all sandbox or production environments in specific child business organizations.
*** Check the box for each specific subenvironment to individually select the desired environments in specific child business organizations.

[start=6]
. Click *Save Changes* or *Discard Changes* to discard or confirm the association.

=== Production Environments

When selecting a production environment, a dialog is displayed that verifies Runtime Fabric has been configured to operate in a production setting. This includes proper hardware configuration, log forwarding, alerting, and possible failure modes.

If your Runtime Fabric is running with an unsupported configuration or does not meet the requirements for a production environment, one of the following messages is displayed:

* `This Runtime Fabric is not supported for any workloads. Learn more.`
* `This Runtime Fabric is suitable for non-production workloads only. Learn more.`

Refer to xref:install-index.adoc[Installing Runtime Fabric] for additional information.

Proper configuration must be complete before operating and deploying production applications on Runtime Fabric.
