= Configuring Authorized Namespaces in Runtime Fabric

Authorized namespaces enables you to deploy Runtime Fabric alongside other services in a Kubernetes cluster. By limiting permissions in your Runtime Fabric cluster, you can allow access only to resources within namespaces assigned to Runtime Fabric. 

With authorized namespaces, you have control of the creation of the following Runtime Fabric resources:

* Namespaces
* RoleBindings
* ServiceAccounts

== How Authorized Namespaces Work

At install time, you provide a configuration file that consists of your namespaces, ServiceAccounts, ClusterRoles/Roles, and RoleBindings.

Runtime Fabric installs the rtf-agent in the Runtime Fabric namespace, and it has access to any additional namespaces you create.

=== Example

The following is an example of a Runtime Fabric agent ClusterRole that allows the agent to control all cron jobs across all namespaces in a cluster.

[source,yaml]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: rtf:agent
rules:
- apiGroups:
 - batch
 resources:
 - cronjobs
 verbs:
 - create
 - delete
 - deletecollection
 - get
 - list
 - patch
 - update
 - watch
----
   
Runtime Fabric creates the required RoleBinding objects which use the ClusterRole rtf:agent to allow corresponding ServiceAccount to perform various actions (verbs) on cron jobs in two namespaces.

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rtf:agent-1
  namespace: namespace1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rtf:agent
subjects:
- kind: ServiceAccount
  name: rtf-agent-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rtf:agent-2
  namespace: namespace2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rtf:agent
subjects:
- kind: ServiceAccount
  name: rtf-agent-sa
  namespace: default
----
 
== Configure Authorized Namespaces 

You configure authorized namespaces when you install Runtime Fabric. Refer to the appropriate installation instructions:

* xref:install-helm.adoc[Installing Runtime Fabric on EKS, AKS, and GKE Using Helm]
* xref:install-openshift.adoc[Install Runtime Fabric on Red Hat OpenShift]

