= Configuring Runtime Fabric

To configure Anypoint Runtime Fabric, review the following topics:

* xref:associate-environments.adoc[Associating Business Groups and Environments] +
Associate a Runtime Fabric with one or more Anypoint Platform environments before deploying a Mule app or API proxy.

* xref:install-self-managed-network-configuration.adoc[Configuring Network] +
Configure ports and hostnames correctly before installing Runtime Fabric.

* xref:install-rtfctl.adoc#configure-rtfctl[Configuring Runtime Fabric Using RTFCTL] +
Use `rtfctl apply`, `update` and `wait` commands to configure Runtime Fabric.

* xref:custom-ingress-configuration.adoc[Configuring Ingress] +
Customize ingress configurations using an ingress resource template. 

* xref:configure-openshift-routes.adoc[Configuring Red Hat OpenShift Routes] +
Configure Red Hat OpenShift Routes to create ingress endpoints for your Mule apps.

* xref:persistence-gateway.adoc[Configuring Persistence Gateway] +
Use persistence gateway that enables Mule apps deployed to a Mule runtime instance to store and share data across application replicas and restarts.

* xref:manage-proxy-self.adoc[Configuring Proxies] +
Configure proxies when running and hosting Mule apps deployed to Runtime Fabric.
