= Configure a TLS Context for Anypoint Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

For HTTPS requests, all inbound traffic entering Runtime Fabric is encrypted using TLS. When enabling inbound traffic, you must provide a valid TLS certificate. When you configure inbound traffic for Runtime Fabric, you can configure the TLS server by importing a Privacy-Enhanced Mail (PEM) or Java Keystore (JKS) file, or by importing a TLS context from the secrets manager (advanced use case).

== Before You Begin

You must have the following permissions to enable inbound traffic to Runtime Fabric:

* Grant access to secrets
* Manage Secret Groups
* Read secrets metadata
* Write secrets

These permissions are available from the Secrets Manager tab in Anypoint Access Management.

. From Anypoint Platform, select *Access Management*.
+
If you do not have access to *Access Management*, ask your organization admin (system administrator) to provide the "Manage Runtime Fabrics" permission to your user. If you have access, execute the following steps to add the permission:
. Select *Users*.
. Locate the row containing your username and then select the blue link in the *Username* column.
. In the *Runtime Manager* tab, enable the *Manage Runtime Fabrics* permission for your Runtime Fabric environment.
+
[NOTE]
It can take up to five minutes for any permissions you add to propagate.

== TLS Context Configuration Prerequisites

You must perform the following configuration steps prior to adding a TLS context to a secrets group:

*** Have a TLS certificate with the desired Common Name set to route traffic to Runtime Fabric.

.... Create a Certificate Signing Request (CSR) for a Certificate Authority (CA). To streamline this step, larger organizations have a portal/internal service that provides certificate signing from a CA or might repurpose existing certificates. If neither of the previous options are available, follow the steps required by your CA to obtain your certificate, which usually includes the following tasks:

..... Submit a CSR to CA signing order. All domains/subdomains for serving traffic must be included in the Subject Alternative Name (SAN).
..... Prove domain ownership (DV certificates) or complete the necessary background checks for the certificate level.
..... Download the certificate and CA path (signing path) from your CA.
.... Review domains associated with the  (SAN) in your certificate. Many clients, including most browsers, only return a lock icon, which indicates a verified TLS connection, if the URL matches a domain in the SAN field of the certificate. 
.... Be prepared to add or update the DNS routing record to send traffic to the external load balancer IP address or addresses that front the Runtime Fabric instance. This is the final step needed to cut in or cut over traffic.

*** Be able to create or configure an external TCP load balancer to manage traffic to applications running in Runtime Fabric:

.... Gather all IP addresses of controller or dedicated nodes (depending on the configuration you choose during installation) that can be reached by the external TCP load balancer. These IP addresses may not be known until you complete the Runtime Fabric installation. For smaller traffic loads, controller nodes can be shared for cluster administration and inbound traffic TLS termination. For larger traffic loads, use dedicated nodes. The controller and dedicated nodes must have IP addresses that cn be reached (are routable and allowed at applicable firewalls) by the external load balancer. Otherwise, traffic cannot be routed from the load balancer to Runtime Fabric. 
.... Know the domain or domains to be used for routing traffic to your applications.
.... Understand that you need to configure an external load balancer to proxy the TCP protocol. The load balancer does not terminate TLS but does allow Runtime Fabric to do so.

*** Be able to configure the DNS settings to associate domains that are signed in the TLS certificate to the IP address or addess(es) served by the external load balancer.

== Add a TLS Context to a Secrets Group

Before you can import the TLS context from the secrets manager, you must add a TLS context.

Adding a TLS context to your secrets group involves supplying a name, target, security information, version, keystore, and, optionally, truststore. 

. In the *Secret Groups* list view, select the secrets group to which you want to add a TLS context. 
. Select *TLS Context* in the menu on the left, and click *Add TLS Context*. 
. In the Create TLS Context screen, add the required information:
+
* *Name* +
Enter a name for your TLS context. 
* *Target* +
Select *Anypoint Security* to validate the SSL handshake for Runtime Fabric. 
* *TLS Version* +
By default, TLS 1.2 and TLS 1.3 are selected. +
For information about the advantages of TLS 1.3, see <<tls_support_rtf,TLS Support on Runtime Fabric>>.
* *Keystore* +
From the drop-down list, select the keystore to store the TLS context. +
For information about adding a keystore to the secrets manager, see xref:asm-secret-group-creation-task#add_keystore.adoc[Create a Secrets Group]. +
You can select keystores that are either PEM or non-PEM types. 
* Optionally select a truststore to which to add the TLS context if you are using a truststore to store certificates trusted by the client. +
A truststore is required if you are going to enable client authentication.
* *Expiration Date* +
Optionally select the expiration date for the certificate.
. Optionally xref:enable-client-authentication.adoc[enable client authentication]. 
. Optionally xref:cipher-suites.adoc[select ciphers]. 
. Click *Save*.

[[import_tls_rtf]]
== Import a TLS Context to Runtime Fabric

. In *Runtime Manager > Runtime Fabrics > Inbound Traffic*, select one of the following options: +
* *Upload PEM* +
For information about this option, see xref:runtime-fabric::enable-inbound-traffic.adoc[Enable Inbound Traffic on Anypoint Runtime Fabric].
* *Upload JKS* +
For information about this option, see xref:runtime-fabric::enable-inbound-traffic.adoc[Enable Inbound Traffic on Anypoint Runtime Fabric].
* *Import from Secrets Manager*. +
This option is automatically selected for instances of Runtime Fabric for which inbound traffic was enabled before the PEM and JKS upload options became available. +
This option imports a TLS context from the secrets manager, and supports advanced configuration such as creating a TLS context, mutual authentication, selecting ciphers, and selecting TLS versions.
. Select the environment the secrets group that contains the TLS context is associated with.
. Select the secrets group where the TLS context is configured.
. Select the TLS context to use for Runtime Fabric. +
You can click *View Details* to see details of the TLS context you are importing. 

[[tls_support_rtf]]
== TLS Support on Anypoint Runtime Fabric

OpenSSL 1.1.1 and TLS 1.3 provide the following security enhancements and performance improvements over TLS 1.2:

* 2x or greater TLS 1.2 connection performance throughput boost over an earlier Runtime Fabric internal load balancer running on OpenSSL 1.0.2
* Reduction of one round trip in a full handshake for TLS 1.3 vs. TLS 1.2
* Added TLS 1.2 and TLS 1.3 ChaCha20-Poly1305 ciphers for better mobile and IoT device support
* TLS 1.3 protection against downgrade attacks
* Continued support for both RSA and ECDSA keys
* Removal of obsolete and insecure features from TLS 1.2 and TLS 1.1. +
See xref:release-notes::anypoint-security/anypoint-security-rtf-edge.adoc[Anypoint Security Edge Release Notes] for a list of supported and deprecated ciphers.

The TLS 1.3 protocol is enabled by default for those clients that support it.

== See Also

* xref:enable-client-authentication.adoc[Enable Client Authentication]
* xref:cipher-suites.adoc[Cipher Suites]
* xref:asm-secret-type-support-reference.adoc[Supported Secret Types]
* xref:runtime-fabric::enable-inbound-traffic.adoc[Enable Inbound Traffic on Anypoint Runtime Fabric]
