= Using a Local Registry with Runtime Fabric

Runtime Fabric uses its own registry to store the necessary Docker images for installing and managing Runtime Fabric and for running applications in Kubernetes. If your security policies require that you pull your Docker images from a registry under your control, you can set up a local registry to pull and store these Docker images.

== Limitations on Local Registry Support 

Review the following limitations on support for local registries:
 

[IMPORTANT]
You cannot use local registries during the installation of OpenShift operator. However, you can use local registries with OpenShift RTF to store Mule Docker images and install and manage Runtime Fabric for running Mule apps. 

* You can use xref:install-rtfctl.adoc[Runtime Fabric command line utility (`rtfctl`)] version 0.3.150 or later. Note that `rtfctl` installs Runtime Fabric agent to the latest version by default.
* You can use Helm to install Rutime Fabric and configure your local registry.
* You can use a local registry only if you create a new Runtime Fabric instance of version 1.12.0 or later.
+
If you set up a local registry, you can upgrade to a version later than 1.12.0 without reinstalling Runtime Fabric.
+
You cannot add a local registry to any version of an existing Runtime Fabric instance, even if you upgrade that installation to 1.12.0 or later.
* If you create a Runtime Fabric instance to use with a local registry, you cannot later reconfigure it to use the `rtf-runtime-registry` endpoint. To use the `rtf-runtime-registry` endpoint, you must install a new Runtime Fabric instance using the standard installation procedure.
* You're responsible for synchronization between your registry and the Runtime Fabric registry. 
+
MuleSoft doesn't provide additional software to synchronize images between the registries. Push all the dependency images for your version to your local registry before you start the installation. See the xref:release-notes::runtime-fabric/runtime-fabric-release-notes-2.x.x.adoc[Runtime Fabric release notes] for the required dependencies for your Runtime Fabric version.
+ 

* If you use a local registry that needs authentication, synchronization and propagation of a pull secret between different namespaces is your responsibility. Alternatively, Runtime Fabric can synchronize your pull secret across different namespaces if your secret uses the following label:

----
  labels:
    rtf.mulesoft.com/synchronized: "true"
----

* If you need to authenticate access to your local registry, ensure that the https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials[corresponding credentials are configured as a Kubernetes secret in the `rtf` namespace^]. You'll need the name of the configured secret when you install Runtime Fabric. 

* You also need to synchronize in your registry the Mule runtime versions you intend to use for application deployments. Refer to the xref:release-notes::runtime-fabric/runtime-fabric-runtimes-release-notes.adoc[Runtime Fabric Patch Update Release Notes] for information about the latest Mule runtime patch versions. The location of the image will follow this format: `rtf-runtime-registry.kqa.msap.io/mulesoft/poseidon-runtime-4.4.0:<tag>`.

== Configure Your Local Registry for Runtime Fabric

To configure a local registry, you must gather and add the necessary credentials to synchronize the registries. 

=== Before You Begin

Ensure that you've performed the following tasks: 

. Set up, configure, and test your private Docker image registry.
. <<synchronize, Synchronize>> to your local registry all the Docker images you need to install Runtime Fabric:
+
See the xref:release-notes::runtime-fabric/runtime-fabric-release-notes-2.x.x.adoc[Runtime Fabric release notes] for the required dependencies for your Runtime Fabric version. 
+
[NOTE]
Dependency versions are specific to the Runtime Fabric version. 

To configure your local registry using `rtfctl` or `helm`, select one of the following options:

[tabs]
====
RTFCTL:: 

+
--
. xref:install-self-managed.adoc#step-3-download-the-rtfctl-utility[Download and install the `rtfctl` command line utility] version 0.3.150 or higher.
. Obtain `rtf-runtime-registry` credentials:
+
[source,copy]
----
# rtfctl get registry-credentials <activation-data>
----
+
This command sets `RTF_IMAGE_REGISTRY_ENDPOINT`, `RTF_IMAGE_REGISTRY_USER`, and `RTF_IMAGE_REGISTRY_PASSWORD` in the current shell environment. 

. Run the following commands to verify that the Docker login to the `rtf-runtime-registry` succeeds:
+
[source,copy]
---- 
# eval $(rtfctl get registry-credentials <activation-data>)
# docker login $RTF_IMAGE_REGISTRY_ENDPOINT --username $RTF_IMAGE_REGISTRY_USER --password $RTF_IMAGE_REGISTRY_PASSWORD
----
+
You should see a message that the login was successful.

. <<synchronize,Synchronize your container images>> to your local registry.

. Repeat step 3 for all the other dependency images (resourceFetcher, clusterOps etc.) based on the versions published in the Runtime Fabric release notes. 

. If you use authentication to access your registry, create the required secret in the rtf namespace:
+
[source,copy]
----
# kubectl create namespace rtf
# kubectl create secret docker-registry regcred --namespace=rtf --docker-server=<docker_server> --docker-username=<docker_username> --docker-email=<docker_email> --docker-password=<docker_password> 
# kubectl label secret regcred rtf.mulesoft.com/synchronized=true -n rtf
----
+

. Finalize the Runtime Fabric installation, and configure it to pull from your local registry:
+
[source,copy]
----
# rtfctl install ‘<activation_data>’ --image-pull-registry <docker-server>
----
+
Alternatively, if you use authentication to access your registry, use the following command:
+
[source,copy]
----
# rtfctl install ‘<activation_data>’ --image-pull-registry <docker-server> --image-pull-secret <your-local-reg-secret>
----
+
This command ensures that Runtime Fabric creates the necessary overrides for the local registry URL and `image-pull-secret` values so Runtime Fabric continues to pull images from the local registry even after an upgrade.

. If you use authentication to access your registry, after you complete the installation, you must recreate the pull secret in the RTF namespace and in any other namespaces where you will deploy applications. 
. Refer to the xref:install-self-managed.adoc[installation instructions] for further steps, such as inserting the Mule license key.

The `rtfctl uninstall` command deletes any pull secret you specify during installation.

When using `rtfctl` to perform a backup and restore procedure, the backups point to your local registry URL and pull secret. 
--
 
Helm::
+
--
. <<synchronize,Synchronize your container images>> to your local registry.
. xref:install-helm.adoc#create-a-runtime-fabric-using-runtime-manager[Create a Runtime Fabric using Runtime Manager], and gather the activation data.
. In Runtime Manager, select the *Helm* path, and follow the instructions on the screen platform.
. Obtain your private `docker-server`, `docker-username`, and `docker-password`.
. Following the *Helm* path instructions in Runtime Manager, create a secret with your docker server name, username, and password by running the following command in your Unix shell:
+
[source,copy]
----
kubectl create secret docker-registry rtf-pull-secret --namespace test-gke-rtf-qax-helm --docker-server=<docker-servername> --docker-username=<docker-username --docker-password=<docker-password> --docker-email=<docker-email>
----

[start=6]
. Following the *Helm* path instructions, download the values.yaml file and modify its values. The following is a values.yaml file example:
+
[source,copy]
----
activationData: xxx
proxy:
 http_proxy:
 http_no_proxy:
 monitoring_proxy:
muleLicense: 
customLog4jEnabled: false
global:
 crds:
  install: false
 authorizedNamespaces: false
 image:
  rtfRegistry: 
  pullSecretName: rtf-pull-secret
 containerLogPaths:
 - /var/lib/docker/containers
 - /var/log/containers
 - /var/log/pods
----

[start=7]
. Continue with the *Helm* path instructions and install Runtime Fabric in your Kubernetes cluster.

--
====
[[synchronize]]
== Synchronize Local Registry

To install Runtime Fabric, you must first synchronize the dependencies images to your local registry. You can perform the synchronization by running a script automatically or running comands manually. 

[tabs]
====
Synchronize Automatically:: 

+
--
To synchronize the dependencies images automatically, you ran a bash script that uses `docker`, `curl`,  and `jq` tools.

[NOTE]
Automated registry synchronization is available from Runtime Fabric version 2.6.0 onwards. Previous dependencies can not be retrieved using this script.

Ensure that your xref::access-management/permissions-by-product.adoc#runtime-manager[Access Management permission for Runtime Manager] is set to *Read Runtime Fabric*, which enables you to query Runtime Fabrics in your organization.

. In your shell script, run the following script, replacing `agent-version`, `authorization-token`, `mulesoft-docker-server`, and any other parameter value where appropriate:

+
[source,copy]
----

##!/usr/bin/env bash
dependencies=$(curl https://qax.anypoint.mulesoft.com/runtimefabric/api/agentmanifests/<agent-version>         -H 'Authorization: bearer <authorization-token>' | jq -c '.dependencies |.[] | select(.provider | contains("generic")) | "\(.artifact):\(.version)"' | sed 's/"//g')
for i in $dependencies
do
    echo "Processing $i"
    docker pull <mulesoft-docker-server>/mulesoft/$i
    docker tag  <mulesoft-docker-server>/mulesoft/$i <local-docker-server>/mulesoft/$i
    docker push <local-docker-server>/mulesoft/$i
done
----
+
[%header%autowidth.spread]
.Script Parameters
|===
| Parameters | Description
| `agent-version` | Runtime Fabric agent release version required for the synchronization.
| `authorization-token` |  Obtain the authorization token required for the synchronization through the connected apps capability and a link redirects to the connected apps page.
| `mulesoft-docker-server` |  MuleSoft Docker server required for the synchronization. +
For US control plane: `rtf-runtime-registry.kprod.msap.io` +
For EU control plane: `rtf-runtime-registry.kprod-eu.msap.io`
|==

--
Synchronize Manually:: 

+
--
To synchronize the dependencies images manually, follow these steps:

. Log in into your own private container registry and run the following command, replacing `docker-server` where appropriate:
+
For the US control plane:
+
[source,copy]
---- 
# docker pull rtf-runtime-registry.kprod.msap.io/mulesoft/rtf-agent:v1.12.0 
# docker tag rtf-runtime-registry.kprod.msap.io/mulesoft/rtf-agent:v1.12.0 <docker-server>/mulesoft/rtf-agent:v1.12.0 
# docker push <docker-server>/mulesoft/rtf-agent:v1.12.0
----
+
For the EU control plane:
+
[source,copy]
---- 
# docker pull rtf-runtime-registry.kprod-eu.msap.io/mulesoft/rtf-agent:v1.12.0 
# docker tag rtf-runtime-registry.kprod-eu.msap.io/mulesoft/rtf-agent:v1.12.0 <docker-server>/mulesoft/rtf-agent:v1.12.0 
# docker push <docker-server>:5000/mulesoft/rtf-agent:v1.12.0
----
--
====
