= Mutual Authentication with Anypoint Platform
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Starting with version 1.3.60, you can use the Runtime Fabric *Settings* page in Runtime Manager to enable mutual authentication on the connectivity between the Runtime Fabric and Anypoint control plane. Mutual authentication improves the security of communication between Runtime Fabric and Anypoint Platform and is highly recommended. Runtime Fabrics created after July 6, 2020 will have this setting enabled by default.

Before enabling mutual authentication, verify the following endpoint and port is reachable from all of the Runtime Fabric controller and worker nodes:

* US control plane: 
** `configuration-resolver.prod.cloudhub.io:443`
* EU control plane:
** `configuration-resolver.prod-eu.msap.io:443`

You can use the latest version of the xref:install-rtfctl.adoc[rtfctl] utility to validate all required endpoints are reachable from each Runtime Fabric controller node:

----
cd /opt/anypoint/runtimefabric
./rtfctl update
./rtfctl test outbound-network
----
