= Resource Allocation on Anypoint Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before deploying a Mule application to Runtime Fabric, determine the correct amount of resources to allocate. Determining resource allocation is also applicable when configuring the internal load balancers on Anypoint Runtime Fabric.

When a Mule application is deployed to Runtime Fabric, the application is deployed with its own Mule runtime. The number of replicas, or instances of that application and runtime, are also specified. The resources available for each replica are determined by the values you set when deploying an application.

You can allocate the following resources when deploying an application:

* vCPU cores
* Memory

== Minimum Core and Memory Requirements

The minimum values for the amount of CPU and memory allocated to each replica of a Mule application are:

* vCPU Cores: 0.07 cores
* Memory: 0.7 GiB memory (Mule 4) or 0.5 GiB (Mule 3.x)

== Calculating Memory Allocation on CloudHub and Runtime Fabric

Anypoint Platform allocates native and heap memory for a deployed application. Heap memory is the portion of the total memory that is made available to the Mule runtime and the application. Heap memory is used for tasks like handling payload.

Both CloudHub and Runtime fabric allocate both types of memory. However, they differ in how the memory allocation of each memory type is calculated.

* Runtime Fabric: lists the total memory available for an application. The available heap memory is approximately half of the total memory allocated to an application.
* CloudHub: describes minimum memory requirements in terms of the heap memory available to an application.

== Application Startup Times

The startup time for a Mule applications is correlated to the amount of vCPU cores the application has access to:

[%header,cols="2*a"]
|===
| vCPU Cores | Approximate Startup Time
| `1.00` | Less than 1 minute
| `0.50` | Under 2 minutes
| `0.10` | 6 to 8 minutes
| `0.07` | 10 to 14 minutes
|===

== Application Performance

The amount of resources allocated to your Mule application determin the application's performance. Below are the approximate values for throughput based on the amount of vCPU cores allocated for a single Mule application performing simple processing on a 10 KB payload.

[%header,cols="3*a"]
|===
| vCPU Cores | Concurrent Connections | Avg Response Time (ms)
| `1.00` | 10 | 15
| `0.50` | 5 | 15
| `0.10` | 1 | 25
| `0.07` | 1 | 78
|===

[NOTE]
Run performance and load testing on your Mule applications to determine the number of resources to allocate.

== Internal Load Balancer

Inbound traffic is processed using an internal load balancer managed by Anypoint Runtime Fabric. Since this load balancer is responsible for TLS termination, the amount of resources required scales based on the number of incoming connections and the average payload size for each request.

The following table lists the approximate requests averaging 10 KB that can be served with a single replica of the internal load balancer based on the amount of CPU cores.

[%header,cols="3*a"]
|===
| vCPU Cores | Max Requests per Second (Connection Re-use) | Max Requests per Second (No Connection Re-use)
| `1.00` | 2000 | 175
| `0.75` | 1500 | 100
| `0.50` | 1000 | 50
| `0.25` | 100 | 10
|===

[NOTE]
The internal load balancer runs on the controller VMs of Runtime Fabric. Size the VMs appropriately based on the amount and type of inbound traffic. You can only allocate half of the available CPU cores on each VM to the internal load balancer.

== See Also

* xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to a Runtime Fabric]
