= Deploy a Mule Application to Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Deploy a Mule application to Anypoint Runtime Fabric and test the inbound traffic for deployed applications.

== Before You Begin

Before deploying an application to Anypoint Runtime Fabric, you must perform the following:

* Install and configure Anypoint Runtime Fabric. See xref:install-create-rtf-arm.adoc[Begin Runtime Fabric Installation] for more information.
* Ensure that Runtime Fabric is associated with an environment.
* Determine the resource allocation requirements for your application. See xref:deploy-resource-allocation.adoc[Determine Application Resource Allocation on Runtime Fabric] for more information.
* Your Anypoint user may require the *Exchange Contributors* permission to deploy applications to Runtime Fabric.

== Deploy an Application

To deploy an application, perform the following steps:

. Sign into https://anypoint.mulesoft.com[Anypoint Platform].
. Navigate to *Runtime Manager*, and select the *Applications* section.
. Click *Deploy application*.
. Provide a name for your application in the *Application Name* field.
+
The name can contain only lowercase alphanumeric characters, hyphens, and underscores.
. Click *Choose File* to select the application to deploy, then select one of the following options:
+
* *Import file from Exchange*: Enables you to select a Mule application stored in Anypoint Exchange.
* *Upload file*: Enables you to select a Mule application file from your filesystem.
+
. Select the name of your Runtime Fabric from the *Deployment Target* drop-down list.
+
_Result_: The *Deployment Target*, *Ingress*, and *Properties* tabs are displayed. Use these tabs to enter additional configuration information for your application.

. Select the *Deployment Target* tab.
+
This tab displays the name and type of the deployment target you selected above.

. Select the Mule runtime engine version from the *Runtime Version* drop-down list.

. Select the number of replicas, or instances, of the application to deploy.
+
[NOTE]
A minimum of two replicas is required for high availability.
. To enable Mule clustering across each replica of the application, enable *Run in Runtime Clustering Mode*.
. Specify the number of *Cores* and amount of *Memory* to allocate to each replica of the application by adjusting the sliders to the appropriate values.
+
See how to xref:deploy-resource-allocation.adoc[determine resource allocation] for applications deployed to Runtime Fabric.

. Specify network configuration for the application:

.. Click the *Ingress* tab.
.. Enable or disable the following options:
+
* *Enable inbound traffic to this application* to allow incoming HTTP requests to be processed by this application. Ensure your application is configured to accept connections on port 8081.
* *Enable Last-Mile security* to forward HTTPS connections to be decrypted by this application. This requires an SSL certificate to be included in the Mule application, and also requires more CPU resources.

. Configure application properties:
.. Click the *Properties* tab.
.. Specify your application properties as key-value pairs.

. Click *Deploy Application*.
+
If the *Deploy Application* button is disabled, ensure that you have uploaded a valid Mule application file. Also ensure that the Mule runtime engine version you selected is the same as the version used by your application.

_Result_: Runtime Manager displays a status message confirming the application deployment. After the deployment starts, you'll be directed to the applications list page where you can view the deployment status.

For newly deployed applications, the status initially displays as *Starting*. The status updates to *Started* if the application is successful. Monitor the application status to ensure that it starts successfully.

== Verification

To test inbound traffic for deployed applications, you can send a request using the controller IP address along with a host header set to the domain. The host header depends on the structure of the application URL.

. Determine the URL path (if it exists) for the application by locating the worker node for the application, for example:
+
```
kubectl get pods --all-namespaces | grep {app-name}

873835cd-273a-4623-9203-ecaa1b975a5e   {app-name}-f9b7d85d-59df7                   2/2     Running     0          2m48s
```
. On the controller node, get the connection to the worker node for the application:
+
```
kubectl exec -n 873835cd-273a-4623-9203-ecaa1b975a5e {app-name}-f9b7d85d-59df7 -c app -it -- /bin/bash
```
. On the worker node for the application, get the URL path. In this example, the URL path is `/helloWorld`:
+
```
app@{app-name}-f9b7d85d-59df7:/opt/mule/apps/{app-name}$ cat hello-world.xml

<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns="http://www.mulesoft.org/schema/mule/core"
	xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="d6132ed6-b549-4a5a-ab30-b0006362476b" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>
	<flow name="hello-worldFlow" doc:id="fb709ee4-0263-492c-92e3-ba5bb6287cd7" >
		<http:listener doc:name="Listener" doc:id="b4f5d981-3869-46e4-879b-2ba9e8e1c2b7" config-ref="HTTP_Listener_config" path="/helloWorld"/>
		<logger level="INFO" doc:name="Logger" doc:id="d254b372-8ea9-4b59-bb07-04cc2bf715a5" message="#[attributes.requestPath]"/>
		<set-payload value="Hello World!" doc:name="Set Payload" doc:id="c04ac342-40dd-48ec-bf80-206d3aaa77e3" mimeType="text/plain"/>
	</flow>
</mule>
```
. Using the {path} information obtained, use one of the following cURL commands for verification, based on the application URL format:

** An application URL with the format `{app-name}.domain.com` uses the following request header format: `Host: {app-name}.domain.com`. Use the following cURL command for verification:
+
```
curl -Lvk -XGET -H 'Host: {app_name}.<domain of worker>' https://{worker-ip-address>}/{path}
```
+
For example:
+
```
curl -Lvk -XGET -H 'Host: hworld-app.eu-north-1.compute.amazonaws.com' https://13.53.214.196/helloWorld
```
** An application URL with the format `domain.com/{app-name}` uses the following request header format: `Host: domain.com`. Use the following cURL command for verification: 
+
```
curl -Lvk -XGET https://{worker-ip-address}/{app-name}/{path} -H "Host: <domain of worker>"
```
+
For example:
+
```
curl -Lvk -XGET https://{worker-ip-address}/hworld-app/helloWorld -H "Host: eu-north-1.compute.amazonaws.com"
```

== Common Issues

If your application remains in the *Starting* status for several minutes, this may be due to specifying a lower amount of resources. It's common for applications to take several minutes to start up when selecting 0.3 cores or lower.

If the application encounters an error during startup, the deployment will stop and the status updates to *Failed*. An error message preview is displayed when clicking on the application and viewing the right sidebar. To view the entire message, click on the *Manage Application* button. Viewing the application logs in Ops Center or using your third party logging provider will provide more details.

An error message indicating `insufficient resources` is returned when Runtime Fabric doesn't have the CPU cores or memory available for the deployment. When selecting multiple replicas, it's important to know that the cores and memory specified applies to _each_ replica.

If a re-deployment to an existing running application fails, the previous application remains running and active. This behavior enables zero-downtime application re-deployments. Runtime Manager will report the details and status of the failed deployment to help resolve the failure.

== See Also

* xref:deploy-resource-allocation.adoc[Determine Application Resource Allocation on Runtime Fabric]
* xref:runtime-manager::developing-applications-for-cloudhub.adoc[Deploy a Mule Application to CloudHub]
* xref:runtime-manager::deploying-to-your-own-servers.adoc[Deploy a Mule Application to a Hybrid Environment]
