= Deploy Applications and API Proxies to Runtime Fabric

Anypoint Runtime Fabric enables you to deploy Mule applications and API Proxies to a Mule runtime engine that is managed on Runtime Fabric.

== Supported Mule Versions

Anypoint Runtime Fabric supports deployment to these versions of Mule runtime:

* 3.8.7
* 3.9.1, 3.9.2
* 4.1.2+
* 4.2.0

== Prerequisites

Before you deploy a Mule application or API proxy to Runtime Fabric, you must:

* Install and configure a Runtime Fabric.
* Ensure that you understand how resources are allocated as described in xref:deploy-resource-allocation.adoc[Resource Allocation on Anypoint Runtime Fabric].
* Publish your Mule application or API proxy to Exchange. +
[NOTE]
Before you deploy Mule applications and API proxies to Runtime Fabric, you must first publish them to Exchange. When you deploy Mule applications and API proxies from Runtime Manager, they are published to Exchange automatically.


== Deploy Using Runtime Manager

You can use Runtime Manager to manually deploy Mule applications and API proxies. See xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric].

== Deploy Using Maven

Runtime Fabric supports Maven for managing and deploying a Mule application or API proxy. 

The following topics have information that's specific to the version of Mule your application supports:

* xref:deploy-maven-4.x.adoc[Deploy an Application to Runtime Fabric using Maven (Mule 4)]
* xref:deploy-maven-3.x.adoc[Deploy an Application to Runtime Fabric using Maven (Mule 3.x)]
