= Deploy and Manage Apps in Runtime Fabric Using the CLI
 
Use these Anypoint Platform CLI commands for deploying and managing applications in Runtime Fabric. The CLI supports both the interactive shell and standard CLI modes. 

Before you get started, review xref:3.x@anypoint-cli::index.adoc[Anypoint CLI prerequisites, installation, and authentication instructions]. 

[[deploy-apps-in-runtime-fabric]]
== Managing Apps in Runtime Fabric

include::anypoint-cli::partial$cloudhub2-apps.adoc[tags=summary,leveloffset=+1]

include::anypoint-cli::partial$cloudhub2-apps.adoc[tags=commands,leveloffset=+1]

[[list-runtime-fabric-instances]]
== List Runtime Fabric Instances

include::anypoint-cli::partial$rtf-instances.adoc[tag=summary,leveloffset=+1]

include::anypoint-cli::partial$rtf-instances.adoc[tag=commands,leveloffset=+1]

== Deploy a Mule App Example

The following example shows how to deploy a Mule application to Runtime Fabric using Anypoint CLI.

=== Configure your Anypoint CLI Space

To configure your CLI space, you must download and install `anypoint-cli-v4`:

. Open CLI and run this command:
+
[source,copy]
----
npm install -g anypoint-cli-v4
----
+
[start=2]
. Install runtime-mgr plugin by running this command:
+
[source,copy]
----
anypoint-cli-v4 plugins:install anypoint-cli-runtime-mgr-plugin
----
+
[start=3]
. Set your credentials by running these commands:
+
[source,copy]
----
anypoint-cli-v4 conf username <username>
----
[source,copy]
----
anypoint-cli-v4 conf password <password>
----

To set other parameters for your space, review the xref:anypoint-cli::auth.adoc[Authentication to the Anypoint Platform CLI] documentation.
After your CLI space is set, you can deploy and manage Mule applications to Runtime Fabric.

=== List Existing Apps

To list existing apps, run the following command:
[source,copy]
----
anypoint-cli-v4 runtime-mgr:application:list.
----

=== Deploy a Mule App

To deploy the Mule app, run the following command:

[source,copy]
----
runtime-mgr:application:deploy <appName> <targetId> <runtimeVersion> <artifactId>
----

Using (test-mule-1) version as default version: v1.0.6
deploying new-app01, the output log would be similar to this :

[source,copy]
----
╔═════════════════════╤══════════════════════════════════════════════╗
║ Name:               │ new-app01                                    ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ App Id:             │ 9eeb4bb1-5ba4-47c8-b987-f1e1c2f68f8c         ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Status:             │ UNDEPLOYED                                   ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Updated:            │ a few seconds ago                            ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Runtime:            │ 4.4.0                                        ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Target:             │ 734024b7-002b-40cd-92d2-b659175d0557         ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Artifact Id :       │ test-mule-1                                  ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Replicas:           │ 1                                            ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Update Strategy     │ rolling                                      ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Specs:              │ e45ab9b9-fe58-4387-9975-2ffcb91742df (DESIRED║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Properties:         │                                              ║
╟─────────────────────┼──────────────────────────────────────────────╢
║ Secure Properties:  │                                              ║
╚═════════════════════╧══════════════════════════════════════════════╝
----

Additionally, you can add more parameters to deploy your Mule app. If you want your app to have 2 replicas instead of 1, you can write `--replicas 2`  at the end of your script.

You can set the following extra parameters for you deployment:

* Password and username/client id:  `--password <value> [--username <value> | --client_id <value> | ]`
* Client secret:   `--client_secret <value>`
* Bearer: `--bearer <value>`
* Organization:  `--organization <value>`
* Environment: `--environment <value>`
* Host: `--host <value>`
* Collect metrics: `--collectMetrics`
* Asset version: `--assetVersion <value>`
* Group id: `--groupId <value>`
* Replicas: `--replicas <value>`
* Replica size: `--replicaSize <value>`
* Object store v2: `--objectStoreV2`
* Update strategy: `--updateStrategy <value>`
* Clustered: `--clustered`
* Last mile security: `--lastMileSecurity`
* Disable am log forwarding: `--disableAmLogForwarding`
* Property: `--property <key:value>`
* Secure property: `--secureProperty <key:value>`
* Properties file: `--propertiesFile <value>`
* Scope logging config file: `--scopeLoggingConfigFile <value>`
* Forward ssl session: `--forwardSslSession`
* Path rewrite: `--pathRewrite <value>`
* Public endpoints: `--publicEndpoints <value>`
* Instance type: `--instanceType <value>`

=== Edit Existing Mule App

To modify an existing Mule application, you need the app ID. You can obtain the app ID from the list of applications or if you want to modify the app that you just deployed, the app ID is in the response of that deployment.

You can change the same parameters that you set when deploying the Mule app.
For example, to add a secure property, run the following command: 

[source,copy]
----
anypoint-cli-v4 runtime-mgr:application:modify <appId>  --secureProperty <key:value> 
----

=== Stop, Start and Delete a Mule App

To perform these actions, you need the app ID you want to modify.

To stop a Mule app, run this command: 

[source,copy]
----
anypoint-cli-v4 runtime-mgr:application:stop <appId> 
----

To start a Mule app, run this command:  

[source,copy]
----
anypoint-cli-v4 runtime-mgr:application:start <appId>
----

To delete a Mule app, run this command:

[source,copy]
----
anypoint-cli-v4 runtime-mgr:application:delete <appId>
----
