= Enable Inbound Traffic on Anypoint Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Runtime Fabric provides load balancing to manage inbound traffic to Mule applications and API proxies. Network traffic is balanced across multiple replicas of an application, which, by default, are deployed across different worker VMs.

Runtime Fabric can be shared across multiple environments. After installation, configure one or more environments for each Runtime Fabric to enable application deployment. You must associate at least one environment with each Runtime Fabric to be able to deploy Mule applications or API gateways.

Applications deployed to a production environment must be deployed to an instance of Runtime Fabric that is separate from non-production applications.

By default, inbound traffic is disabled to prevent consuming unnecessary resources. To allow Mule applications or API gateways to listen on inbound connections, enable inbound traffic. Inbound traffic is disabled by default and must be manually enabled before inbound requests can be received by Mule applications and API gateways.

== Step 1: Assign Required Roles and Permissions
Ensure you have the necessary permissions for the Runtime Fabric environment you want to use for applications.

. From Anypoint Platform, select *Access Management*.
+
If you do not have access to Anypoint Access Management, request access from your system administrator.
. Select *Users*.
. Locate the row with your username and then select the blue link in the *Username* column.
. In the *Runtime Manager* tab, enable the *Manage Runtime Fabrics* permission for your Runtime Fabric environment.
+
[NOTE]
It can take up to 5 minutes for any permissions you gain to propagate.

== Step 2: Configure Inbound Traffic Using Runtime Manager

. Navigate to Runtime Manager and select *Runtime Fabric*.
. Select the name of your Runtime Fabric to open the management page.
. In the *Associated Environments* tab, ensure your Runtime Fabric is associated with the environments in which applications are to be deployed.
. Select *Inbound Traffic* and enable the *Enable inbound traffic* toggle.
+
[NOTE]
Disabling the Inbound Traffic tab can take several minutes to complete.

. In the *Basic Configuration* section, verify *Secure Port* is set to `443` and *Non Secure Port* is set to `80`.  The nonsecure port redirects to the secure port.
. Select *Resource Allocation*.
+
[NOTE]
The number of Inbound load balancer replicas is determined by the number of controller nodes configured in the RTF. Refer to https://docs.mulesoft.com/runtime-fabric/1.4/manage-index for detailed information.
.. Select the resource allocation type for the ingress configuration:

*** Shared Mode. This is the default setting if no dedicated mode is available. A minimum of 2 replicas is required for production environments, and these replicas only run on the controller VMs.
.. Specify the minimum number of cores for each replica of the internal load balancer. Note that the RTF can use up to the maximum number shown if they are available. Transport Layer Security (TLS) termination is computationally expensive, so make sure to allocate enough CPU to increase throughput and decrease latency.
.. Specify the minimum memory for each replica of the internal load balancer. Note that Runtime Fabric can use up to the maximum amount shown if it is available.
. Configure a TLS context:
+
All inbound traffic entering Anypoint Runtime Fabric is encrypted using TLS. When enabling inbound traffic, you must provide a valid TLS certificate. Once enabled, HTTP requests sent to Runtime Fabric receive a `301` response to redirect to HTTPS on port 443.
+
You can configure the private key and public certificate for a TLS-enabled server in one of the following ways:

** Upload Privacy-Enhanced Mail (PEM) or Java Keystore (JKS) information. The default value for `Source` is `Upload PEM`  when no TLS context exists for Runtime Fabric. A PEM file is a Base64-encoded ASCII file with a `.cer`, `.crt`, or `.pem` extension. A JKS file is a repository for authorization or public key certificates and does not store secret keys. When you select the *Upload PEM* or *Upload JKS* option, you cannot change default values for TLS versions, ciphers, and other TLS configuration options. 
** Import a TLS Context from Secrets Manager.
+
This option supports advanced configuration such as mutual authentication, selecting ciphers, and selecting TLS versions. This option is automatically selected for Runtime Fabrics that were configured before the PEM and JKS upload options became available.
+
To use this option you need additional Secrets Manager permissions. Refer to xref:anypoint-security::configure-tls-context-rtf-lb.adoc[Configure a TLS Context for Runtime Fabric Load Balancer] for additional information.
+
To generate key material for testing purposes and create a TLS context in Secrets Manager, follow the instructions provided in xref:anypoint-security::secret-group-add-tls-context.adoc[Generate a TLS Certificate for Testing].

.. Select one of the following options:

*** Option 1: Upload PEM
+
Use this option to upload a public certificate and private key in PEM format. 
+
This option uses the TLS default values. Refer to <xref:anypoint-security::configure-tls-context-rtf-lb.adoc> for additional information.
.... Specify a *Certificate File*. When you specify a PEM public certificate file, the *Derived URL Format* field lists domains that are selectable for *Application url*, which is used for routing requests to an application. By default, the first domain listed is used. Other values can be selected via the Applications->Ingress page.
+
The certificate must be set with a passphrase and a common name (CN) that specifies the domain for each application deployed to Runtime Fabric.
***** If the CN contains a wildcard, the endpoint for each deployed application takes the form `{app-name}.{common-name}`.
***** If the CN does not contain a wildcard, the endpoint takes the form `{common-name}/{app-name}`.
.... Specify a value for *Key File*. This is the PEM formatted file that contains the private key for the certificate.
.... If the *Key Passcode* field is displayed after uploading a PEM key file, enter the word or phrase that protects the private key.
.... Optionally, specify a value for *CA Path Certificate File (Optional)*. This is the certificate signed by a certification authority (CA). The CA path contains the intermediary and root certificates that are related to the certificate file you want to use.
.... Select Deploy. The *Key Passcode* field is disabled. If you upload a new key file, the field is again enabled.
+
The PEM file information is saved in the global secrets group for your organization.

*** Option 2: Upload JKS
+
This option uses the TLS default values. Refer to <xref:anypoint-security::configure-tls-context-rtf-lb.adoc> for additional information.
.... Specify a value for *Keystore File*, the keystore file to use.
.... Specify a value for *Keystore Passcode*, the word or phrase that protects the keystore.
.... Specify a value for *Alias*. The alias is used to access the keystore entries (key and trusted certificate entries).
+
[NOTE]
This field is enabled after you specify a keystore file and keystore passcode.
.... In the  `Choose Alias From Keystore` window, select an alias. The following information is displayed:
***** The URL format to be used for your apps, based on the certificate’s CN.
+
The certificate must be set with a passphrase and a CN that specifies the domain for each application deployed to Runtime Fabric.
***** If the CN contains a wildcard, the endpoint for each deployed application takes the form `{app-name}.{common-name}`.
***** If the CN does not contain a wildcard, the endpoint takes the form `{common-name}/{app-name}`.
***** The expiration date of the secret.
.... Specify a value for *Key Passcode*, the word or phrase that protects the private key.
+
[NOTE]
This field is enabled after you specify an alias.
.... Make sure you have entered values for *Keystore File*, *Keystore Passcode*, *Alias*, and *Key Passcode* before continuing.
.... Select *Deploy*. The *Keystore Passcode* and *Key Passcode* fields are disabled.
***** If you select a different *Alias* value, the *Key Passcode* field is again enabled.
***** If you upload a new keystore file, the *Alias* and *Keystore Passcode* fields are again enabled and the *Alias* field contents are cleared.
+
The JKS file information is saved in the global secrets group for your organization.

*** Option 3: Import from Secrets Manager (for advanced users)
+
Select this option to create a TLS context or change TLS defaults, including adding or removing a TLS version, configuring mutual authentication, or changing cipher suites. For additional information, refer to xref:anypoint-security::configure-tls-context-rtf-lb.adoc[Configure a TLS Context for Anypoint Runtime Fabric].
+
This option is automatically selected for Runtime Fabrics that were configured prior to Runtime Fabric release <xxx>. 
Refer to xref:anypoint-security::configure-tls-context-rtf-lb.adoc for instructions.

. (Optional) Select Security Policies
+
A security policy must be defined in Anypoint Security to be displayed as an option in *Security Policies*. To define a security policy in Anypoint Security, you must have the *Anypoint Security - Edge* entitlement for your Anypoint Platform account.
+ If you don't see *Security* listed in *Management Center*, contact your customer success manager to enable Anypoint Security for your account.
+
Refer to https://docs.mulesoft.com/anypoint-security/index-policies for additional information.

. (Optional) Select Advanced Options
+
The following table describes additional configuration options you might need to set for your environment. In this 
case, *Source IP* refers to the client making the request.
+
[%header%autowidth.spread,cols="a,a"]
|===
|Value |Description
| *Max Connections*
| The maximum number of simultaneous connections to allow.

*Default value*: 512 connections

| *Max Requests per Connection*
| The maximum number of requests per connections to allow. +
Because this value determines how much reuse a connection allows, consider the amount of CPU required to terminate and reestablish a TLS-encrypted connection when lowering this value.

*Maximum allowed*: 1000 requests per connection

*Default value*: 1000

| *Connection Idle Time-out*
| The maximum amount of time that allowed for an idle connection. +
This value helps you terminate idle connections and free resources. +
This value should always be higher than your *Read Request Time-out*.

*Default value*: 15 seconds

| *Read Request Time-out*
| The maximum amount of time spent to read a request before it is terminated.+
This value enables requests with large payloads or slow clients to be terminated to keep resources available.+
This helps guard against connection pool exhaustion from slow requests or from clients who don't close connections after a response is sent.

If a Mule application takes longer than this value to respond, the connection is automatically closed. +
This value should always be lower than the *Connection Idle Time-out* value previously configured.

*Default value*: 10 seconds

| *Read Response Time-out*
| The maximum amount of time spent to initiate a response before the connection is terminated.+
This value enables requests with large payloads be terminated to keep resources available.+

*Default value*: 300 seconds

| *Write Response Time-out*
| The maximum amount of time spent from the end of the request header read to the end of the response write before the request is terminated.+

*Default value*: 10 seconds

| *Max Pipeline Depth*
| The maximum number of requests to allow from the same client. +
This value defines how many simultaneous requests a client can send. +
If a client exceeds this number, the exceeding requests are not read until the requests in the queue receive a response.

*Default value*: 10 requests per client

| *Source IP header name* and *enable proxy protocol* 
| Set these configurations if Runtime Fabric is behind a load balancer.

The values to configure here depend on your scenario:

. Runtime Fabric is not behind a load balancer. +
Runtime Fabric is not deployed behind a load balancer, these values should not be configured.
+
*Source IP header name*: blank +
*Enable proxy protocol*: Unchecked
. Runtime Fabric is behind an AWS Load Balancer with a Proxy Protocol configured. +
 If Runtime Fabric is deployed behind an AWS load balancer with a proxy protocol enabled, you must select the *enable proxy protocol* option.
+
*Source IP header name*: blank +
*Enable proxy protocol*: checked
. Runtime Fabric is behind a non-AWS load balancer. +
 If Runtime Fabric is deployed behind another type of load balancer, such as F5 or nginx, the source IP header name will need to be provided. Two common source IP headers are:
+
* Forwarded: An RFC7239 compliant IP header.
* X-Forwarded-For: Non-standard pre-2014 header containing one or more IPs from a Load Balancer (For example: “192.16.23.34, 172.16.21.36")
+
*Source IP header name*: non-blank +
*Enable proxy protocol*: unchecked

*Default value*: blank and unchecked.

|=== 

. (Optional) Configure Internal Load Balancer Logs
+
You can define the log levels for the internal load balancer. Runtime Fabric supports the following log levels, listed in descending order of verbosity:
+
** FATAL
** ERROR
** WARNING
** INFO
** VERBOSE
** DEBUG
** TRACE
+
The more verbose log levels, WARNING to TRACE, consume more CPU resources for each request. Consider this when adjusting the log level and allocating resources for the internal load balancer.
+
By default, the activity across all IPs addresses behind your endpoint is logged. To help reduce CPU consumption when using more verbose log levels, add IP filters to only log-specific IP addresses. This feature also reduces the quantity of logs when debugging a connection for a specific or limited number of IP addresses.

.. From Anypoint Platform select *Runtime Manager*.
.. Select *Runtime Fabric*.
.. Select the *Inbound Traffic* tab, and then select *Logs +*.
.. Select *Add Filter*.
.. In the *IP* field, enter a single IP address or subset of addresses using CIDR notation.
.. Select the log level to apply to this IP filter.
.. Select *OK*.

. Select *Deploy* to deploy the internal load balancer.
+
The deployment can take up to a minute to complete. If successful, a message is displayed. You can view the deployment status at the beginning of the page. When the status transitions to *Applied*, the internal load balancer is successfully deployed and inbound traffic is enabled.

== Step 3: Verify that Inbound Traffic is Enabled
To resolve the CN of applications deployed on Runtime Fabric, DNS must be configured to map the CN to the IP address of the external load balancer or of each controller VM. 

To test inbound traffic for applications before configuring DNS, send a request to the application using the IP address and a host header set to the domain.

The structure of the domain depends on whether a wildcard was used in the CN of your certificate, for example:

* A CN with a wildcard (e.g. *.example.com) uses the following request header format: `Host: {app-name}.example.com`. Use the following cURL command to verify:
+
----
curl -Lvk -XGET https://{ip-address}/{path} -H 'Host: {app-name}.example.com'
----

* A CN without a wildcard (e.g. example.com) uses the following request header format: `Host: example.com`. Use the following cURL command to verify:
+
----
curl -Lvk -XGET https://{ip-address}/{app-name}/{path} -H 'Host: example.com'`
----

== Step 4: After Enabling Inbound Traffic
Runtime Fabric must be configured to route incoming traffic to each enabled application in order for clients to send requests to deployed applications:
. Configure an external load balancer to load balance HTTPS traffic between each controller VM on Runtime Fabric.

** External Load Balancer Requirements
+
Controller VMs are virtual machines dedicated to run the components that power Anypoint Runtime Fabric. Each controller VM runs a replica of the internal load balancer and is configured to listen on port 443. When running multiple controller VMs, you must have an external load balancer outside Runtime Fabric to front each of the controller VMs.
+
The external load balancer must support TCP load balancing and must be configured with a server pool containing the IP addresses of each controller VM. A health check must also be configured on the external load balancer, listening on port 443.
+
This configuration of the external load balancer provides the following benefits:
** Maintains high availability.
** Protects against failures.
** Gracefully handles automated failover if a replica of the internal load balancer restarts or is evicted and rescheduled on another controller VM.
. Review the information described in *Advanced Options* when adding an external load balancer.
. Configure DNS before using the CN obtained from the TLS certificate. DNS is required to send requests to applications or API gateways deployed to Runtime Fabric. Add an "A record" to your DNS provider to map the CN to the IP address of the external load balancer or controller VMs.

== Step 5: Deploy Applications
When you are ready to deploy an application, follow the instructions in xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric].

The *Ingress* tab allows you to specify whether inbound traffic should be allowed for the application. After you enable inbound traffic, the default behavior is changed to allow for new application deployments. If there are applications deployed to Runtime Fabric before you enable inbound traffic, they do not receive inbound requests until this setting is enabled.

== TLS Certificate Expiration
Certificates (both self-signed and CA-signed) always have an expiration date. By default, certificates expire one year after they are created. 

The following warnings are displayed for certificates that will expire within 30 days to allow you to upload a new certificate-key pair before a certificate expires:

* On the *Runtime Fabrics* page, when a TLS certificate will expire within the next 30 days,`TLS Expiring` is displayed in the *Inbound traffic* column. On the `Runtime Fabrics` page, when a TLS certificate has expired, a warning is displayed in the *Inbound traffic* column for that RTF.
* On the *Inbound Traffic tab, when a TLS certificate will expire within the next 30 days, a warning is displayed. When a TLS certificate has expired, the expiration date information includes a red warning in the *Certificate File* field.

== See Also

* xref:deploy-resource-allocation.adoc[Determine resource allocation on Anypoint Runtime Fabric]
* xref:deploy-to-runtime-fabric.adoc[Deploy a Mule application to Anypoint Runtime Fabric]
