= General Prerequisites for Anypoint Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following sections list the general requirements and considerations for successfully using Anypoint Runtime Fabric. Ensure the following criteria have been met before beginning the installation.

Consult your network or operations administrators to ensure that these are in place before installing Anypoint Runtime Fabric.

=== Anypoint Platform Roles and Permissions

To succesfully use Anypoint Runtime Fabric, your Anypoint Platform account must have the following roles and permissions enabled:

* Ability to use Anypoint Runtime Manager to deploy and manage applications.
* Ability to use Anypoint Access Management to manage permissions for Anypoint Platform users.
** To use Anypoint Runtime Fabric, you must have the *Organization Administrators* role or the *Manage Runtime Fabrics* permission on the corresponding environments.
* You may also require the following permissions to enable inbound traffic to Runtime Fabric:
** Grant Access to Secrets
** Manage Secret Groups
** Read Secrets Metadata
** Write Secrets
+
These permissions are available from the *Secrets Manager* tab in Access Management .
** To deploy applications, you must have the *Exchange Contributors* role enabled for your Anypoint Platform account.

=== Network and Security

To successfully install and use Anypoint Runtime Fabric, you must know and verify the following about your network:

* Your organization requires outbound connections to be routed to a proxy.
* Outbound access is allowed using websockets (via port 443) to Anypoint Platform.
* Your organization's network and security policies, including:
** Internal network IP address range in CIDR notation.
** The subnet range used for Runtime Fabric in CIDR notation.
** If virtual machines are allowed public IP addresses.
** How to gain shell access to each VM.
* Know if inbound traffic should be enabled for Anypoint Runtime Fabric. This will likely be based on the function of your organization's Mule applications.
** If so, you must have a TLS certificate with the desired Common Name set to route traffic to Runtime Fabric.
** Ability to create or configure an external TCP load balancer to manage traffic to applications running in Runtime Fabric.
** Ability to configure DNS settings to associate the Common Name on the TLS certificate to the IP address of the external load balancer.

=== Infrastructure and Operations

To successfully install and use Anypoint Runtime Fabric, your network infrastructure must have:

* Required hardware provisioned, or have enough quota with your infrastructure provider to create the required hardware. This includes:
** Virtual machines
** Disks with provisioned IOPS
** Virtual networks
** Firewall rules / security groups
** Load balancers
* If provisioning hardware with AWS or Azure, you must have the right permissions to create the above resources.
* You must understand how to forward logs to your organization's logging provider.
* Details on your organization's SMTP provider to configure alerts.

=== Mule

To deploy Mule applications and API proxies, you must have the following:

* Access to your organization's Mule license key(s).
* One or more Mule applications.
