= Anypoint Runtime Fabric Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Runtime Fabric is a container service that allows you to run Mule applications, composite APIs and API gateways across any environment with centralized management via Anypoint Platform.

Some of the capabilities of Anypoint Runtime Fabric include:

* Isolation between applications by running a separate Mule runtime per application.
* Ability to run multiple versions of Mule runtime on the same set of resources.
* Scaling applications across multiple replicas.
* Automated application fail-over.
* Application management with Anypoint Runtime Manager.

[NOTE]
Contact your Customer Success Manager for information on how enable Anypoint Runtime Fabric on your account.

There are two management options for Anypoint Runtime Fabric:

* *Runtime Fabric on self-managed Kubernetes*: a version of Runtime Fabric that you install on an existing Kubernetes environment that you operate and manage. This version supports Amazon Elastic Kubernetes Service (EKS) and Azure Kubernetes Service (AKS)

* *Runtime Fabric on VMs / bare metal*: a version of Runtime Fabric where MuleSoft provides the required software components, including Docker and Kubernetes. You install this version on virtual machines that you operate and manage.

Each of these options has its own system requirements and installation procedures. See xref:index-self-managed.adoc[Runtime Fabric Self-managed] and xref:index-appliance.adoc[Runtime Fabric Appliance] for more information.

== Feature Support Matrix for the Self-managed and Appliance Versions of Runtime Fabric

[%header,cols="3*a"]
.Supported features for the self-managed and appliance versions of Runtime Fabric
|===
| | RTF Self-managed | RTF Appliance
| Support for deploying Mules and API Gateways | Supported | Supported
| Kubernetes and Docker | Not included. +
You must provide your own Kubernetes and Docker services via EKS or AKS clusters. | Included
| Support for installing on any Linux distribution | Supported | RHEL and CentOS only
| Support for node auto-scaling | Supported using AWS or Azure settings | Not supported
| Support for external log forwarding | You must provide an external log forwarding service | Included
| Support for an internal load balancer | You must provide an internal load balancer (Ingress Controller) | Included
| Support for Anypoint Security Edge | Not supported | Supported
| Ops Center | Not Included +
You can enable monitoring and alerting in AWS or Azure | Included
|===


== Anypoint Runtime Fabric and Standalone Mule Runtimes (Hybrid Deployments)

Hybrid deployments of Mule applications require you to install a version of the Mule runtime on a server and deploy one or more applications on the server. Each application shares the Mule runtime and the resources made available to it. Other resources such as certificates or database connections may also be shared using domains.

Anypoint Runtime Fabric provisions resources differently. Each Mule application and API gateway runs within their own Mule runtime and in their own container. The resources the container can access is specified when deploying a Mule application or API proxy. This enables Mule applications to horizontally scale across VMs without relying on other dependencies. It also ensures that different applications do not compete with each other for resources on the same VM.

== See Also

* xref:architecture.adoc[Runtime Fabric Architecture]
* xref:install-prereqs.adoc[Anypoint Runtime Fabric Installation Prerequisites]
