= Anypoint Runtime Fabric Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Runtime Fabric is a container service that allows you to run Mule applications, composite APIs and API gateways across any environment with centralized management via Anypoint Platform.

Some of the capabilities of Anypoint Runtime Fabric include:

* Isolation between applications by running a separate Mule runtime per application.
* Ability to run multiple versions of Mule runtime on the same set of resources.
* Scaling applications across multiple replicas.
* Automated application fail-over.
* Application management with Anypoint Runtime Manager.

[NOTE]
Contact your Customer Success Manager for information on how enable Anypoint Runtime Fabric on your account.

There are two management options for Anypoint Runtime Fabric:

* *Runtime Fabric on self-managed Kubernetes*: a version of Runtime Fabric that you install on an existing Kubernetes environment that you operate and manage. This version supports Amazon Elastic Kubernetes Service (EKS) and Azure Kubernetes Service (AKS)

* *Runtime Fabric on VMs / bare metal*: a version of Runtime Fabric where MuleSoft provides the required software components, including Docker and Kubernetes. You install this version on virtual machines that you operate and manage.

Each of these options has its own system requirements and installation procedures. See xref:index-self-managed.adoc[Runtime Fabric Self-managed] and xref:index-appliance.adoc[Anypoint Runtime Fabric on VMs / Bare Metal] for more information.

[%header,cols="3*a"]
.Personas required to install and support Anypoint Runtime Fabric
|===
| RTF Version | IT Administrator | MuleSoft Organization Administrator
| VMs / bare metal | Creates and configures the infrstructure that runs RTF. This persona is also responsible for installing RTF and maintaining the undrelying infrastructure during its operation. | Creates Runtime Fabrics, deploys projects, and performs other tasks within Anypoint Platform
| Self-managed Kubernetes | Requires an IT administrator to create and configure a Kubernetes cluster on AKS or EKS. This persona is also responsible for installing RTF and managing Kubernetes and AKS/EKS. | Creates Runtime Fabrics, deploys projects, and performs other tasks within Anypoint Platform
|===

== Feature Support Matrix for the Self-managed and VM / Bare Metals Versions of Runtime Fabric

[%header,cols="3*a"]
.Supported features for the self-managed and appliance versions of Runtime Fabric
|===
| | RTF Self-managed | RTF Appliance
| Support for deploying Mules and API Gateways | Supported | Supported
| Kubernetes and Docker | Not included. +
You must provide your instances of Kubernetes and Docker via EKS or AKS clusters. | Included
| Installing on any Linux distribution | Supported | Support for RHEL and CentOS only
| Node auto-scaling | Supported using AWS or Azure functionality | Not supported
| External log forwarding | You must provide an external log forwarding service | Included
| Internal load balancer | You must provide an internal load balancer (Ingress Controller) | Included
| Anypoint Security Edge | Not supported | Supported
| Ops Center | Not Included +
You can enable monitoring and alerting in AWS or Azure | Included
|===


== Anypoint Runtime Fabric and Standalone Mule Runtimes (Hybrid Deployments)

Hybrid deployments of Mule applications require you to install a version of the Mule runtime on a server and deploy one or more applications on the server. Each application shares the Mule runtime and the resources made available to it. Other resources such as certificates or database connections may also be shared using domains.

Anypoint Runtime Fabric provisions resources differently. Each Mule application and API gateway runs within their own Mule runtime and in their own container. The resources the container can access is specified when deploying a Mule application or API proxy. This enables Mule applications to horizontally scale across VMs without relying on other dependencies. It also ensures that different applications do not compete with each other for resources on the same VM.

== See Also

* xref:architecture.adoc[Runtime Fabric Architecture]
* xref:install-prereqs.adoc[Anypoint Runtime Fabric Installation Prerequisites]
