= Installing Runtime Fabric on Self-Managed Kubernetes

[IMPORTANT]
====
Installing Runtime Fabric on Self-Managed Kubernetes requires tasks that must be performed by both IT administrators and MuleSoft organization administrators.
====

You can install Anypoint Runtime Fabric on an Amazon Elastic Kubernetes Service (Amazon EKS), Azure Kubernetes Service (AKS) or Google Kubernetes Engine (GKE) installation that you manage. 

== Before you Begin

Before installing Anypoint Runtime Fabric in a self-managed Kubernetes environment, ensure:

* You have read and understand the architecture and requirements outlined in xref:index-self-managed.adoc[Runtime Fabric on Self-Managed Kubernetes]
* You have xref:install-self-managed-network-configuration.adoc[configured your network to support Runtime Fabric on Self-Managed Kubernetes]
* You have installed and configured your Kubernetes environment as follows:
+
** Running an EKS, AKS, or GKE Kubernetes environment. Other Kubernetes environments are not supported.
** Running a xref:index-self-managed.adoc#supported-kubernetes-versions[supported Kubernetes version]
** Running an ingress controller to send external requests to applications.


== Create a Runtime Fabric using Runtime Manager

[IMPORTANT]
====
The procedures in this section should be performed by a MuleSoft organization administrator.
====

To install Runtime Fabric on Self-Managed Kubernetes, first create a Runtime Fabric using Runtime Manager. This is required to obtain the activation data which is needed during installation.

. From Anypoint Platform, select Runtime Manager.
. Click *Runtime Fabrics*.
. Click *Create Runtime Fabric*.
. Enter the name of the new Runtime Fabric, then select one of the following options:
+
* Amazon Elastic Kubernetes Service
* Azure Kubernetes Service
* Google Kubernetes Engine

. Click *Next*.
. Review the *Support responsibility* disclaimer, then if you agree click *Accept*.
+
Runtime Manager creates the Runtime Fabric and displays the Activation State page. This page displays the activation data used to install Runtime Fabric on a Kubernetes service. Copy this data to the clipboard for use in the next section.


== Download the rtfctl Utility

[IMPORTANT]
====
The tasks in the section must be performed by an IT administrator.
====

Runtime Fabric on Self-Managed Kubernetes uses the `rtfctl` command-line utility for installation and management tasks. See xref:install-rtfctl.adoc[Install the Runtime Fabric Command Line Tool].


. Download the `rtfctl` command-line utility:
+
`rtfctl` is supported on Windows, MacOS (Darwin), and Linux. Download this utility using the URLs below:
+
*Windows:*
+
----
curl -L https://anypoint.mulesoft.com/runtimefabric/api/download/rtfctl-windows/latest -o rtfctl.exe
----
+
*MacOS (Darwin):*
+
----
curl -L https://anypoint.mulesoft.com/runtimefabric/api/download/rtfctl-darwin/latest -o rtfctl
----
+
*Linux:*
+
----
curl -L https://anypoint.mulesoft.com/runtimefabric/api/download/rtfctl/latest -o rtfctl
----

. Change file permissions for the `rtfctl` command-line utility:
+
----
sudo chmod +x rtfctl
----

== Install Runtime Fabric

[IMPORTANT]
====
The procedures in the section must be performed by an IT administrator.
====

After creating a Runtime Fabric in Runtime Manager and obtaining the activation data, install Runtime Fabric into your Kubernetes service using the `rtfctl` command-line utility.

If your Kubernetes configuration is not located in the `\~/.kube/config` directory, set the `KUBECONFIG` environment variable before running `rtfctl`:
----
export KUBECONFIG=<path-to-kubeconfig>
----


. Validate that your Kubernetes environment is read for installation:
+
----
rtfctl validate <activation_data>
----
+
The `validate` option verifies that:
+
* The Kubernetes environment is running.
* All required components exist.
* All required services are available.
+
The `rtfctl` command-line utility outputs any incompatibilities with the Kubernetes environment.

. Install Runtime Fabric:
+
----
rtfctl install <activation_data>
----
+
`<activation_data>` is the activation data obtained after creating the Runtime Fabric using Runtime Manager. During installation, the `rtfctl` utility displays any errors encountered.

include::partial$include-install-tasks.adoc[tags=licenseKey]
include::partial$include-install-tasks.adoc[tags=ingressResource]
include::partial$include-install-tasks.adoc[tags=validate]

== See Also

* xref:index-self-managed.adoc[Runtime Fabric on Self-Managed Kubernetes]
* xref:custom-ingress-configuration.adoc[Configure Ingress for Runtime Fabric on Self-Managed Kubernetes]
* xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric]
