= Anypoint Runtime Fabric Workflow
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic provides a high-level overview of the workflow for installing, configuring, and using Anypoint Runtime Fabric. If you are new to Anypoint Runtime Fabric, please read this topic.

Setting up Runtime Fabric occurs in the following steps:

. Provision and configure infrastructure
. Install & activate Runtime Fabric
. xref:runtime-fabric-logs.adoc[Configure Log Forwarding]
. xref:configure-alerting.adoc[Configure Alerting]
. xref:associate-environments.adoc[Associate Runtime Fabric to an Environment]
. xref:enable-inbound-traffic.adoc[Enable Inbound Traffic]


== Review the System and Network requirements

Before using Anypoint Runtime Fabric, you must make decisions about the resource requirements for your environment. You must also understand how different ports must be configured within your environment.

* xref:install-sys-reqs.adoc[System Requirements for Anypoint Runtime Fabric] provides information on supported configurations and the resources required.
* xref:install-port-reqs.adoc[Network Port Requirements for Anypoint Runtime Fabric] describes which ports are required to install and run Runtime Fabric.

== Create a Runtime Fabric in Runtime Manager

Before beginning to install Anypoint Runtime Fabric, you must create a Runtime Fabric using Runtime Manager. See xref:install-create-rtf-arm.adoc[Create a Runtime Fabric using Runtime Manager]. After creating the Runtime Fabric, you must perform the following:

* Download a ZIP file containing the installation scripts. This ZIP file contains scripts specific to the infrastructure provider.
* Record the activation data for the Runtime Fabric.


Before installing Runtime Fabric in your environment, create a Runtime Fabric using Runtime Manager. This enables you to:

* Specify the name of your Runtime Fabric.
* Download the installation scripts.
* Record the Runtime Fabric activation data used during the installation.

== Install Runtime Fabric

After determining resource requirements and creating a Runtime Fabric in Runtime Manager, provision the resources and install Runtime Fabric. The following environments are supported:

* xref:install-aws.adoc[Install Runtime Fabric on AWS]
* xref:install-azure.adoc[Install Runtime Fabric on Azure]
* xref:install-manual.adoc[Install Runtime Fabric Manually]

== Configure Runtime Fabric

After installing Runtime Fabric, perform additional configuration procedures as described in the following topics:

* xref:enable-inbound-traffic.adoc[Enable Inbound Traffic for Anypoint Runtime Fabric]
* xref:runtime-fabric-logs.adoc[Set up Log Forwarding on Anypoint Runtime Fabric]
* xref:configure-alerting.adoc[Set up Alerting on Anypoint Runtime Fabric]
* xref:using-opscenter.adoc[Access Ops Center on Anypoint Runtime Fabric]

== Deploy an Application

After installing and configuring Runtime Fabric, deploy Mule applications in your environment.

* xref:deploy-resource-allocation.adoc[Determine Application Resource Allocation on Runtime Fabric] describes how to determine the resources required for your application.
* xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to a Runtime Fabric] describes how to deploy an application to Runtime Fabric.

This topic provides an overview of the Anypoint Runtime Fabric installation process and describes how the installer works.

Anypoint Runtime Fabric is a container service built to run Mule applications and API gateways on a set of VMs. The Anypoint Runtime Fabric installer is optimized to require minimal user interaction. However, there are important configuration steps to complete after installation.
