= Install Runtime Fabric on Azure
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:noindex:

This topic describes how to install Anypoint Runtime Fabric on your Azure account.

[WARNING]
====
Before installing Runtime Fabric ensure your infrastructure meets the minimum hardware, operating system, and networking requirements.

Your organization's operations, networking and security teams should review these requirements. See xref:install-sys-reqs.adoc[System Requirements for Anypoint Runtime Fabric] and xref:install-port-reqs.adoc[Network and Port Requirements for Anypoint Runtime Fabric].
====

== Before you Begin

Before installing Anypoint Runtime Fabric on Azure, ensure the following requirements have been met:

* You have xref:install-create-rtf-arm.adoc[created a Runtime Fabric in Runtime Manager].
* Your Anypoint user account has the *Manage Runtime Fabrics* permission.
* Your Azure user has access to create VMs, Disks, Virtual Networks, and Network Security Groups.
* Your Azure account has enough quota for the infrastructure being provisioned.
* If your organization does not allow using public IPs for VMs, you may need to use an existing Virtual Network. Modify the Azure Resource Manager template to reference an existing Virtual Network.

== Installation

To begin installing Runtime Fabric, download the Azure Resource Manager template from Runtime Manager:

. From Anypoint Platform, navigate to Runtime Manager.
. Select *Runtime Fabrics*.
. Click on the Runtime Fabric you created. It should be in the `Activating` state.
. Click the *Download files* link.
. After the file has downloaded, unzip the `rtf-install-scripts.zip` file.

The `rtf-install-scripts\azure` directory contains the following installation files:

* `ARM-template-dev.template`: the Azure Resource Manager template that describes the infrastructure for the development configuration requirements.
* `ARM-template-prod.template`: the Azure Resource Manager template that describes the infrastructure for the production configuration requirements.
* `generate-templates.sh`: a shell script used to insert the Mule Enterprise license digest and initialization script in the ARM templates. This script outputs the JSON templates to use when deploying to Azure.

== Base64 Encode your Mule License Key

Run the `generate-templates.sh` script to add the Mule Enterprise license key in the Azure Resource Manager templates. These templates are used to provision the infrastructure needed.

[NOTE]
On Windows, you must have a shell terminal emulator (such as cygwin) or access to a Unix-based computer.

. Locate your organization's Mule Enterprise license key file (`license.lic`) and transfer the file to your Unix environment if necessary.
. Open a terminal/shell and navigate to the `azure` sub-directory.
. Copy the following to a text editor:
+
----
RTF_MULE_LICENSE='' \
./generate-templates.sh
----

. Using the terminal, encode the Mule Enterprise license key to base64 and paste the contents as the value for `RTF_MULE_LICENSE` in your text editor.
+
----
base64 -w0 license.lic # Linux

base64 -b0 license.lic # OSX / MacOS
----

. Copy the command from the text editor and run in the terminal pointed to the `azure` directory.
. Confirm the generated output of the `ARM-template-dev.json` and `ARM-template-prod.json` files in the `azure` directory.

== Deploy using the ARM Template

Run the generated ARM template to provision the infrastructure on your Azure account. The following procedures describe how to run the template via the Azure Portal.

[NOTE]
You must have a private and public key as a PEM file to provision the VMs. This is required to enable secure access to your VMs via SSH (Secure Shell).

. Log into your https://portal.azure.com[Azure portal].
. Navigate to *Create a resource*.
. From the *Search the marketplace* search bar, enter *Template deployment*.
. Click *Create* on the bottom of the window.
. Select *Build your own template in the editor*.
. In the bar above the editor, click *Load file* and select the desired Azure Resource Manager template from the `azure` directory. You must select a JSON file.
. When the file contents appears in the editor, click *Save*.
. Verify your Subscription selection, Resource group, and Region for your environment. In general, you should create a separate Resource group.
. Under *Settings*, enter the following:
+

[%header,cols="3*a"]
|===
|Variable | Description | Example
| `Public Key` | contains the public key string. This enables you to SSH into each VM with your associated private key. | `ssh rsa ...`
| `Anypoint Activation Data` | specifies the encoded Runtime Fabric activation data. You can access this data by viewing your Runtime Fabric in Runtime Manager. | `NzdlMzU1YTktMzAxMC00OGE0LWJlMGQtMDdxxxx`
| `SSH User Name` | specifies the user name to use when establishing a SSH connection to each VM. | `rtf-user`
| `Controller Instance Type` | specifies the Azure machine type to provision for each controller VM. The defaults are 2 cores and 8 GiB memory. | `Standard_D2s_v3`
| `Worker Instance Type` | specifies the Azure machine type to provision for each worker VM. The defaults are 2 cores and 16 GiB memory. | `Standard_E2s_v3`
| `Virtual Network CIDR` | specifies the address range to specify for the Virtual Network. Refer to your network specialist for assistance, if necessary. | `172.31.0.0/16`
| `Virtual Network Subnet` | specifies the address range for the subnet to use within the Virtual Network. Contact your system administrator for assistance, if necessary. | `172.31.3.0/28`
| `Installer IP Address` | specifies the IP address to assign the controller VM acting as the installer VM. This should be an available address which is within the subnet range specified. | `172.31.3.4`
| `Availability Set Update Domains` | specifies the number of update domains supported in the Azure region selected. | `3`
| `Availability Set Fault Domains` | specifies the number of fault domains supported in the Azure region selected. | `3`

|===

+
. Review and select the *Terms and Conditions* on the bottom of the page, then click *Purchase*.

Runtime Fabric is installed across all servers to form a cluster. This process takes time to complete. When complete, the status of Runtime Fabric displayed in Runtime Manager changes to `Active` status.

[NOTE]
By default, the ARM templates are configured to set a public IP address for each VM. Modify the template to remove the `publicIPAddresses`, if necessary.

== Monitoring Installation Progress

To follow the Azure provisioning process, follow these steps:

. On the left navigation bar in the Azure Portal, click on *Resource groups*.
. Select the Resource group used to provision your Runtime Fabric infrastructure.
. On the *Overview* pane under *Deployments*, click on the link below. This link should display something like `1 Deploying`.
. Click the Deployment Name *Microsoft.Template*.

You should be able to see the list of infrastructure and its status. Click *Refresh* button to update the pane and status.

To view the progress during the installation, you can tail the output log on each VM:

. Open a shell (or SSH session) to the VM.
. Tail the output log, located at `/var/log/rtf-init.log`
+
----
tail -f /var/log/rtf-init.log
----

You can tail the same log on each VM to view its progress.

When the installation completes successfully, the `/opt/anypoint/runtimefabric/.state/init-complete` file is created.

== Common Errors

Depending on the policies set and the quotas defined with your Azure account, you may encounter errors during the provisioning process. The ARM template can be modified to accommodate the policies set by your organization. Consult your network administrator as needed.

* *Exceed max core quota:* file a ticket with Azure Support to increase quota for your deployment region. If you believe you have enough quota, ensure the correct region is selected with the increased quota. Also, try modifying the Resource Group name to ensure it is unique to your account.
* *Network policy violation:* By default, the Network Security Groups defined in the Azure Resource Template are associated at the subnet level and the NIC for each VM. Depending on your company's policy, you may need to adjust the template to remove an association.


== Access Ops Center

After installation is completed successfully, login to Ops Center to view that status of your Runtime Fabric infrastructure. See xref:using-opscenter.adoc[Using Ops Center on Anypoint Runtime Fabric] for information on accessing Ops Center and determining the Ops Center username and password.

== Post Installation Configuration

Before deploying applications on Anypoint Runtime Fabric, you'll need to perform the following steps:

* xref:associate-environments.adoc[Associate Business Groups and Environments on Anypoint Runtime Fabric]
* xref:enable-inbound-traffic.adoc[Enable Inbound Traffic on Anypoint Runtime Fabric]
* xref:runtime-fabric-logs.adoc[Configure Log Forwarding on Anypoint Runtime Fabric]
* xref:configure-alerting.adoc[Configure Alerting on Anypoint Runtime Fabric]
