= Installing Runtime Fabric on EKS, AKS, and GKE Using rtfctl

You can use the Runtime Fabric command line tool, `rtfctl`, to install Anypoint Runtime Fabric on an Amazon Elastic Kubernetes Service (Amazon EKS), Azure Kubernetes Service (AKS) or Google Kubernetes Engine (GKE) installation that you manage. 

== Before you Begin

Before installing Anypoint Runtime Fabric in a Kubernetes environment, ensure:

* You have reviewed the architecture and requirements outlined in xref:index.adoc[Runtime Fabric]
* You have xref:install-self-managed-network-configuration.adoc[configured your network to support Runtime Fabric]
* You have installed and configured your Kubernetes environment with:
+
** An EKS, AKS, or GKE Kubernetes environment. Other Kubernetes environments are not supported.
** A supported Kubernetes version.
** An ingress controller to send external requests to applications.
* You create your clusters using the latest Runtime Fabric agent version available. If you can't do so, refer to https://help.mulesoft.com/s/article/RTF-Agent-upgrade-path[How to Specify the RTF Agent Version in Upgrades^].

[IMPORTANT]
====
* If you want to use a local registry with Runtime Fabric, follow the installation instructions in xref:configure-local-registry.adoc[Using a Local Registry with Runtime Fabric]. You must set up the local registry during installation. 
====

== Create a Runtime Fabric using Runtime Manager

To install Runtime Fabric, first create a Runtime Fabric using Runtime Manager. This is required to obtain the activation data which is needed during installation.

. From Anypoint Platform, select Runtime Manager.
. Click *Runtime Fabrics*.
. Click *Create Runtime Fabric*.
. Enter the name of the new Runtime Fabric, then select one of the following options:
+
* Amazon Elastic Kubernetes Service
* Azure Kubernetes Service
* Google Kubernetes Engine

. Click *Next*.
. Click *rtfctl*.
. Review the *Support responsibility* disclaimer, then if you agree click *Accept*.
+
Runtime Manager creates the Runtime Fabric and displays the Activation State page. This page displays the activation data used to install Runtime Fabric on a Kubernetes service. Copy this data to the clipboard for use in the next section.

== Download the rtfctl Utility

Runtime Fabric uses the `rtfctl` command-line utility for installation and management tasks. See xref:install-rtfctl.adoc[Install the Runtime Fabric Command Line Tool].


. Download the `rtfctl` command-line utility:
+
`rtfctl` is supported on Windows, MacOS (Darwin), and Linux. Choose the appropriate method:
+
* Windows
+
[source,copy]
----
curl -L https://anypoint.mulesoft.com/runtimefabric/api/download/rtfctl-windows/latest -o rtfctl.exe
----
+
* MacOS (Darwin)
+
[source,copy]
----
curl -L https://anypoint.mulesoft.com/runtimefabric/api/download/rtfctl-darwin/latest -o rtfctl
----
+
* Linux
+
[source,copy]
----
curl -L https://anypoint.mulesoft.com/runtimefabric/api/download/rtfctl/latest -o rtfctl
----

. Change file permissions for the `rtfctl` command-line utility:
+
[source,copy]
----
sudo chmod +x rtfctl
----

== Install Runtime Fabric

After creating a Runtime Fabric in Runtime Manager and obtaining the activation data, install Runtime Fabric into your Kubernetes service using the `rtfctl` command-line utility.

If your Kubernetes configuration is not located in the `\~/.kube/config` directory, set the `KUBECONFIG` environment variable before running `rtfctl`:
[source,copy]
----
export KUBECONFIG=<path-to-kubeconfig>
----

. Validate that your Kubernetes environment is ready for installation:
+
[source,copy]
----
rtfctl validate <activation_data>
----
+
The `validate` option verifies that:
+
* The Kubernetes environment is running.
* All required components exist.
* All required services are available.
+
The `rtfctl` command-line utility outputs any incompatibilities with the Kubernetes environment.

. Install Runtime Fabric:
+
[source,copy]
----
rtfctl install <activation_data>
----
+
`<activation_data>` is the activation data obtained after creating the Runtime Fabric using Runtime Manager. During installation, the `rtfctl` utility displays any errors encountered.

include::partial$include-install-tasks.adoc[tags=licenseKey]
include::partial$include-install-tasks.adoc[tags=ingressResource]
include::partial$include-install-tasks.adoc[tags=validate]

== See Also

* xref:index.adoc[Runtime Fabric Overview]
* xref:custom-ingress-configuration.adoc[Configure Ingress for Runtime Fabric]
* xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric]
