= Install Runtime Fabric on Azure
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:noindex:

This topic describes how to install Anypoint Runtime Fabric on your Azure account.

[WARNING]
====
Ensure your infrastructure meets the minimum hardware, operating system, and networking requirements. These requirements should be reviewed by your organization's operations, networking and security teams.
====

== Before you Begin

Ensure the following criteria have been met before beginning the installation:

* You have xref:install-create-rtf-arm.adoc[created a Runtime Fabric in Runtime Manager].
* Your Azure user has access to create VMs, Disks, Virtual Networks, and Network Security Groups.
* Your Azure account has enough quota for the infrastructure being provisioned.
* Your Anypoint user account has the *Manage Runtime Fabrics* permission.
* If your organization does not allow using public IPs for VMs, you may need to use an existing Virtual Network. The Azure Resource Manager template can be modified to reference an existing Virtual Network.

== Installation

First, download the Azure Resource Manager template from Runtime Manager.

. Sign in to Anypoint platform and navigate to Runtime Manager.
. On the left navigation pane, select *Runtime Fabrics*.
. Click on the Runtime Fabric you created. It should be in the Activating state.
. Click the *Download files* link.
. Once downloaded, unzip the `rtf-install-scripts.zip` file.

Inside the `rtf-install-scripts` directory, you'll find a directory named `azure` containing the following:

* `ARM-template-dev.template`: the Azure Resource Manager template describing the infrastructure per the development configuration requirements.
* `ARM-template-prod.template`: the Azure Resource Manager template describing the infrastructure per the production configuration requirements.
* `generate-templates.sh`: a shell script used to insert the Mule Enterprise license digest and initialization script in the ARM templates, outputting the JSON templates to use when deploying to Azure.

=== Add Mule License Key in ARM Templates

Second, run the `generate-templates.sh` script to add the Mule Enterprise license key in the Azure Resource Manager templates. The resulting templates will then be used to provision the infrastructure needed.

If you're using Windows, you'll need a shell terminal emulator (such as cygwin) or access to a Unix-based computer to follow these steps:

. Find your organization's Mule Enterprise license key file (`license.lic`) and transfer to your Unix environment if necessary.
. Open a terminal/shell and navigate to the `azure` sub-directory.
. Copy the command below in a text editor to make it easier to add in the Mule Enterprise license before running:
+
----
RTF_MULE_LICENSE='' \
./generate-templates.sh
----
+
* Using the terminal, encode the Mule Enterprise license key to base64 and paste the contents as the value for `RTF_MULE_LICENSE` in the text editor.
+
----
base64 -w0 license.lic # Linux
base64 -b0 license.lic # OSX
----
+
. Copy the command from the text editor and run in the terminal pointed to the `azure` directory.
. Confirm the output of the `ARM-template-dev.json` and `ARM-template-prod.json` files in the `azure` directory.

=== Deploy using ARM Template

Third, run the ARM template to provision the infrastructure on your Azure account. Below are instructions on how to run the template via the Azure Portal.

[NOTE]
You'll need a private and public key as a PEM file to provision the VMs. This is required to enable secure access to your VMs via SSH (Secure Shell).

. Log into your https://portal.azure.com[Azure portal].
. Navigate to "Create a resource".
. On the "Search the marketplace" search bar, type in "Template deployment".
. Click "Create".
. Select "Build your own template in the editor."
. On the bar above the editor, click "Load file" and select the desired Azure Resource Manager template from the `azure` directory. A JSON file should be selected.
. After the editor is populated with the contents of the file, click "Save".
. Verify your Subscription selection, Resource group, and Region for deployment. In most cases, it's recommended to create a separate Resource group.
. Under Settings, fill in the following parameters:
+

[%header,cols="3*a"]
|===
|Variable | Description | Example
| `Public Key` | The public key string. This will enable you to SSH into each VM with your associated private key. | `ssh rsa ...`
| `Anypoint Activation Data` | The encoded Runtime Fabric activation data found in Runtime Manager. | NzdlMzU1YTktMzAxMC00OGE0LWJlMGQtMDdxxxx
| `SSH User Name` | The user name to use when establishing a SSH connection to each VM. | `rtf-user`
| `Controller Instance Type` | The Azure machine type to provision for each controller VM. Default set to 2 cores and 8 GiB memory. | `Standard_D2s_v3`
| `Worker Instance Type` | The Azure machine type to provision for each worker VM. Default set to 2 cores and 16 GiB memory. | `Standard_E2s_v3`
| `Virtual Network CIDR` | The address range to specify for the Virtual Network. Refer to your network specialist for assistance, if necessary. | `172.31.0.0/16`
| `Virtual Network Subnet` | The address range to specify for subnet to use within the Virtual Network. Refer to your network specialist for assistance, if necessary. | `172.31.3.0/28`
| `Installer IP Address` | The IP address to assign the controller VM acting as the installer VM. This should be an available address which is within the subnet range specified. | `172.31.3.4`
| `Availability Set Update Domains` | The number of update domains supported in the Azure region selected. | `3`
| `Availability Set Fault Domains` | The number of fault domains supported in the Azure region selected. | `3`

|===

+
. Review and select the Terms and Conditions on the bottom of the page, and click "Purchase".

This step installs Runtime Fabric across all servers to form a cluster. It may take 15-25 minutes or longer to complete. When complete, the Runtime Fabric will update to the Active status in Runtime Manager.

[NOTE]
By default, the ARM templates are configured to set a public IP address for each VM. The template can be modified to remove the `publicIPAddresses`, if necessary.

== Monitoring the Installation

Your infrastructure will be created. Follow these steps to view the progress:

. On the left navigation bar in the Azure Portal, click on "Resource groups".
. Select the Resource group used to provision your Runtime Fabric infrastructure.
. On the Overview pane under Deployments, click on the link below, which may read "1 Deploying".
. Click on the Deployment Name "Microsoft.Template".

You should be able to see the list of infrastructure and its status. Click the "Refresh" button to update the pane and status.

To view the progress during the installation, you can tail the output log on each VM:

. Open a shell (or SSH session) to the VM.
. Tail the output log, located at `/var/log/rtf-init.log`
+
----
tail -f /var/log/rtf-init.log
----

[NOTE]
You can tail the same log on each VM to view its progress.

When the installation completes successfully, the file `/opt/anypoint/runtimefabric/.state/init-complete` is created.

=== Access to Ops Center

After installation is completed successfully, the last few lines of the log output file located at `/var/log/rtf-init.log` will contain a host, username, and password to access the Ops Center. Copy these values and store them securely.

== Common Errors

Depending on the policies set and the quotas defined with your Azure account, you may encounter errors during the provisioning process. The ARM template can be modified to accommodate the policies set by your organization. Consult your operations team as needed.

* *Exceed max core quota:* File a ticket with Azure Support to increase quota for your deployment region. If you believe you have enough quota, ensure the right region is selected with the increased quota. Also, try modifying the Resource Group name to ensure it is unique to your account.
* *Network policy violation:* By default, the Network Security Groups defined in the Azure Resource Template are associated at the subnet level and the NIC for each VM. Depending on your company's policy, you may need to adjust the template to remove an association.

== Next Steps

Before deploying applications on Anypoint Runtime Fabric, you'll need to perform the following steps:

* xref:associate-environments.adoc[Associate an environment to Runtime Fabric]
* xref:enable-inbound-traffic.adoc[Enable inbound traffic to Runtime Fabric] (optional)