= Install Runtime Fabric on Self-managed Kubernetes

You can install Anypoint Runtime Fabric into a Kubernetes service that you manage on Amazon Web Services of Microsoft Azure. 

== Before you Begin

Before installing Anypoint Runtime Fabric in a self-managed Kubernetes service, ensure the following:

* You have installed and configured your Kubernetes cluster as follows:
+
- Running Kubernetes version 1.14.x to 1.18.x
- Contains an Ingress controller to connect external applications to the internal Runtime Fabric services.
* You have downloaded and installed the `rtfctl` script.
+
`rtfctl` is supported on Windows, Darwin, and Linux. To download this script use the following command:
+
----
curl -L https://qax.anypoint.mulesoft.comruntimefabric/api/download/rtfctl/latest -o rtfctl
----

== Create a Runtime Fabric using Runtime Manager

To install Runtime Fabric on a self-managed Kubernetes cluster, first create a Runtime Fabric using Runtime Manager. This is required to obtain the necessary 

. From Anypoint Platform, select Runtime Manager.
. Click *Runtime Fabrics*.
. Click *Create Runtime Fabric*.
. Enter the name of the new Runtime Fabric, then select one of the following options:
+
* Amazon Elastic Kubernetes Service
* Azure Kubernetes Service

. Click *Next*.
. Review the *Support responsibility* disclaimer, then if you agree click *Continue*.
+
Runtime Manager creates the Runtime Fabric and displays the Activation State page. This page displays the activation data used to install runtime fabric on a Kubernetes service. Copy this data to the clipboard for use in the next section. 


== Install Runtime Fabric on a Self-Managed Kubernetes Service

After creating a Runtime Fabric and getting the activation data, install Runtime Fabric into your Kubernetes service using the `rtfctl` command.

[NOTE]
====
Run `rtfctl --help` to see a list of options for this command.
====

. From the command line, run `rtfctl --validate`.
+
The `--validate` option verifies that the Kubernetes service is running, that all required components exist, and that all required services are available. The `rtfctl` command outputs any problems is encounters.

. Run the `rtfctl --install` command using the following syntax:
+
----
rtfctl --install <activation_data>
----
+
Where <activation_data> is the activation data obtained after creating the Runtime Fabric using Runtime Manager.
+
During installation, the `rtfctl` command displays any errors.

. If the installation completed succesfully, update the Mule license:
+
----
rtfctl --update mule-license
----

== Validating Runtime Fabric on a Self-Managed Kubernetes Service

*SL Note: How would the user validate that RTF is running? Deploy an app and hit the URL?*

