= Limitations with Anypoint Runtime Fabric on Self-Managed Kubernetes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following information is important when installing, configuring, and managing Anypoint Runtime Fabric on Self-Managed Kubernetes.

[cols="2*a"]
.Anypoint Runtime Fabric on Self-Managed Kubernetes resource allocation 
|===
| Nodes | The maximum number of nodes supported is 30.
| Node Types | VM-based nodes are required. For example, Fargate is not supported.
| Replicas Per Node | The maximum number of replicas that can be deployed per node is 40.

Run no more than 20 - 25 replicas per core, up to a maximum of 40 replicas per node, to allow core sharing across replicas when needed for bursting. This ensures the Runtime Fabric’s internal components that run on each worker node are not overloaded by too many replicas.
| Associated Environments per Runtime Fabric | You can associate a Runtime Fabric with up to 100 environments in any Business Group. For example, if you associate a development and a production environment with Org A and a dev environment with Org B, that is three environment associations. 
| Business Groups | You can create up to 50 Runtime Fabrics per org in a Business Group. Any sub org can contain up to 50 Runtime Fabrics, in addition to any shared by another sub org. For example, if you have master Org A and its child Org B, you can have 50 Runtime Fabrics in Org A and 50 in Org B. You can also share all 50 Runtime Fabrics from Org A with Org B, and as a result, you will see 100 Runtime Fabrics in total in the list view of Org B.
| Object Store Persistence | To manage data persistence across Mule application replicas and restarts, Anypoint Runtime Fabric uses Persistence Gateway. See xref:persistence-gateway.adoc[Persistence Gateway].
|===

== How Antivirus and DPI Software Impacts Runtime Fabric Functionality

The Anypoint Runtime Fabric appliance has specific hardware and OS requirements. MuleSoft Support provides Support SLA and Severity Levels based on our validation and certification of the requirements specified in the xref:install-prereqs.adoc[installation prerequisites].

A small number of third-party software that requires root access to the host, which includes, but is not limited to, antivirus and DPI software, has been found to interfere with the behavior and requirements of the Runtime Fabric appliance. In many support cases where MuleSoft Support has detected antivirus software, they have seen issues such as port blocking, node-to-node communication blocking, Docker default bridge deletion, and filesystem access issues that interfere with Runtime Fabric appliance installation, upgrade, and normal operations.

In the event that abnormal behavior is observed with the Runtime Fabric appliance, you may be asked to disable any running third-party software (including anti-virus or DPI software) to determine if it is the cause of the behavior. If disabling such software restores proper Runtime Fabric appliance functionality, this would demonstrate an implicit incompatibility between that software package and the Runtime Fabric appliance, and we would consider the support case resolved.

If you are strictly required to run traditional security tools that interfere with certain components of the Runtime Fabric appliance, vendors and security experts that support Kubernetes are recommended to support you in meeting this requirement. Alternatively, you are encouraged to consider using Runtime Fabric on Self-Managed Kubernetes. Cloud platform vendors often add cloud-centric controls that are consistent with well-known security benchmarks, such as the https://www.cisecurity.org/benchmark/kubernetes/[Center for Internet Security (CIS) Kubernetes Benchmark^].
