= Monitoring Applications Deployed to Runtime Fabric

Runtime Fabric provides customers varying observability solutions depending on their needs:

== Anypoint Monitoring
By default, Runtime Fabric sends application metrics to Anypoint Monitoring. Titanium-plan customers also have application logs automatically sent to Anypoint Monitoring by default. For metrics and logs to be sent to Anypoint Monitoring, outbound network connectivity must be available. Refer to xref:use-anypoint-monitoring.adoc[]

== Log4j Appender
You can use a Log4j appender to integrate your logging system with applications deployed to Runtime Fabric. For information about configuring log4j2.xml, see the Log4j Configuration SyntaxLeaving the Site Refer to xref:use-log4j-appender.adoc[]

== Otel Tracing
OpenTelemetry enables Mule runtime engine to bring observability to the behavior of Mule apps, and also, because of distributed tracing, to the interaction between different Mule apps. There is no additional Runtime Fabric configuration to use OpenTelemetry. Refer to xref:mule-runtime::open-telemetry.adoc[]
