= Manage Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you install and configure Anypoint Runtime Fabric and deploy Mule applications and API proxies, you might need to perform additional tasks.

* Monitor and View

** View Runtime Fabric status.
+
See xref:view-health.adoc[View Runtime Fabric Health Details].
** Use Anypoint Monitoring and Anypoint Visualizer to monitor applications deployed to Runtime Fabric.
+
See xref:manage-monitor-applications.adoc[Monitor Applications Deployed to Runtime Fabric].
** Monitor the performance and health of your Runtime Fabric installation.
+
See xref:using-opscenter.adoc[Use Ops Center on Anypoint Runtime Fabric].

* Update

** Install rtfctl to manage Runtime Fabric settings.
+
See xref:install-rtfctl.adoc[Install rtfctl].
** Install patches and perform other scheduled maintenance on Runtime Fabric.
+
See xref:install-patches.adoc[Perform Scheduled Maintenance].
** Replace your Mule license key.
+
See xref:replace-license-key.adoc[Replace a Mule License Key].

* Maintain

** Configure proxy settings used by Runtime Fabric outbound connections.
+
See xref:manage-proxy.adoc[Manage Proxies Used by Runtime Fabric].
** Manage Runtime Fabric secure properties.
+
See xref:manage-secure-properties.adoc[Manage Secure Properties in Runtime Fabric].
** Enable mutual authentication.
+
See xref:config-mutual-auth.adoc[Configure Mutual Authentication with Anypoint Platform].
** Add or remove nodes from a cluster to maintain cluster health or to perform an upgrade.
+
See xref:manage-nodes.adoc[Add or Remove a Node from a Runtime Fabric].
** Stop and restart a Runtime Fabric.
+
This requires stopping and restarting each instance.
** Back up Runtime Fabric.
+
See xref:manage-backup-restore.aodc[Back up and Restore Runtime Fabric].

* Uninstall Runtime Fabric manually.
+
See xref:uninstall-manual.adoc[Uninstall Runtime Fabric Manually].

* Troubleshoot errors with installation or post-installation.
+
See xref:troubleshoot-guide.adoc[Troubleshooting Runtime Fabric].

== See Also

* xref:configure-alerting.adoc[Configure Alerting on Runtime Fabric]
