= Back up and Restore Runtime Fabric

To preserve applications in the event of system failure, confirm that Runtime Fabric is automatically backed up. When scheduling backups, follow best practices by configuring hourly backups. Store your backup archive on external storage outside the Runtime Fabric cluster.

The state of Runtime Fabric is distributed across the Kubernetes cluster. Use the following procedures to back up and restore the required state necessary for all deployed applications, management services, and their configurations. Individual node backup and restore operations are not supported. 

[WARNING]
====
Configuration changes to deployed applications and management services made after a back up cannot not be restored.  
====

[NOTE]
====
For Runtime Fabric running on VMs / Bare Metal, the backup process also includes backing up of underneath Kubernetes appliance related custom resources [logforwarder, smtp, alert and alerttarget].  
====


== Prerequisites for Runtime Fabric

Before performing a backup or restore operation:

* Verify that Runtime Fabric is installed and running successfully.
* Verify that `rtfctl` CLI tool is upgraded to version 0.3.102 or later. Verify the version by running `rtfctl version` on a Runtime Fabric node.
* If you are using Runtime Fabric on VMs / Bare Metal, verify that Runtime Fabric is upgraded to version 1.1.1581474166 or later. See xref:release-notes::runtime-fabric/runtime-fabric-installer-release-notes.adoc[Anypoint Runtime Fabric Installer Release Notes].

== Create a Backup

To create a backup run the following command:

----
./rtfctl backup <path_to_backup_file>
----

This command creates an archive of the current system state in `<path_to_backup_file>`, which can be any path in the file system that you have write access to, for instance `/opt/anypoint/runtimefabric/backup.tar.gz`. 

[NOTE]
====
For Runtime Fabric running on VMs / Bare Metal, the `rtfctl` binary is present in directory `/opt/anypoint/runtimefabric/`. Confirm that you run the backup command on any controller node in the cluster as a privileged user. To use the archive for restoring later, copy the archive file to secure storage that is on a different machine and is not part of the RTF cluster. The following command, for example, uses `scp` to copy the archive to another drive: 

----
scp your_username@remotehost:/opt/anypoint/runtimefabric/backup.tar.gz /backup-path/to-restore.tar.gz
----

For Runtime Fabric running on Self-Managed Kubernetes, confirm that the `rtfctl` binary is present in the current directory and Kubernetes(kubectl) context is set to the intended backup cluster.
====

== Restore a Cluster

To restore Runtime Fabric cluster from a backup, use an existing Runtime Fabric cluster or create a new Kubernetes cluster with the same configuration (number of servers, disks, and so on) as the backed up cluster.  

[NOTE]
====
To create a new Kubernetes cluster on VMs / Bare Metal without Runtime Fabric being installed, run the Runtime Fabric installer script(s) but do not provide the fabric activation data.
====

[WARNING]
====
For restoring on existing Runtime Fabric cluster, you must restore on to the same version of Runtime Fabric that you used to create the backup archive. You cannot restore from an older version to a newer version of Runtime Fabric running on the cluster.
====

. Copy backup archive file and make sure that it is available to `rtfctl`.

[NOTE]
====
For Runtime Fabric on VMs / Bare Metal, copy the compressed backup archive file to a folder in any of the controller nodes of the environment to be restored. For example, you can transfer this file securely via the following command: 

----
scp /backup-path/to-restore.tar.gz your_username@remotehost:/opt/anypoint/runtimefabric/
----

For Runtime Fabric on Self-Managed Kubernetes, confirm that the `rtfctl` binary is present in the current directory and the Kubernetes (kubectl) context is set to the cluster you are restoring to.

====

. Restore the cluster from the backup archive with following command:
+
----
rtfctl restore <path_to_backup_file>
----

[WARNING]
====
On the original backed up cluster, to restore into the newly created different cluster, scale down all Runtime Fabric components by running the following command: 
----
# Confirm that your Kubernetes(kubectl) context is set to the backed up cluster
`kubectl scale --replicas=0 -n rtf deployment.apps/agent`
----
====

This process may require several minutes to complete.

== See Also

* xref:manage-nodes.adoc[Add or Remove a Node from a Runtime Fabric]
* xref:install-prereqs.adoc[Anypoint Runtime Fabric Installation Prerequisites]
