= Managing Proxies on Runtime Fabric on VMs / Bare Metal

Anypoint Runtime Fabric clusters consistently communicate with the Anypoint Platform control plane and image repositories. Applications that are deployed in the cluster can also communicate with external endpoints.

You can configure the proxy settings used by Runtime Fabric outbound connections to the internet. This includes both HTTP proxies for connecting to the Anypoint Platform control plane and SOCKS5 proxies for sending metrics and logs to Anypoint Monitoring. You can also configure proxies for applications.

* <<configure-proxy, Configure an Anypoint Monitoring Proxy>>
* <<configure-http-proxy, Configure an HTTP Proxy for Services in Runtime Fabric>>
* <<configure-proxy-api, Configure a Proxy for the API Manager Agent>>
* <<configure-proxy-mule-app, Configure a Proxy for a Mule Application>>



Proxies used by Runtime Fabric can be configured during or after installation using the `rtfctl` utility. Application proxies are configured during application deployment.

== Install rtfctl 

The `rtfctl` command line tool is required to manage proxy settings on Runtime Fabric. Follow the steps to xref:install-rtfctl.adoc[Install rtfctl] before configuring proxy settings.

[IMPORTANT]
--
You must install Runtime Fabric before running `rtfctl apply proxy` commands.
--

include::partial$include-manage-proxies.adoc[tags=monitoring-proxy]
include::partial$include-manage-proxies.adoc[tags=http-proxy]
include::partial$include-manage-proxies.adoc[tags=api-manager-proxy]
include::partial$include-manage-proxies.adoc[tags=mule-app-proxy]


== See Also

* xref:install-rtfctl.adoc[]
* xref:install-prereqs.adoc[Anypoint Runtime Fabric Installation Prerequisites]
