= Back up and Restore Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Prerequisites

Before performing a backup or restore operation, verify that Runtime Fabric was installed or upgraded 
using  https://docs.mulesoft.com/release-notes/runtime-fabric/runtime-fabric-installer-release-notes[installer version 1.1.1581474166, role=external, window=_blank] or later, and that the rtfctl CLI tool is upgraded to version 0.2.95 or later.
The versions can be verified by running `rtfctl version` on a Runtime Fabric node.

To preserve applications in the event of system failure, ensure that Runtime Fabric is automatically backed up. 
MuleSoft highly recommends configuring hourly backups. Store your backup archive on external storage outside 
the Runtime Fabric cluster.

[NOTE]
The state of Runtime Fabric is distributed across its controller nodes. Use the following procedures to back up and restore
the required state necessary for all deployed applications, management services, and their configurations. 
Individual node backup and restore operations are not supported.

== Create a Backup

To create a backup:

. Run the following command on any controller node in the cluster as a privileged user (with root access):
+
----
./rtfctl backup <path_to_backup_file>
----
This command creates an archive of the current system state in `<path_to_backup_file>`, which can be any path in the file system that you have write access to, for instance `/opt/anypoint/runtimefabric/backup.tar.gz`. 

. Move the archive file to secure storage (a different machine that is not part of the RTF cluster);
for example:
+
----
scp your_username@remotehost:/opt/anypoint/runtimefabric/backup.tar.gz /backup-path/to-restore.tar.gz
----

== Restore a Cluster

To restore a Runtime Fabric cluster from a backup, you can use the existing Runtime Fabric cluster or create a new Runtime Fabric 
cluster with the same hardware (number of servers, disks, and so on) as the cluster being restored.

[WARNING]
You can not restore Runtime Fabric on a newer version of the Runtime Fabric cluster. The new installation must use 
the same version of Runtime Fabric installation bundle as the backup.

. Log in to a controller node in your Runtime Fabric as a privileged user (with root access).

. Move the compressed backup archive file to a folder in any of the controller nodes of the environment to be restored. 
You can transfer this file securely via the following command:
+
----
scp /backup-path/to-restore.tar.gz your_username@remotehost:/opt/anypoint/runtimefabric/
----

. Restore the cluster from the backup archive:
+
----
rtfctl restore /opt/anypoint/runtimefabric/to-restore.tar.gz
----

This process requires a few minutes.

== See Also

* xref:manage-nodes.adoc[Add or Remove a Node from a Runtime Fabric]
* xref:install-prereqs.adoc[Anypoint Runtime Fabric Installation Prerequisites]
