= Managing Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After you install and configure Anypoint Runtime Fabric and deploy Mule applications and API proxies, you might need to perform additional tasks.

* Monitor and View

** View Runtime Fabric status.
+
See xref:view-health.adoc[View Runtime Fabric Health Details].
** Use Anypoint Monitoring and Anypoint Visualizer to monitor applications deployed to Runtime Fabric.
+
See xref:manage-monitor-applications.adoc[Monitor Applications Deployed to Runtime Fabric].
** Monitor the performance and health of your Runtime Fabric installation.

* Update

** Install rtfctl to manage Runtime Fabric settings.
+
See xref:install-rtfctl.adoc[Install rtfctl].
** Install patches and perform other scheduled maintenance on Runtime Fabric.
+
** Replace your Mule license key.
+
See xref:replace-license-key.adoc[Replace a Mule License Key].

* Maintain

** Configure proxy settings used by Runtime Fabric outbound connections.
+
See xref:manage-proxy-self.adoc[Manage Proxies Used by Runtime Fabric].
** Manage Runtime Fabric secure properties.
+
See xref:manage-secure-properties.adoc[Manage Secure Properties in Runtime Fabric].
** Enable mutual authentication.
+
** Back up Runtime Fabric.
+
See xref:manage-backup-restore.adoc[Back up and Restore Runtime Fabric].

* Uninstall Runtime Fabric manually.
+
See xref:uninstall-self.adoc[Uninstall Runtime Fabric].