= Manage Proxies Used by Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic describes how to set or update proxy settings used by Runtime Fabric to connect outbound to the internet. This includes managing HTTP proxies for connecting out to Anypoint control plane, and SOCKS5 proxies for sending metrics and logs out to Anypoint Monitoring.

== Procedure For Updating the Monitoring Proxy

. Obtain the xref:https://runtime-fabric.s3.amazonaws.com/rtfctl/rtfctl-0.2.0[latest version] of `rtfctl` and transfer to a controller node under the `/usr/local/bin` folder with the name `rtfctl`. You may need root access to perform this operation.
. Make the script executable by running `chmod +x /usr/bin/rtfctl`.
. On the controller node, run `rtfctl -h` to verify the script works as expected by outputting instructions on how to use the utility.
. Run the following command, replacing the placeholder values with the following: `rtfctl apply monitoring_proxy "<user>:<pass>@<10.0.0.2>:<8080>"`
.. *<user>*: the username needed to authenticate to the SOCKS5 proxy.
.. *<pass>*: the password needed to authenticate to the SOCKS5 proxy.
.. *<10.0.0.2>: the IP address or hostname to access the SOCKS5 proxy.
.. *<8080>*: the port on the host where the SOCKS5 proxy is listening for requests.
. To verify the change was successful, run the following command to output the current value of the monitoring proxy: `rtfctl get monitoring_proxy`

The output should match the value expected.

== Procedure For Updating the HTTP Proxy

. Obtain the xref:https://runtime-fabric.s3.amazonaws.com/rtfctl/rtfctl-0.2.0[latest version] of `rtfctl` and transfer to a controller node under the `/usr/local/bin` folder with the name `rtfctl`. You may need root access to perform this operation.
. Make the script executable by running `chmod +x /usr/bin/rtfctl`.
. On the controller node, run `rtfctl -h` to verify the script works as expected by outputting instructions on how to use the utility.
. Run the following command, replacing the placeholder values with the following: `rtfctl apply http_proxy "<user>:<pass>@<10.0.0.1>:<8080>" --no-proxy "<1.1.1.1:8888,2.2.2.2.:9999>"`
.. *<user>*: the username needed to authenticate to the HTTP proxy.
.. *<pass>*: the password needed to authenticate to the HTTP proxy.
.. *<10.0.0.1>: the IP address or hostname to access the HTTP proxy.
.. *<8080>*: the port on the host where the HTTP proxy is listening for requests.
.. *<1.1.1.1:8888,2.2.2.2.:9999>*: the NO_PROXY hosts and ports, delimited by commas.
. To verify the change was successful, run the following command to output the current value of the HTTP proxy: `rtfctl get http_proxy`

The output should match the value expected.

== See Also

* xref:install-port-reqs.adoc[Network and Port Requirements for Anypoint Runtime Fabric]
