= Managing Mule Apps Deployed to Runtime Fabric

To manage Mule apps deployed to Anypoint Runtime Fabric, review the following topics:

* xref:manage-monitor-applications.adoc[Monitoring Mule Apps Deployed to Runtime Fabric] +
Use Anypoint Monitoring to view metrics and logs of Mule app deployed to Runtime Fabric. Additionally, you can export telemetry externally by using a Log4j appender to integrate your logging system to deployed Mule apps to Runtime Fabric.

* xref:install-rtfctl.adoc#manage-rtfctl-apps[Managing Mule Apps Deployed to Runtime Fabric Using RTFCTL] +
Use `rtfctl delete`, `describe`, `disk`, `memory`, `package`, `restart`, `heapdump`, `threaddump`` commands to manage Mule apps deployed to Runtime Fabric.

* xref:app-to-app-requests.adoc[Sending Application-to-Application Requests] +
Send a request from one Mule app to another app inside the cluster by using the Mule app name and environment ID.

* xref:app-versioning.adoc[Reviewing Mule App Versioning] +
Review deployed Mule app versioning to understand configuration changes history, roll back configurations, view Mule apps statuses and to make updates to a deployed Mule app's configuration.

* xref:manage-schedules.adoc[Managing Mule App Schedules] +
Use Runtime Manager to view and control the Scheduler components within the flows in your deployed Mule apps.

* xref:runtime-patch-updates.adoc[Managing Mule Runtime Patch Updates] +
Review the Mule runtime engine patch updates and the Mule release channels for Runtime Fabric.

== See Also

* xref:deploy-index.adoc[Deploying Mule Apps to Runtime Fabric]
* xref:hardening-apps-deployed-runtime-fabric.adoc[Hardening Mule Apps Deployed to Runtime Fabric]