= Monitoring Applications Deployed to Runtime Fabric

Applications and API gateways deployed to Runtime Fabric include native support for Anypoint Monitoring to allow viewing metrics within Anypoint Platform.

== Anypoint Monitoring

xref:monitoring::index.adoc[Anypoint Monitoring] includes tools that provide feedback from Mule runtime engine (Mule) flows and components in your application network. For applications and API gateways deployed to Anypoint Runtime Fabric (Runtime Fabric), Anypoint Monitoring provides basic metrics to all customers. Titanium-plan customers have access to additional capabilities, including application log retrieval and search.

=== Enable Anypoint Monitoring

By default, Runtime Fabric is configured to send application metrics to Anypoint Monitoring. Titanium-plan customers also have application logs automatically sent to Anypoint Monitoring by default. For metrics and logs to be sent to Anypoint Monitoring, outbound network connectivity must be available. 

If you need an outbound proxy, configure Runtime Fabric to use a SOCKS5 proxy by following the instructions in xref:manage-proxy.adoc[Manage Proxies Used by Runtime Fabric].

To verify outbound network connectivity, ensure that each node in Runtime Fabric can send outbound TCP (Lumberjack) communication using port 5044 to:

. US control plane: `dias-ingestor-nginx.prod.cloudhub.io`
. EU control plane: `dias-ingestor-nginx.prod-eu.msap.io`

=== Disable Anypoint Monitoring for an Application

When you deploy an application to Runtime Fabric, Anypoint Monitoring is enabled by default. To disable Anypoint 
Monitoring, pass the following custom property when deploying your application:

----
anypoint.platform.config.analytics.agent.enabled=false
----

[NOTE]
In some cases, logs with multiple lines might not be fully transmitted to Anypoint Monitoring. This can occur if 
multiple lines of log output are split across two files due to log rotation inside Runtime Fabric.

=== Metrics

Each Mule application and API gateway replica runs a metrics agent that collects and transmits metrics data to 
Anypoint Monitoring. Each replica can cache up to 100 megabytes of metrics, after which the metrics data is rotated 
to provide storage for more recent data. In the event that metrics cannot be sent to Anypoint Monitoring, this 
typically provides at least 4 days worth of storage per replica. Note that use of custom metrics might consume more storage.

=== Logs (Titanium)

Each Mule application and API gateway replica can store up to 450 megabytes of log data on disk, after which log data 
is rotated to provide storage for more recent log data.

Logs generated by each replica of a Mule application and API gateway are collected and written to disk on the worker 
node on which they are running. Each worker node runs a single log forwarding agent, which monitors this location 
and transmits the log data to Anypoint Monitoring.

[NOTE]
The log forwarding agent can transmit up to 300 kilobytes of log data per second. You should not deploy more than 
50 replicas per worker node.

== Anypoint Visualizer

xref:visualizer::index.adoc[Anypoint Visualizer] displays views of different aspects of an application network graph. 
You can use the graph to explore your application network, identify problems, and make decisions.

[WARNING]
====

* By default, Anypoint Visualizer is disabled when deploying an application to Mule runtime 4.x. 
See xref:visualizer::setup.adoc#enable-header-injection[Enable Header Injection] for more information.
* Due to the impact on performance, enabling Anypoint Visualizer for application deployments with less than 0.2 vCPU is 
not supported.
====
