= Monitoring Applications Deployed to Runtime Fabric

Applications and API gateways deployed to Runtime Fabric include native support for Anypoint Monitoring to allow viewing metrics within Anypoint Platform.

== Anypoint Monitoring

xref:monitoring::index.adoc[Anypoint Monitoring] provides tools that give feedback from Mule flows and components in your application network. For applications and API gateways deployed to Runtime Fabric, Anypoint Monitoring provides basic metrics to all customers. Titanium customers have access to additional capabilities including application log retrieval and search.

When you deploy an application to Runtime Fabric, Anypoint Monitoring is enabled by default. To disable Anypoint Monitoring, pass the following custom property when deploying your application:

----
anypoint.platform.config.analytics.agent.enabled=false
----

=== Metrics

Each Mule application and API gateway replica runs a metrics agent that collects and transmits the metrics data to Anypoint Monitoring. Each replica can cache up to 100 megabytes of metrics, after which the metrics will begin to rotate to provide storage for more recent data. In the event that metrics are unable to be sent to Anypoint Monitoring, this should generally provide at least 4 days worth of storage per replica. Note that use of custom metrics may consume more storage.

=== Logs (Titanium)

Each Mule application and API gateway replica can store up to 450 megabytes of log data on disk, after which log data is rotated to provide storage for more recent log data.

Logs generated by each replica of a Mule application and API gateway are collected and written to disk on the worker node where they are running on. Each worker node runs a single log forwarding agent, which monitors this location and transmits the log data to Anypoint Monitoring.

[NOTE]
The log forwarding agent can transmit up to 300 kilobytes of log data per second. You should not deploy more than 50 replicas per worker node.

== Anypoint Visualizer

xref:visualizer::index.adoc[Anypoint Visualizer] displays views of different aspects of an application network graph. You can use the graph to explore your application network, identify problems, and make decisions.

[WARNING]
By default, Anypoint Visualizer is disabled when deploying an application to Mule runtime 4.x. See xref:visualizer::setup.adoc#enable-header-injection[Enable Header Injection] for more information.

