= Managing Proxies on Runtime Fabric on Self-Managed Kubernetes

Runtime Fabric on Self-Managed Kubernetes uses two types of proxies when running and hosting applications:

* System proxies: include proxies that enable connectivity among Kubernetes cluster services, including the Docker daemon and other internal components. When using Runtime Fabric on Self-Managed Kubernetes you are responsible for configuring and managing system proxies.
* Application proxies: include proxies that enable connectivity to applications running on Runtime Fabric.

You can configure the proxy settings used by Runtime Fabric outbound connections to the internet. This includes both HTTP proxies for connecting to the Anypoint Platform control plane and SOCKS5 proxies for sending metrics and logs to Anypoint Monitoring. You can also configure proxies for applications.

* xref:configure-an-anypoint-monitoring-proxy[Configure an Anypoint Monitoring Proxy]
* xref:configure-an-http-proxy-for-services-in-runtime-fabric[Configure an HTTP Proxy for Services in Runtime Fabric]
* xref:configure-a-proxy-for-the-api-manager-agent[Configure a Proxy for the API Manager Agent]
* xref:configure-a-proxy-for-a-mule-application[Configure a Proxy for a Mule Application]


== Install rtfctl 

The `rtfctl` command line tool is required to manage proxy settings on Runtime Fabric. Follow the steps to xref:install-rtfctl.adoc[Install rtfctl] before configuring proxy settings.

[NOTE]
--
You can apply proxy settings during installation of Runtime Fabric on Self-Managed Kubernetes if you install using Helm. For more information, refer to the xref:install-helm.adoc[Installing Runtime Fabric on Self-Managed Kubernetes Using Helm documentation]. 
--

include::partial$include-manage-proxies.adoc[tags=monitoring-proxy]
include::partial$include-manage-proxies.adoc[tags=http-proxy]
include::partial$include-manage-proxies.adoc[tags=api-manager-proxy]
include::partial$include-manage-proxies.adoc[tags=mule-app-proxy]

== See Also

* xref:install-self-managed.adoc[Install Runtime Fabric on Self-Managed Kubernetes]