= Monitor Mule Core Usage With Runtime Fabric on Self-Managed Kubernetes

Anypoint Runtime Fabric on Self-Managed Kubernetes allows customers to use their own 
infrastructure monitoring solution to view metrics, monitor and alert on conditions.
This monitoring solution can be used to count and generate alerts on Mule core usage.

== Counting Mule Application Resources

The information below shows the steps you'll need to follow on your monitoring solution in
order to aggregate resource usage across all Mule application containers on Runtime Fabric
with Self-Managed Kubernetes. 

. Select all Pods containing a label equal to "MuleApplication"
. From each pod in the prior step, select the Container Name equal to "/app"
. Use your monitoring solution to aggregate and plot the CPU Usage and CPU Request across each selected container.

Refer to your monitoring solution's documentation to aggregate, plot and alert on the CPU usage across the Mule applications as required.

== See Also

* xref:index-self-managed.adoc[Runtime Fabric on Self-Managed Kubernetes]
* xref:install-self-managed.adoc[Install Runtime Fabric on Self-managed Kubernetes]
