= Persistence Gateway

To store state across applications, Anypoint Runtime Fabric provides the Persistence Gateway. Persistence Gateway enables Mule applications deployed to a Mule runtime engine (Mule) to store and share data across replicas and application restarts.

[NOTE]
====
Persistence Gateway is supported on Anypoint Runtime Fabric, version 1.9 or later and Mule runtime engine, version 4.2.1 or later.
====

== Use Persistence Gateway in a Mule Application

After Persistence Gateway is enabled, it is available when deploying to Mule runtime engine, version 4.2.1 or later. Mule applications use the Object Store REST API to connect to the Persistence Gateway. This enables you to deploy to both Anypoint Runtime Fabric and CloudHub without having to modify your Mule application. See xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric] for more information.

When an application using persistent object storage is deleted, Runtime Fabric deletes all information stored in the Persistence Gateway.

== Persistent Gateway Limits

The following table lists the limits on the data stored by the Persistence Gateway:

[%header,cols="3*a"]
|===
| Limit | Description | Default Value
| Maximum TTL. | The amount of time data is stored in the Persistence Gateway  | 30 days
| Maximum key length | | 256 characters
| Maximum value length | | 10 MB
| Maximum partitions per application | | 10
| Maximum keys per partition | | 1000
|===


[Configure-Persistence-Gateway]
== Configure Persistence Gateway

To enable Persistence Gateway, you must create a Kubernetes custom resource that allows the cluster to connect to your persistence data store.

=== Prerequisties

Before enabling Persistence Gateway, ensure that you have created a database to serve as the data source for data stored by the Persistence Gateway. This database must be compatible with PostgresSQL 9 and above. 

=== Create a Kubernetes Secret and Kubernetes Custom Resource

. Create a Kubernetes secret:
.. Copy the Kubernetes secret template from <<k8-secret-template>> to a file called `kubernetes-secret.yaml`.
.. Create a base64-encoded connection string. 
+
The standard URI for this string is `postgres://username:pass@host:port/databasename`. However, the requirements for your database may be different.
.. Copy the encoded string to the `persistence-gateway-creds:` field of `kubernetes-secret.yaml`. 
.. Run `kubectl apply -f kubernetes-secret.yaml`.

. Create a custom resource for your data store:
.. Copy the custom resource template from <<k8-custom-resource-template>> to a file called `custom-resource.yaml`.
.. Ensure the value of `secretRef: name` matches the `name` field defined in your Kubernetes secret file.
.. Modify other fields of the custome resource template as required for your environment.
.. Run `kubectl apply -f custom-resource.yaml`.

. Check the log of the Persistence Gateway pod to ensure it can communicate with the database:
+
----
kubectl logs -f persistence-gateway-6dfb98949c-7xns9 -nrtf
----
+
The output of this command should be similar to the following:
+
----
2021/04/09 16:35:31 Connecting to PostgreSQL backend...
2021/04/09 16:35:32 Starting watcher for /var/run/secrets/rtf-object-store/persistence-gateway-creds
2021/04/09 16:35:32 Watching for changes on /var/run/secrets/rtf-object-store/persistence-gateway-creds
2021/04/09 16:35:35 Succesfully connected to the PostgreSQL backend.
192.168.2.101 - - [09/Apr/2021:16:35:55 +0000] "GET /api/v1/status/ready HTTP/1.1" 200 2 "" "kube-probe/1.18+"
----

[[k8-secret-template]]
=== Kubernetes Secret Template

Use the example template below to create a Kubernetes secret. The Kubernetes cluster uses this secret to connect to your data store.

----
apiVersion: v1
data:
 persistence-gateway-creds: cG9zdGdyZXNxbDovL3Bvc3RncmVzOlRlc3RpbmdQb3N0Z3Jlc0BhdXRvbWF0aW9uLXRlc3RpbmctcnYuY2ZqcHFoeTZlYWhzLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL1JURg==
kind: Secret
metadata:
  name: persistence-gateway-creds
  namespace: rtf
type: Opaque
----

Below are descriptions of the fields of the template you should modify:

[%header,cols="2*a"]
|===
| Field | Description
| `metadata: persistence-gateway-creds` | The internal identifier for this secret. This name must match the value of the `secretRef:name` field of your Kubernetes resource.
| `metadata: namespace` | 
| `type` | Specifies the type of Kubernetes key. Only `Opaque` is supported.
|===


[[k8-custom-resource-template]]
=== Kubernetes Custom Resource Template

Use the example template below to create a Kubernetes custom resource. This custom resource enables the Kubernetes cluster to connect to your data store.

----
apiVersion: rtf.mulesoft.com/v1
kind: PersistenceGateway
metadata:
	name: persistent-gateway-config
	namespace: rtf
spec:
	objectStore:
    	backendDriver: postgresql
    	maxBackendConnectionPool: 10
		maxKeysPerStore: 5000
    	maxStores: 4
    	replicas: 1
		resources:
			limits:
				cpu: 1m
        		memory: 200Mi
			requests:
				cpu: 0.5m
				memory: 100Mi
		secretRef:
			name: persistence-gateway-creds
----

Below are descriptions of the fields of the template you modify:

[%header,cols="3*a"]
|===
| Field | Description | Default Value
| `backendDriver` | Specifies the driver used by the data store. Only `postgresql` is supported. | `postgresql`
| `maxBackendConnectionPool` | | 10
| `maxKeysPerStore` | | 5000
| `maxStores` | | 5000
| `replicas` | | 5000
| `resources: limits: cpu` | | 1m
| `resources: limits: memory` | | 200Mi
| `resources: requests: cpu` |  | 0.5m
| `resources: requests: memory` | | 100Mi
| `secretRef: name:` | Specifies the name of the persistence gateway credentials defined in the Kubernetes secret file.| `persistence-gateway-creds`
|===

== See Also

* xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric]