= Deploying API Proxies to Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Runtime Fabric enables you to deploy API proxies to a Mule runtime.

== Before you Begin

To deploy API proxies to a Mule runtime, you must have the following permissions on your account:

* Manage APIs Configuration permission
* Deploy API Proxies permission

You must ensure that you are using API Gateway version 3.8.7, 3.9.1, or 4.1.2.

If you are deploying your API to a Mule 4 environment and want to enable the proxy to support HTTPS requests, first refer to xref:api-manager::building-https-proxy.adoc[build HTTPS API proxies].

By default, the resources allocated to the proxy app are:

* CPU: 0.2 vCores
* Memory: 1.024 GB

You can update resource allocation settings on the application's *Settings* page in Runtime Manager.

== Deploy an API Proxy

Use API Manager to deploy proxies to Runtime Fabric. You can enable proxies to support inbound and outbound requests over HTTP or HTTPS. 

If you need your proxy to support HTTPS, see xref:api-manager::building-https-proxy.adoc[Build HTTPS API Proxies] in the API Manager documentation for additional requirements before getting started.

. From Anypoint Platform, select *API Manager* > *Manage API* > *Manage API From Exchange*.
. In *API Name*, search for the name of the asset saved in Exchange.
+
The *Asset type*, *API version*, and *Asset version* fields for the API are auto-populated from Exchange.
. For *Managing type*, select *Endpoint with proxy*.
. For *Proxy deployment target*, select Runtime Fabric.
. Select the Mule version.
. For *Implementation URI*, specify the base URL path to access the proxy.
. Optionally, specify a *Path*.
. If you want to enable SSL for inbound traffic:
.. Select **HTTPS** for the **Scheme**. 
+
You should now see the **TLS Context for Inbound Traffic** field enabled.
.. Select **Add TLS Context**.
.. Select the secret group where you hosted your TLS context from the **Secret group** drop-down.
.. Select your TLS context for your HTTPS API Proxy from the **TLS Context** drop-down.
. Enter the *Port* number for your API proxy.
. Select your *Client Provider*.
. Click *Advanced Options*.
. In *Proxy Version*, select *latest*. 
+
This value ensures that your API proxy uses the latest released proxy version.
. Click *Add TLS Context* for *TLS Context for Outbound traffic*.
.. Select the secret group where you hosted your TLS Context from the *Secret Group* drop-down list.
.. Select your TLS Context for your HTTPS API Proxy from the *TLS Context* drop-down.
. Click *Save*.
+
Your configuration information is saved and API Manager displays the *Deployment Configuration* section.
. In the *Deployment Configuration* section, configure the following:
+
.. Select the *Runtime Fabric target*.
.. Select the *Runtime version*.
.. Enter the name of the proxy application.

API Manager deploys the API proxy to Runtime Fabric. While deploying, a deployment status dialog appears that indicates:

. *Deploying proxy*.
. *Starting application*. 
. *Deploy successful*. 

After deployment, you can manage the deployed API proxy from Runtime Manager.

== Enable an HTTPS Proxy Using Anypoint Studio

You can enable the proxy to support HTTPs requests using Anypoint Studio.

. Download the API gateway and deploy from API Manager using the instructions in xref:api-manager::download-proxy-task.adoc[Downloading an API Proxy].
. Open the gateway in Anypoint Studio and insert a keystore (SSL cert) using the instructions in xref:mule-runtime::tls-configuration#use-anypoint-studio-to-configure-tls[Use Anypoint Studio to Configure TLS].
. Export and deploy the gateway using Runtime Manager according to the instructions in xref:runtime-fabric::deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric].
. Enable last-mile security on the application using the instructions in https://help.mulesoft.com/s/article/How-to-enable-last-mile-security-in-Runtime-Fabric-RTF[How to enable last-mile security in Runtime Fabric (RTF)].

== Related Resources

* xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric]
