= Deploy API Proxies to Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

// tag::content[]
Runtime Fabric enables you to deploy API proxies to a Mule runtime.

== Before you Begin

To deploy API proxies to a Mule runtime, you must have the following permissions on your account:

* Manage APIs Configuration permission
* Deploy API Proxies permission

You must ensure that you are using API Gateway version 3.8.7, 3.9.1, or 4.1.2.

If you are deploying your API to a Mule 4 environment and want to enable the proxy to support HTTPS requests, first refer to xref::apimanager:building-https-proxy.adoc[build HTTPS API proxies].

By default, the resources allocated to the proxy app are:

* CPU: 0.2 vCores
* Memory: 1.024 GB

You can update resource allocation settings on the application's *Settings* page in Runtime Manager.

== Deploy an API Proxy

. From Anypoint Platform, select *API Manager* > *Manage API* > *Manage API From Exchange*.
. In *API Name*, search for the name of the asset as saved in Exchange.
+
The *Asset type*, *API version*, and *Asset version* fields for the API are auto-populated from Exchange.
. For *Managing type*, select *Endpoint with proxy*.
. For *Proxy deployment target*, select Runtime Fabric.
. Select the Mule version.
. For *Implementation URI*, specify the base URL path to access the proxy.
. If using HTTPS, make a selection for *TLS context for outbound traffic*.
. If using OAuth 2.0, select a client provider.
. Optionally, specify a *Path*, *Service Name*, *Service Port*, and *Service Namespace*.
. Click *Advanced options* and optionally specify advanced parameters, such as *TLS context for outbound traffic* (for HTTPS), *Proxy version*, *Validations*, *Response timeout*, and *Port*.
. Click *Save*.
+
Your configuration information is saved and API Manager displays the *Deployment Configuration* section.
. In the *Deployment Configuration* section, configure the following:
+
* Select the *Runtime Fabric target*.
* Select the *Runtime version*.
* Enter the name of the proxy application.

API Manager deploys the API proxy to Runtime Fabric. While deploying, a deployment status dialog appears that indicates:

. *Deploying proxy*.
. *Starting application*. 
. *Deploy successful*. 

After deployment, you can manage the deployed API proxy from Runtime Manager.

== Enable an HTTPS Proxy
To enable the proxy to support HTTPs requests:

. Download the API gateway and deploy from API Manager using the instructions in xref:api-manager::download-proxy-task.adoc[Downloading an API Proxy].
. Open the gateway in Anypoint Studio and insert a keystore (SSL cert) using the instructions in xref:mule-runtime::tls-configuration#use-anypoint-studio-to-configure-tls[Use Anypoint Studio to Configure TLS].
. Export and deploy the gateway using Runtime Manager according to the instructions in xref:runtime-fabric::deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric].
. Enable last-mile security on the application using the instructions in https://help.mulesoft.com/s/article/How-to-enable-last-mile-security-in-Runtime-Fabric-RTF[How to enable last-mile security in Runtime Fabric (RTF)].

== Related Resources

* xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric]
