= Deploying API Proxies to Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Runtime Fabric enables you to deploy API proxies to a Mule runtime.

== Before you Begin

To deploy API proxies to a Mule runtime, you must have the following permissions on your account:

* Manage APIs Configuration permission
* Deploy API Proxies permission

You must ensure that you are using API Gateway version 3.8.7, 3.9.1, or 4.1.2.

If you are deploying your API to a Mule 4 environment and want to enable the proxy to support HTTPS requests, first refer to xref:api-manager::building-https-proxy.adoc[build HTTPS API proxies].

By default, the resources allocated to the proxy app are:

* CPU: 0.2 vCores
* Memory: 1.024 GB

You can update resource allocation settings on the application's *Settings* page in Runtime Manager.

== Deploy an API Proxy

. From Anypoint Platform, select *API Manager* > *Manage API* > *Manage API From Exchange*.
. In *API Name*, search for the name of the asset saved in Exchange.
+
The *Asset type*, *API version*, and *Asset version* fields for the API are auto-populated from Exchange.
. For *Managing type*, select *Endpoint with proxy*.
. For *Proxy deployment target*, select Runtime Fabric.
. Select the Mule version.
. For *Implementation URI*, specify the base URL path to access the proxy.
. Optionally, specify a *Path*.
. Click *Advanced options* and optionally specify advanced parameters, such as *TLS context for outbound traffic* (for HTTPS), *Proxy version*, *Validations*, *Response timeout*, and *Port*.
. Click *Save*.
+
Your configuration information is saved and API Manager displays the *Deployment Configuration* section.
. In the *Deployment Configuration* section, configure the following:
+
* Select the *Runtime Fabric target*.
* Select the *Runtime version*.
* Enter the name of the proxy application.

API Manager deploys the API proxy to Runtime Fabric. While deploying, a deployment status dialog appears that indicates:

. *Deploying proxy*.
. *Starting application*. 
. *Deploy successful*. 

After deployment, you can manage the deployed API proxy from Runtime Manager.

== Enable and Deploy an HTTPS Proxy

You can enable proxies deployed to Runtime Fabric to support inbound and outbound HTTPs requests. To do so, use API Manager to:

. Select the proxy type
. Select the Runtime Fabric deployment target
. Select an API
. Use the advanced configure options to add the TLS Context for inbound and outbound HTTPs requests
. Deploy the proxy to Runtime Fabric

See xref:api-manager::building-https-proxy.adoc[Build HTTPS API Proxies] in the API Manager documentation for additional requirements.

== Related Resources

* xref:deploy-to-runtime-fabric.adoc[Deploy a Mule Application to Runtime Fabric]
