= Replacing Mule License Keys
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

When your Mule license expires, you must replace your Mule license key. Also use this procedure if you 
entered an incorrect license key during installation.

Perform the following steps on the controller node used to start the installation. For Azure and AWS installations, 
this node is named `rtf-controller-1` by default.

== Install rtfctl 

The `rtfctl` utility is required to replace your Mule license key on Runtime Fabric. Follow the steps in xref:install-rtfctl.adoc[Install rtfctl] before continuing.

For Runtime Fabric on VMs / Bare Metal, the `rtfctl` binary is in directory `/opt/anypoint/runtimefabric/`. Confirm that the current working directory is also `/opt/anypoint/runtimefabric/`.

For Runtime Fabric on Self-Managed Kubernetes, confirm that the `rtfctl` binary is present in the current working directory and in the user `$PATH`.   

Run `rtfctl` commands as a privileged user.

== Procedure

. Base64 encode the new Mule `.lic` license file provided by MuleSoft: 

** On MacOS, run the following command in the terminal: 
+
----
BASE64_ENCODED_LICENSE=$(base64 -b0 license.lic)
----
** On Unix, run the following command:
+
----
BASE64_ENCODED_LICENSE=$(base64 -w0 license.lic)
----
** On Windows, choose one of the following: 
*** Use a WSL or Cygwin shell that includes the base64, tool and use the above Unix command. 
*** Use the `base64.exe` program included with Windows git (`C:\Program Files\Git\usr\bin`).
*** Use the following Powershell command:
+
----
$BASE64_ENCODED_LICENSE=[convert]::ToBase64String((Get-Content -path "license.lic" -Encoding byte))
----

. On the controller node acting as the leader during installation (the installer node), use the `rtfctl` utility with the
Base64 value of your license key. For more information on the `rtfctl` command, refer to 
xref:runtime-fabric::install-rtfctl#list-supported-commands[rtfctl commands].
+
----
rtfctl apply mule-license $BASE64_ENCODED_LICENSE
----
+
. To verify the Mule license key has applied correctly, retrieve the contents using the `rtfctl` utility:
+
----
rtfctl get mule-license
----


== See Also

* xref:runtime-fabric::install-rtfctl.adoc[Install rtfctl]
