= Replace a Mule License Key
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

When your Mule license expires, you must replace your Mule license key. Also use this procedure if you 
entered an incorrect license key during installation.

Perform the following steps on the controller node used to start the installation. For Azure and AWS installations, 
this node is named `rtf-controller-1` by default.

. Base64 encode the new Mule `.lic` license file provided by MuleSoft: 

** On MacOS, run the following command in the terminal: 
+
----
base64 -b0 license.lic
----
** On Unix, run the following command:
+
----
base64 -w0 license.lic
----
** On Windows, a shell terminal emulator (such as cygwin) or access to a Unix-based 
computer is required.

... Transfer to your Unix environment if necessary.
... Run the following command to Base64 encode the license key:
+
----
base64 -w0 license.lic
----

. On the controller node acting as the leader during installation (the installer node), use the `rtfctl` utility with the
Base64 value of your license key. For more information on the `rtfctl` command, refer to 
xref:runtime-fabric::install-rtfctl#supported-commands[rtfctl Supported commands].
+
----
rtfctl apply mule-license BASE64_ENCODED_LICENSE
----
+
. To verify the Mule license key has applied correctly, retrieve the contents using the `rtfctl` utility:
+
----
rtfctl get mule-license
----


== See Also

* xref:runtime-fabric::install-rtfctl.adoc[Install rtfctl Utility]
