= View Runtime Fabric Status
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can use Anypoint Runtime Manager to view the health of your Anypoint Runtime Fabric clusters. 

. Navigate to Runtime Manager and select *Runtime Fabric*.
. Click in the area between a Runtime Fabric cluster name and its status to display resource and status information for that Runtime Fabric cluster.
. Click the *Manage* button to open the management page.
+
Information that is displayed includes version; number of controller, worker, and ingress (internal load balancer) nodes; and the total amount of vCPU that is available for the Runtime Fabric cluster to use.

== Health Details
For Runtime Fabric version 1.5 or later:

. Navigate to Runtime Manager and select *Runtime Fabric*.
. Select the name of your Runtime Fabric cluster to open the management page.
. Select *Health Details*.
+
The *Health Details* section indicates whether your Runtime Fabric cluster configuration meets the requirements for a production environment, a development environment, or neither. If your configuration fails to meet the minimum requirements of both production and development environments, `Not supported` is displayed. 

== See Also
You can view additional performance and Runtime Fabric cluster health information using the Ops Center. Refer to xref:using-opscenter[Use Ops Center to Monitor Runtime Fabric].
