= Runtime Fabric Runtime Patch Updates 

The following provides important information about Mule runtime engine patch updates for Runtime Fabric.

== Monthly Date-Patch Updates 

Once per month, MuleSoft releases a _date-patch update_,  which includes backward-compatible bug fixes to address any issues discovered in Mule runtime engine.
The monthly date-patch update might include security patches if the scheduled date is within the security SLA.

The format of the version number for these updates is:

_Major_._Minor_._Patch_ - _Date_ 

Here's an example version number, including the patch date:

`4.3.0:20210101`

The monthly patches update applications only to the latest date patch for the patch version.
They do not change the patch version number.

== Runtime Fabric Runtime Patch Update Schedule 

Runtime Fabric runs each application and gateway deployment on a separate Mule runtime instance. By managing the containerized Mule images used for these deployments, Runtime Fabric enables you to upgrade your Mule runtime version for each deployment on the following schedule:

. On the first full week of the month, you have access to new versions of updated Mule runtimes.
. During the next two weeks, you can redeploy your applications using the newer runtime versions to validate its behavior. This is known as a grace period.
. Beginning on the third full full week of the month, you must select the latest date patch version of your chosen Mule runtime version when deploying a new application, or when making a change to an existing application.

[NOTE]
If needed, you can redeploy an application using an older runtime version. However, if you make any subsequent changes to that application, you must update its runtime version. 

== Update a Single App to the Latest Runtime Patch Release

Before updating apps in the production environment, update them in the sandbox environment and run required tests. 

To update an app to the latest date patch:

. In the Runtime Manager left menu, click *Applications*.
. Click the *Update Available* tab.
. Click in the *Status* column for the app to display the details pane on the right.
. Click the *Manage Application* button to display the *Settings* page for the app.
+
If the app requires an update, *Update available* appears in the *Runtime version* menu:
+
[add RTF screenshot]
. Select the latest version from the *Runtime version* menu.
+
Although the version number of the update might be the same as the installed version, a later date identifies the update:
+
[add RTF screenshot]
. If you want to see details about the version, click the *Read release notes* link.
. Click the *Apply Changes* button to update the app. 
+
Runtime Fabric updates the app with the version you selected and displays a message indicating success or failure.
+
If the app update was successful, the app no longer appears in the *Update Available* tab on the *Applications* page.
. Re-deploy your application.
+
Mule deployments on Runtime Fabric are not automatically patched. You must re-deploy your applications to apply the latest date-patch updates.

== See Also
Link to Best Practices with Mule Patching
Runtime Fabric Runtimes Release Notes
