= Limitations
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following information is important when installing, configuring, 
and managing Runtime Fabric.

Controller Nodes::
The maximum number of controller nodes supported is 5.

Worker Nodes::
The maximum number of worker nodes supported is 16.

Replicas Per Worker Node::
The maximum number of replicas that can be deployed per worker node is 40.
+
Run no more than 20 - 25 replicas per core, up to a maximum of 40 replicas per node, to allow core sharing across replicas when needed for bursting. This ensures the Runtime Fabric’s internal components that run on each worker node are not overloaded by too many replicas.

Associated Environments per Runtime Fabric::
The maximum number of environments per Runtime Fabric is 50. 

Business Groups::
The maximum number of Runtime Fabrics you can create in a business group is 50.

Internal Load Balancer::
The following table lists the approximate number of requests (averaging 10 KB) that can be served with a single replica of the internal load balancer based on the number of CPU cores. This information is based on the performance test results as described in xref:deploy-resource-allocation#internal-load-balancer[Resource Allocation and Performance on Anypoint Runtime Fabric].

[%header,cols="3*a"]
|===
| vCPU Cores | Max Requests per Second (Connection Reuse) | Max Requests per Second (No Connection Reuse)
| `1.00` | 2000 | 175
| `0.75` | 1500 | 100
| `0.50` | 1000 | 50
| `0.25` | 100 | 10
|===

[NOTE]
The internal load balancer runs on the controller VMs of Runtime Fabric. Configure the VM size based on the amount and 
type of inbound traffic. You can allocate only half of the available CPU cores on each VM to the internal load balancer.
Refer to xref:deploy-resource-allocation#internal-load-balancer[Resource Allocation and Performance on Anypoint Runtime Fabric] for additional information.
