= Configuring Shared Tenancy in Runtime Fabric

Shared tenancy enables you to deploy Runtime Fabric alongside other services in a Kubernetes cluster. By limiting permissions in your Runtime Fabric cluster, you can allow access only to resources within namespaces assigned to Runtime Fabric. 

With shared tenancy, you have control of the creation of the following Runtime Fabric resources:

* Namespaces
* RoleBindings
* ServiceAccounts

== How Shared Tenancy Works

At install time, you provide a configuration file that consists of your namespaces, ServiceAccounts, ClusterRoles/Roles, and RoleBindings.

Runtime Fabric installs the rtf-agent in the Runtime Fabric namespace, and it has access to any additional namespaces you create.

=== Example

The following is an example of a rtf:agent ClusterRole that allows everything regarding cronjobs. available in the whole cluster, but doesn’t itself grant permissions for the whole cluster. It’s available in the whole cluster, but doesn’t itself grant permissions for the whole cluster.

[source,yaml]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: rtf:agent
rules:
- apiGroups:
 - batch
 resources:
 - cronjobs
 verbs:
 - create
 - delete
 - deletecollection
 - get
 - list
 - patch
 - update
 - watch
----
   
Runtime Fabric will then create required RoleBinding objects which will use the ClusterRole rtf:agent to allow corresponding ServiceAccount to perform various actions (verbs) on cronjobs in two namespaces.

[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rtf:agent-1
  namespace: namespace1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rtf:agent
subjects:
- kind: ServiceAccount
  name: rtf-agent-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rtf:agent-2
  namespace: namespace2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rtf:agent
subjects:
- kind: ServiceAccount
  name: rtf-agent-sa
  namespace: default
----
 
== Configure Shared Tenancy 

. Create the Kubernetes objects required to install the Runtime Fabric agent:
+
* Namespaces
* ClusterRoles/Roles
* RoleBindings
* ServiceAccounts
. Run some commands
. Complete the RTF installation by following the steps in https://docs.mulesoft.com/runtime-fabric/1.13/install-self-managed
Or
https://docs.mulesoft.com/runtime-fabric/1.13/install-helm
Or 
Link to openshift install docs
