= Troubleshooting Guide for Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic describes common errors and steps to resolve them when installing Anypoint Runtime
Fabric.

== Obtain a Full Network Assessment
Run the following command for an overall health assessment of the network:
```
/opt/anypoint/runtimefabric/rtfctl status
```

== Troubleshoot Network Connectivity Using rtfctl

Every Anypoint Runtime Fabric cluster requires connectivity with Anypoint control plane, and any interference with connectivity can limit functionality, resulting in application deployment failures or degraded status in Anypoint Runtime Manager.

You can use `rtfctl` to verify that Runtime Fabric has the required outbound connectivity as well as troubleshoot connectivity issues. 

=== Verify Outbound Connectivity

On each node, follow the instructions in xref:install-rtfctl.adoc[Install rtfctl] to install `rtfctl`. 
Run the following command in all controller and worker nodes on the cluster to verify the required outbound connectivity:
```
sudo ./rtfctl test outbound-network
```

Sample output:
```
[root@rtf-controller-1 runtimefabric]# sudo ./rtfctl test outbound-network
Using proxy configuration from Runtime Fabric (proxy "", no proxy "")

Using 'US' region
transport-layer.prod.cloudhub.io:443 ✔
https://anypoint.mulesoft.com ✔
https://worker-cloud-helm-prod.s3.amazonaws.com ✔
https://exchange2-asset-manager-kprod.s3.amazonaws.com ✔
https://ecr.us-east-1.amazonaws.com ✔
https://494141260463.dkr.ecr.us-east-1.amazonaws.com ✔
https://prod-us-east-1-starport-layer-bucket.s3.amazonaws.com ✔
https://runtime-fabric.s3.amazonaws.com ✔
tcp://dias-ingestor-nginx.prod.cloudhub.io:5044 ✔
```
 
If you have outbound connectivity issues that prevent Runtime Fabric from reaching any of the required Anypoint control plane services, work with your network team to verify that you have completed the required whitelisting as described in xref:install-port-reqs#port-ips-and-hostnames-to-whitelist[Port IPs and Hostnames to Whitelist].

== Troubleshoot Cluster Issues

When filing a support case, the support team might ask you to run one or both of the following commands to generate debugging information:

* The `rtfctl report` command to generate an archive containing only Kubernetes objects and logs.
* The `rtfctl appliance report` command to collect diagnostics from all cluster nodes.

The support team might also ask you to download information through Ops Center as described in xref:using-opscenter#download-debug-info[Download Debug Info].

== Troubleshoot Application Deployment Issues

In rare situations, the Anypoint Monitoring agent might prevent an application from deploying. In
these situations, you might see the following messages:

* The application remains in the `Deploying` state, or
* `Error starting monitoring agent (code -1)`

In this situation, redeploy your application and set the following custom property:
----
anypoint.platform.config.analytics.agent.enabled=false
----

The Anypoint Monitoring agent might also change the state of a deployed application. If you see
one of the following:

* The application transitions from `Running` to `Applying`, or
* `Monitoring agent has exited with code -1`

This indicates that the agent is restarting. There should be no impact to the running
application. Application metrics are queued, and are again collected after the agent
restarts.

== Troubleshoot Application Runtime Issues
If any of the following Runtime Fabric alert messages are reported, you might need to recover
one or more controller nodes. 
----
Management plane is unreachable

InfluxDB is down or no connection between Kapacitor and InfluxDB

Node is down

CRITICAL / Kubernetes node is not ready: <ip_address>

CRITICAL / etcd: cluster is unhealthy
----
Open a terminal and run the `gravity status` command to obtain the health status of the cluster
as well as individual components. 

To recover a node, follow the instructions provided in xref:manage-nodes.adoc[Add or Remove a Node from a Runtime Fabric].

== Troubleshoot DNS Resolution Issues
If you experience a DNS resolution issue, it might be caused by an older version of gravity, as shown in the following example error message:

```
kubectl logs tokenpolicyapigw-4-2-2-78497485fb-nn2x7  -n a3ea3617-3c3f-47cf-965f-d7a152c31ffb -f
Error from server (BadRequest): a container name must be specified for pod tokenpolicyapigw-4-2-2-78497485fb-nn2x7, choose one of: [app anypoint-monitoring] or one of the init containers: [init]
[root@ip-10-0-110-31 ~]# kubectl logs tokenpolicyapigw-4-2-2-78497485fb-nn2x7  init -n a3ea3617-3c3f-47cf-965f-d7a152c31ffb -f
time="2020-02-25T17:42:15Z" level=info msg="Reading annotations..."
time="2020-02-25T17:42:15Z" level=info msg="Parsing resources annotation..."
time="2020-02-25T17:42:15Z" level=info msg="Application resources:"
time="2020-02-25T17:42:15Z" level=info msg="  1. /opt/mule/apps/tokenpolicyapigw-4-2-2.jar (https://configuration-resolver.qax.msap.io/api/v1/deployments/add0b4d9-54f8-11ea-8202-85e61abacb9f/assets/eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJncm91cElkIjoiMDhlMTBmNjQtMDc3My00NWExLWE0MTItY2M3MjMyMDMzOWQzIiwiaXNzIjoiTXVsZVNvZnQgLSBBTUMgLSBEZXBsb3llciIsImNsYXNzaWZpZXIiOiJtdWxlLWFwcGxpY2F0aW9uIiwiYXJ0aWZhY3RJZCI6ImFwaWd3cHJveHktYXBpLWdhdGV3YXktc2FtcGxlLXJlc3QtcHJveHkiLCJwYWNrYWdpbmciOiJqYXIiLCJleGNoYW5nZVR5cGUiOiJhcHAiLCJkZXBsb3ltZW50TmFtZSI6InRva2VucG9saWN5YXBpZ3ctNC0yLTIiLCJyZWZJZCI6InRva2VucG9saWN5YXBpZ3ctNC0yLTIiLCJzb3VyY2UiOiJleGNoYW5nZSIsInZlcnNpb24iOiIxLjAuMS0yLjEuMCJ9.FymfZOCU0QVI7UusVDQuzSh7TAbXFxFeK2N0Tm6rvlK_qZCykiG7j5fofVCxuAgLWFme1oQnxhpJFsrl7HR-R3d1huVI8zEUvlPa5qEPENNAPlV0_sE6UQuoKwK8rTEMkLQTjXxMg_ktkpk8neTRxyZ17d397Uz2O88oyI6G5v2IhjaVFQEbsoHMyHz5SnzkHecxhVZWoQwmAk6N4IYd6wHKPGYFG-2JvvnDBK98Ms7uPLAOlkIEu8hjQFDTYMO6D6k8UAIAcMdlHyYPZZSG6lO1LEOyLyCNr6-RLNJibwPnbrwUvGb2X8ulFaeCASTH1GL3FE-HB3SxJk7p8r0m0A)"
time="2020-02-25T17:42:15Z" level=info msg="  2. /opt/mule/conf/tokenpolicyapigw-4-2-2.yml (https://configuration-resolver.qax.msap.io/api/v1/deployments/add0b4d9-54f8-11ea-8202-85e61abacb9f/configurations/eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJNdWxlU29mdCAtIEFNQyAtIERlcGxveWVyIiwiZGVwbG95bWVudE5hbWUiOiJ0b2tlbnBvbGljeWFwaWd3LTQtMi0yIiwic291cmNlIjoiZGVwbG95ZXIiLCJ0eXBlIjoiY29uZmlndXJhdGlvbiIsInZlcnNpb24iOiJhZGQwYjRkYi01NGY4LTExZWEtODIwMi00YjA4MWU3NDBmNDQifQ.K5QHijc0oT71-eU5l4wfSnlUXAo4UrhLdVpA10eOvZ7yqVHt46wMtfOPZB5RQw33PhtQMcoK-bYkyZD3xrPv2RverRm502WR2xwZpmq7-aVxA4oNy1qD7o4WCfsNYjGekGgeS-xutW4yb20L3xCu5Lf-PnEGoEcsKvi_Vz0vUfnUrt2VQkcW-Wg175DehJgzYVvHpQcaOzBQqrI2Civ2cCVKy7RqIDuM-27Kqrd5WTD8qthHAo7op0Z0lID2g6uUul5usVCFyiVwUQW1gOr74uqb2j8ExxOjRnf55giJ9WJNJ9JWg6JPmkS5VJcMK3AhKRSBofyDTIlwiWeoGga1pw)"
time="2020-02-25T17:42:15Z" level=info msg="Fetching from cache..." res=/opt/mule/conf/tokenpolicyapigw-4-2-2.yml
time="2020-02-25T17:42:15Z" level=info msg="Fetching from cache..." res=/opt/mule/apps/tokenpolicyapigw-4-2-2.jar
time="2020-02-25T17:42:25Z" level=warning msg="/opt/mule/conf/tokenpolicyapigw-4-2-2.yml: dial tcp: i/o timeout, retrying in 1s"
time="2020-02-25T17:42:25Z" level=warning msg="/opt/mule/apps/tokenpolicyapigw-4-2-2.jar: dial tcp: i/o timeout, retrying in 1s"
time="2020-02-25T17:42:36Z" level=warning msg="/opt/mule/apps/tokenpolicyapigw-4-2-2.jar: dial tcp 10.100.167.56:80: i/o timeout, retrying in 1.664560053s"
time="2020-02-25T17:42:36Z" level=warning msg="/opt/mule/conf/tokenpolicyapigw-4-2-2.yml: dial tcp 10.100.167.56:80: i/o timeout, retrying in 1.437714187s"
time="2020-02-25T17:42:48Z" level=warning msg="/opt/mule/conf/tokenpolicyapigw-4-2-2.yml: dial tcp: i/o timeout, retrying in 2.273912491s"
time="2020-02-25T17:42:48Z" level=warning msg="/opt/mule/apps/tokenpolicyapigw-4-2-2.jar: dial tcp: i/o timeout, retrying in 3.060469218s"
time="2020-02-25T17:43:00Z" level=warning msg="/opt/mule/conf/tokenpolicyapigw-4-2-2.yml: dial tcp 10.100.167.56:80: i/o timeout, retrying in 1.459459134s"
time="2020-02-25T17:43:01Z" level=warning msg="/opt/mule/apps/tokenpolicyapigw-4-2-2.jar: dial tcp 10.100.167.56:80: i/o timeout, retrying in 2.095634783s"
```

In this case, upgrading your installer version and redeploying your applications resolves the problem. Refer to xref:upgrade-index.adoc[Upgrade Runtime Fabric] for additional information.

== Troubleshoot Environment Variable Issues

This step detects the variables which the installation process needs to carry out its
procedures. The methods for providing these variables to the installation vary based upon where
the installation is running.

* For AWS, the variables are set in the terraform script, and outputted to a file located in
`/opt/anypoint/runtimefabric/env`.
* For Azure, the variaables are set when running the ARM template, and are retrieved as tags on
the Virtual Machine instances.
* For manual installations, the user creates a file with the values located in
`/opt/anypoint/runtimefabric/env`.

After these properites are retrieved, a procedure will run to connect to Anypoint Platform and
retrieve additional values based upon the `RTF_ACTIVATION_DATA` value.

=== Common errors

The following error may occur if there is an issue with the activation data value, or if there
is trouble reaching the internet on the instance:

----
curl: (7) Failed connect to anypoint.mulesoft.com:443; Operation now in progress
Error: Failed to fetch registration properties. (000). Please check your token is valid


============ Error ============
Exit code: 1
Line:
----

If this error is observed, try the following:

* Ensure your instance has outbound internet connectivity. A simple way to validate is to run
the following command and verify a 301 response is returned:
+
----
curl https://anypoint.mulesoft.com
----
+
* Re-try running the installation procedure, in case the network connectivity was not finished
initalizing.
** On Azure, the script should be located at `/opt/anypoint/runtimefabric/script.sh foreground`
** On AWS and manual installatons, the script should be located at
`/opt/anypoint/runtimefabric/init.sh foreground`
* Validate the activation data value is correct by comparing with the Runtime Fabric created in
Anypoint Runtime Manager.

If you are still encountering issues, file a support ticket for further assistance.

== Resume a Failed Installation

You can resume an installation at the point where it failed by running the init script:

* AWS and manual installations:

+
----
/opt/anypoint/runtimefabric/init.sh
----

* Azure installations:
+
----
/opt/anypoint/runtimefabric/script.sh
----

== Troubleshoot Install Package Issues

This step will install required packages on the instance. It uses the `yum` package repository
to download and install the required packages.

=== Common errors

If there is a failure on this step, verify the following:

* Ensure your instance has outbound internet connectivity. A simple way to validate is to run
the following command and verify a 301 response is returned:
+
----
curl https://anypoint.mulesoft.com
----
+
* If running a manual installation, ensure the `init.sh` script is run with root privledges:
+
----
sudo ./init.sh foreground
----
+
* Manually install one of the required packages to determine if it is successful outside of the
installation script:
+
----
sudo yum install -y chrony
----
+
** If not successful, work with your operations team for assistance. You may need to ask
for elevated access to the instance.

If manual installation of a package was successful, or if you still require assistance, 
file a support ticket.

== Troubleshoot Ops Center Monitoring and Logs Issues

If Ops Center monitoring and logging fails to restart after restarting one or more nodes, ensure port forwarding rules are applied on all VMs so that traffic can communicate with the Kubernetes pods running on the VMs. Refer to xref:prereq-firewalld-forwarding.adoc[Enable Forwarding When Using firewalld] for additional information.

== Format and Mount Disks

This step performs the following tasks on the block devices or disks provided with the
`RTF_DOCKER_DEVICE` and/or `RTF_ETCD_DEVICE` variables:

. Performs a check to confirm the values map to block devices available on the instance.
. Unmounts the disks in case they were previously mounted.
. Formats the disks.
. Adds an mount entry in the `/etc/fstab` file.
. Creates directories based upon the values in `$DOCKER_MOUNT` and/or `$ETCD_MOUNT`.
. Mounts the disks to the expected directories created above.

=== Install RTF Components

This step connects to Anypoint Platform to download and install the Runtime Fabric components
on the cluster.

In some cases, this step may return an error if the deployment failed to complete within the
time limit:

----
...
[OK]
Installing Runtime Fabric Agent. This may take several minutes...
configmap "grafana-dashboards" deleted
configmap "kapacitor-alerts" deleted
Release "runtime-fabric" does not exist. Installing it now.
The following deployments failed to become ready within the time limit:
monitor ---
Name:           monitor-79c7564b77-wb9c6
Namespace:      rtf
Node:           10.165.12.87/10.165.12.87
Start Time:     Thu, 13 Dec 2018 20:23:59 +0000
Labels:         app=monitor
                pod-template-hash=3573120633
Annotations:    checksum/config=4c4aac48d9cc8b24828b38ba0eb587840bc17b2449a54d593f74e2d58e5c12ae
                kubernetes.io/psp=privileged
                seccomp.security.alpha.kubernetes.io/pod=docker/default
Status:         Running
IP:             10.244.82.17
Controlled By:  ReplicaSet/monitor-79c7564b77
Containers:
...
<< More information displayed that describes the deployment manifest and stack trace >>
----

If this error is observed:

 * Verify outbound TCP port 5672 is open to the Internet. Connections should be allowed from 
 the controller VM(s) running in your internal network to this hostname on the Internet.
 * A TCP proxy may be needed to establish a connection to the Internet. Check with your network
 team to verify and configure if needed. The 
 xref:install-port-reqs.adoc[Network and Ports Requirements] page should provide the 
 information required.
