= Uninstalling Runtime Fabric

Depending on your installation method, you can use the Runtime Fabric command line tool (`rtfctl`) or Helm to uninstall Runtime Fabric.

== Uninstall Runtime Fabric Using rtfctl

To uninstall Runtime Fabric using `rtfctl`:

. Using Runtime Manager, delete all Mule applications and API gateways deployed on Runtime Fabric.
. Verify on all associated environments that you have removed all applications.
. Using Runtime Manager, delete the Runtime Fabric.
. Run the `rtfctl uninstall` command to uninstall the Runtime Fabric services from the Kubernetes cluster.
. Run the `rtfctl uninstall --confirm` command to verify the uninstall operation.
. After the uninstall command finishes, verify that there are no Runtime Fabric applications or services running in the cluster.

== Uninstall Runtime Fabric Using Helm

To uninstall Runtime Fabric using Helm:

. Using Runtime Manager, delete all Mule applications and API gateways deployed on Runtime Fabric.
. Verify on all associated environments that you have removed all applications.
. Using Runtime Manager, delete the Runtime Fabric.
. Run the following command:
+
[source,copy]
----
helm uninstall runtime-fabric -n rtf
----
+
If need to uninstall due to an error in the installation process, for example, if the install did not complete correctly, run the following command:
+
[source,copy]
----
helm uninstall runtime-fabric -n rtf --no-hooks
----

== Uninstalling Runtime Fabric on Red Hat OpenShift

Perform the following procedure to uninstall Runtime Fabric on Red Hat OpenShift:

. Using Runtime Manager, delete all Mule applications and API gateways deployed on Runtime Fabric.
. Verify that you have removed all applications from all associated environments.
. Using Runtime Manager, delete the Runtime Fabric.
. In the Red Hat OpenShift console, navigate to **Operators** > **Installed Operators**.
. Select the Runtime Fabric operator.
. Click **Uninstall**.
