= Uninstalling Runtime Fabric

Depending on your installation method, you can use the Runtime Fabric command line tool (`rtfctl`) or Helm to uninstall Runtime Fabric.

[[unistall-rtfctl-rtf]]
== Uninstall Runtime Fabric Using RTFCTL

include::partial$rtfctl-commands.adoc[tag=uninstall-rtfctl,leveloffset=+2]

== Uninstall Runtime Fabric Using Helm

To uninstall Runtime Fabric using Helm:

. Using Runtime Manager, delete all Mule applications and API gateways deployed on Runtime Fabric.
. Verify on all associated environments that you have removed all applications.
. Using Runtime Manager, delete the Runtime Fabric.
. Run this command:
+
[source,copy]
----
helm uninstall runtime-fabric -n rtf
----
+
If need to uninstall due to an error in the installation process, for example, if the install did not complete correctly, run this command:
+
[source,copy]
----
helm uninstall runtime-fabric -n rtf --no-hooks
----

== Uninstalling Runtime Fabric on Red Hat OpenShift

Perform this procedure to uninstall Runtime Fabric on Red Hat OpenShift:

. Using Runtime Manager, delete all Mule applications and API gateways deployed on Runtime Fabric.
. Verify that you have removed all applications from all associated environments.
. Using Runtime Manager, delete the Runtime Fabric.
. In the Red Hat OpenShift console, navigate to **Operators** > **Installed Operators**.
. Select the Runtime Fabric operator.
. Click **Uninstall**.
. Using this Helm command, uninstall Runtime Fabric from the cluster:
+
[source,copy]
----
helm uninstall runtime-fabric -n rtf --no-hooks
----
. Delete the `rtf` namespace from the cluster:
+
[source,copy]
----
oc delete ns rtf
----

=== Troubleshooting Deletion of the rtf Namespace

If the command to delete the `rtf` namespace does not work, complete these steps:

. Run this command:
+
[source,copy]
----
oc get ns rtf -o json > rtf.json
----
. Edit `rtf.json` and remove `kubernetes` from the `finalizer` array.
. Run these commands:
+
[source,copy]
----
oc replace --raw "/api/v1/namespaces/rtf/finalize" -f ./rtf.json
oc get ns
----
. Confirm the `rtf` namespace is no longer present.

== See Also

* xref:install-index.adoc[Installing Runtime Fabric]
* xref:configuring-runtime-fabric.adoc[Configuring Runtime Fabric]
* xref:upgrade-index.adoc[Upgrading Runtime Fabric]