= Uninstalling Runtime Fabric

Depending on your installation method, you can use the Runtime Fabric command line tool (`rtfctl`) or Helm to uninstall Runtime Fabric.

[[unistall-rtfctl-rtf]]
== Uninstall Runtime Fabric Using rtfctl

To uninstall Runtime Fabric using `rtfctl`:

. Using Runtime Manager, delete all Mule applications and API gateways deployed on Runtime Fabric.
. Verify on all associated environments that you have removed all applications.
. Using Runtime Manager, delete the Runtime Fabric.
. Run the `rtfctl uninstall` command to uninstall the Runtime Fabric services from the Kubernetes cluster.
. Run the `rtfctl uninstall --confirm` command to verify the uninstall operation.
. After the uninstall command finishes, verify that there are no Runtime Fabric applications or services running in the cluster.

== Uninstall Runtime Fabric Using Helm

To uninstall Runtime Fabric using Helm:

. Using Runtime Manager, delete all Mule applications and API gateways deployed on Runtime Fabric.
. Verify on all associated environments that you have removed all applications.
. Using Runtime Manager, delete the Runtime Fabric.
. Run the following command:
+
[source,copy]
----
helm uninstall runtime-fabric -n rtf
----
+
If need to uninstall due to an error in the installation process, for example, if the install did not complete correctly, run the following command:
+
[source,copy]
----
helm uninstall runtime-fabric -n rtf --no-hooks
----

== Uninstalling Runtime Fabric on Red Hat OpenShift

Perform the following procedure to uninstall Runtime Fabric on Red Hat OpenShift:

. Using Runtime Manager, delete all Mule applications and API gateways deployed on Runtime Fabric.
. Verify that you have removed all applications from all associated environments.
. Using Runtime Manager, delete the Runtime Fabric.
. In the Red Hat OpenShift console, navigate to **Operators** > **Installed Operators**.
. Select the Runtime Fabric operator.
. Click **Uninstall**.
. Using the following Helm command, uninstall Runtime Fabric from the cluster:
+
[source,copy]
----
helm uninstall runtime-fabric -n rtf --no-hooks
----
. Delete the `rtf` namespace from the cluster:
+
[source,copy]
----
oc delete ns rtf
----

=== Troubleshooting Deletion of the rtf Namespace

If the command to delete the `rtf` namespace does not work, complete the following steps:

. Run the following command:
+
[source,copy]
----
oc get ns rtf -o json > rtf.json
----
. Edit `rtf.json` and remove `kubernetes` from the `finalizer` array.
. Run the following commands:
+
[source,copy]
----
oc replace --raw "/api/v1/namespaces/rtf/finalize" -f ./rtf.json
oc get ns
----
. Confirm the `rtf` namespace is no longer present.
