= Upgrading Runtime Fabric Using rtfctl

You can use the Runtime Fabric command line tool, `rtfctl`, to upgrade Anypoint Runtime Fabric on an Amazon Elastic Kubernetes Service (Amazon EKS), Amazon Elastic Kubernetes Service Anywhere (Amazon EKS-A), Azure Kubernetes Service (AKS) or Google Kubernetes Engine (GKE). 

== About Component Upgrades

Upgrading Runtime Fabric components means upgrading services that:

- Facilitate communication to the control plane
- Provide load balancing
- Log and forward metrics

When component upgrades are available, you apply the upgrades within Runtime Manager via a button that's visible when an upgrade is available.

Runtime Fabric component upgrades do not require adding a node.

=== Determine the Component Versions You Are Using

From a local workstation that has a `Kubeconfig` file and can access Kubernetes, or from a support bastion, run the following command:

[source,copy]
--
.rtfctl version
--

The output looks something like this:

```
$ ./rtfctl version
COMPONENT    VERSION
rtfctl       0.3.122
agent        1.9.6
kubernetes   1.19.6-eks-49a6c0
```

* The `rtfctl` field shows the `rtfctl` command-line utility version.
* The `agent` field shows the the Runtime Fabric component version.

[NOTE]
The Runtime Fabric component version that is in use is also displayed in the *Runtime Fabrics* tab in Runtime Manager. If an upgrade is available, Runtime Manager displays an *Upgrade to vx.x* message.

== About rtfctl Command-Line Utility Upgrades

Use the `rtfctl` command-line utility  to manage Runtime Fabric and perform upgrades.

Upgrade the `rtfctl` utility from the command line.

Always use the most current version of the `rtfctl` command-line utility to ensure you have the latest functionality.

== Apply the Upgrades

To upgrade Anypoint Runtime Fabric, you:

. Upgrade Runtime Fabric Components
. Upgrade the `rtfctl` command-line utility

Before upgrading your production environment, perform these steps on a nonproduction Runtime Fabric instance to verify compatibility with your environment. Plan to upgrade when your team is not deploying new applications or managing existing applications on Runtime Fabric. When your nonproduction upgrade succeeds, perform these steps in your production environment.

=== Upgrade Runtime Fabric Components

Review the xref:release-notes::runtime-fabric/runtime-fabric-release-notes-2.x.x.adoc[Anypoint Runtime Fabric Release Notes] information to learn more about the most recent component versions.

. Navigate to your Runtime Fabric by selecting it on the *Runtime Fabrics* tab in Runtime Manager.
. Select *Upgrade to vx.x*. The status of the Runtime Fabric is updated to show that the upgrade procedure is in progress.
. Wait for the status to transition to *Active*. 

In most cases, the upgrade takes fewer than 10 minutes. When the status transitions to *Active* and the version of the Runtime Fabric reflects the new version, the component upgrade is complete.

If the Runtime Fabric and Runtime Manager connection disconnects during the upgrade, connectivity is restored after the upgrade finishes.

After the upgrade, it’s normal for Runtime Fabric to report as “degraded” for a few minutes as it synchronizes with the control plane. This state automatically resolves after approximately five minutes.

=== Upgrade the `rtfctl` Command-Line Utility

. From your terminal, run the following command: 
+
[source,copy]
----
curl -L https://anypoint.mulesoft.com/runtimefabric/api/download/rtfctl/latest -o rtfctl
----
. Change file permissions for the `rtfctl` binary: 
+
[source,copy]
----
chmod +x rtfctl
----
. Alternatively, to update `rtfctl` in place as a user who owns the `rtfctl` binary, run:
+
[source,copy]
----
`rtfctl update`
----
