= Upgrade Path to Runtime Fabric Version 1.4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


. Upgrade the Runtime Fabric installer to the latest version. Perform this upgrade during your next scheduled maintenance window. You must complete this step before starting the upgrade to version 1.4.
. Upgrade to Runtime Fabric version 1.4. You must select Runtime Fabric version 1.4 in Runtime Manager and follow 
the instructions provided in xref:upgrade-index.adoc[Upgrade Runtime Fabric]. 
. After completing the upgrade, deploy an app.

== See Also

* xref:upgrade-cluster.adoc[Perform Runtime Fabric Cluster Upgrades]

Anypoint Runtime Fabric contains a collection of services which run within the cluster, including the agent used to connect to Anypoint Platform. Perform the following steps to upgrade these services.

== Before You Begin

* Run the upgrade procedure on a non-production Runtime Fabric to verify compatibility with your environment.
* Plan the upgrade procedure when your team does not need to deploy new applications or managing existing applications on Runtime Fabric.

** The upgrade should be complete within 10 minutes in most cases.
** The Runtime Fabric and Anypoint Runtime Manager connection may disconnect during the upgrade procedure. Connectivity is restored after the upgrade completes.

== Availability of Deployed Applications

The upgrade procedure is designed to keep deployed applications running and available to serve requests. The majority of the services which are upgradable via this process run within the controller nodes. Impact to running Mules and the worker nodes are minimal by design.

== Apply the Component Upgrade

. Navigate to your Runtime Fabric by selecting your Runtime Fabric on the Runtime Fabrics tab under Runtime Manager.
. If an upgrade is available, click on the "Upgrade to v1.x" button. The status of the Runtime Fabric will update to reflect the upgrade procedure is in progress.
. Wait for the status to transition to Active.
. Once the status transitions to Active, and the version of the Runtime Fabric reflects the new version, the upgrade is complete.

== Troubleshooting Upgrade Errors

TBD

== See Also

* xref:upgrade-cluster.adoc[Upgrade Runtime Fabric Cluster]
