= Upgrade Runtime Fabric for Self-Managed Kubernetes

To upgrade Anypoint Runtime Fabric for Self-Managed Kubernetes, upgrade Runtime Fabric components and the `rtfctl` command-line utility.

== About Component Upgrades

Runtime Fabric component upgrades involve the internal services that run within the appliance used to facilitate communication to the Anypoint control plane, provide load balancing, and log and metrics forwarding.

Runtime Fabric component upgrades are applied within Runtime Manager via a button that's visible when an upgrade is made available.

Runtime Fabric component upgrades do not require adding a node.

== About rtfctl Command-Line Utility Upgrades
The `rtfctl` command-line utility is used to manage Runtime Fabric and perform appliance and node configuration upgrades.

You upgrade the `rtfctl` utility from the command line.

It is important to use the most current version of the `rtfctl` command-line utility.

== Determine the Component Versions You Are Using

From your local workstation (configured with a kubeconfig file) or a support bastion, run the following command:
```
.rtfctl version
```

Output includes:

* The `rtfctl` command-line utility version in the `rtfctl` field
* The Runtime Fabric component version in the `agent` field

For example:
```
$ ./rtfctl version
COMPONENT    VERSION
rtfctl       0.3.122
agent        1.9.6
kubernetes   1.19.6-eks-49a6c0

```

[NOTE]
The Runtime Fabric component version that is in use are also displayed in the *Runtime Fabrics* tab in Runtime Manager. If an upgrade is available, an "Upgrade to vx.x" message is displayed.

== Apply the Upgrades

To upgrade Anypoint Runtime Fabric for Self-Managed Kubernetes, you:

. Upgrade Runtime Fabric Components
. Upgrade the `rtfctl` command-line utility

Before upgrading your production environment, perform these steps on a nonproduction Runtime Fabric to verify compatibility with your environment. Plan to upgrade when your team is not deploying new applications or managing existing applications on Runtime Fabric.

Review the xref:release-notes::runtime-fabric/runtime-fabric-release-notes.adoc[Anypoint Runtime Fabric Release Notes] information.

=== Upgrade Runtime Fabric Components

Review the xref:release-notes::runtime-fabric/runtime-fabric-release-notes.adoc[Anypoint Runtime Fabric Release Notes] information to learn more about the most recent component versions.

. Navigate to your Runtime Fabric by selecting it on the *Runtime Fabrics* tab in Runtime Manager.
. Select *Upgrade to vx.x*. The status of the Runtime Fabric is updated to show that the upgrade procedure is in progress.
. Wait for the status to transition to *Active*. 

In most cases, the upgrade takes fewer than 10 minutes. When the status transitions to *Active* and the version of the Runtime Fabric reflects the new version, the component upgrade is complete.

If the Runtime Fabric and Runtime Manager connection disconnects during the upgrade, connectivity is restored after the upgrade finishes.

After the upgrade, it’s normal for Runtime Fabric to report as “degraded” for a few minutes as it synchronizes with the control plane. This state automatically resolves after approximately five minutes.

=== Upgrade the `rtfctl` Command-Line Utility

. From your terminal run the following command: 
+
----
curl -L https://anypoint.mulesoft.com/runtimefabric/api/download/rtfctl/latest -o rtfctl
----
. Change file permissions for the `rtfctl` binary: 
+
----
chmod +x rtfctl
----
. Alternatively, to update `rtfctl` in place as a user who owns the `rtfctl` binary, run
+
----
`rtfctl update`
----
