= Upgrade Runtime Fabric Using Helm

You can use Helm to upgrade Anypoint Runtime Fabric on an Amazon Elastic Kubernetes Service (Amazon EKS), Azure Kubernetes Service (AKS), or Google Kubernetes Engine (GKE) installation that you manage.

Helm upgrades are not available for existing installations that used the `rtfctl` command line tool.

When you upgrade Runtime Fabric using Helm, Runtime Manager provides the Helm command you need to run the upgrade.

[IMPORTANT]
--
The upgrade command supplied by Runtime Manager uses the same parameters and values you added to the Helm command when you installed Runtime Fabric. If you changed any values after install, such as proxy values, and want to keep those values after the upgrade, you need to add them to the upgrade command before you run the upgrade. 
-- 

To upgrade Runtime Fabric Using Helm:

. In Runtime Manager, navigate to your Runtime Fabric by selecting it on the Runtime Fabrics tab.
. Click *Upgrade…*. 
. Follow the prompts to generate and download the `values.yml` file.
. Add any optional parameters needed. 
+
Refer to the xref:install-helm.adoc#values-yml-reference[`values.yml` Reference] in the installation documentation for a list of optional and required parameters. 
. Run the following command:
+
----
helm install -f values.yaml
----
