= Using Anypoint Monitoring

Mule apps and API gateways deployed to Runtime Fabric include native support for Anypoint Monitoring that allows viewing metrics from within Anypoint Platform.

== Anypoint Monitoring

xref:monitoring::index.adoc[Anypoint Monitoring] includes tools that provide feedback from Mule flows and components in your Mule app network. Anypoint Monitoring runs as a sidecar in application deployments and gathers metrics for Mule apps and API gateways deployed to Runtime Fabric. Titanium-plan customers have access to additional capabilities, including application log retrieval and search.

== Enable Anypoint Monitoring

By default, Runtime Fabric is configured to send application metrics to Anypoint Monitoring. Data is securely transmitted using mutual TLS encryption. For metrics and logs to be sent to Anypoint Monitoring, outbound network connectivity must be available. 

If you need an outbound proxy, configure Anypoint Runtime Fabric to use a SOCKS5 proxy by following the instructions in xref:manage-proxy-self.adoc[Configuring Proxies on Runtime Fabric].

To verify outbound network connectivity on Anypoint Runtime Fabric version 1.8.50 or later, ensure that each node in Runtime Fabric can send outbound TCP (Lumberjack) communication using port 443 to the following domains:

* US control plane: +
`dias-ingestor-router.us-east-1.prod.cloudhub.io` +
`us1.ingest.mulesoft.com` +

* EU control plane: +
`dias-ingestor-router.eu-central-1.prod-eu.msap.io` +
`eu1.ingest.mulesoft.com` +

[NOTE]
====
If you are using a version of Anypoint Runtime Fabric older than 1.8.50, use port 5044 instead of port 443. Use the following domains:

* US control plane: `dias-ingestor-nginx.prod.cloudhub.io` 
* EU control plane: `dias-ingestor-nginx.prod-eu.msap.io`
====

For further details on Anypoint Monitoring endpoints, refer to xref:install-self-managed-network-configuration.adoc[configuring your network to support Runtime Fabric].


== Metrics

Each Mule app and API gateway replica runs a metrics agent that collects and transmits metrics data to 
Anypoint Monitoring via secure mutual TLS encryption. Each replica can cache up to 100 megabytes of metrics, after which the metrics data is rotated to provide storage for more recent data. If metrics can't be sent to Anypoint Monitoring, this typically provides at least four days worth of storage per replica. Custom metrics might consume more storage.

The following Anypoint Runtime Fabric updates do not impact or restore monitoring metrics of applications deployed on Runtime Fabric:

* A backup and restore of Runtime Fabric
* An upgrade of Runtime Fabric
* OS patching of Runtime Fabric nodes


== Logs 

Anypoint Monitoring provides access to xref:monitoring::logs.adoc[log data] for applications deployed to Rutime Fabric. To access logs with Anypoint Monitoring, you need a https://www.mulesoft.com/anypoint-pricing[Titanium subscription]. 

Each Mule app and API gateway replica can store up to 450 megabytes of log data on disk, after which log data 
is rotated to provide storage for more recent log data.

Logs generated by each replica of a Mule app and API gateway are collected and written to disk on the worker 
node on which they are running. Each worker node runs a single log forwarding agent, which monitors this location 
and transmits the log data to Anypoint Monitoring.

The log forwarding agent can transmit up to 300 kilobytes of log data per second. You should not deploy more than
50 replicas per worker node.

In some cases, logs with multiple lines might not be fully transmitted to Anypoint Monitoring. This can occur if 
multiple lines of log output are split across two files due to log rotation inside Runtime Fabric.

You can enable log forwarding and set log levels when you xref:deploy-to-runtime-fabric.adoc#configure-logging-and-log-levels[deploy applications in Runtime Manager]. 

=== Resource and Permission Requirements for Anypoint Monitoring Agent

MuleSoft runs Anypoint Monitoring agents alongside Mule apps to send telemetry to the Anypoint control plane.

For Mule apps deployed or managed using Runtime Fabric agent version 2.5.x or lower, two different agents are used as follows:

* One DaemonSet per underlying node to transport logs to Anypoint monitoring control plane.
* One sidecar per application replica to transporting metrics to Anypoint monitoring control plane. 

For optimal daemonset functionality, follow these prerequisites:

. Check that the application containers write logs to the following locations:

* `/var/log/pods`
* `/var/log/containers`
* `/var/lib/docker/containers`

. Check that the DaemonSet creates and writes on the host path `/var/lib/filebeat-data`.
. Ensure that the Docker daemon config includes the `json-file` logging driver.
. Ensure that the Anypoint Monitoring log forwarder DaemonSet container has write access to the host on the host path `/var/lib/filebeat-data`.

For applications deployed or managed using Runtime Fabric versions 2.6.x and above, MuleSoft consolidates telemetry transport to a single sidecar per application replica.

Dependent on the features you use, the sidecar agent consumes corresponding resources for optimal performance:

* To enable default Anypoint metrics, the sidecar agent (per application replica) requires 0.05vCPU or Core of CPU allocation and 90MiB memory allocation.

* If you opt into xref:runtime-fabric/deploy-to-runtime-fabric.adoc#configure-logging-and-log-levels[forwarding application logs to Anypoint Monitoring], the sidecar agent (per application replica) requires up to 30% of CPU limit configured for application replica and up to 150MiB memory allocation

[NOTE]
Allocate appropriate capacity to the underlying cluster to avoid application deployment failure.

== Anypoint Visualizer

xref:visualizer::index.adoc[Anypoint Visualizer] displays views of different aspects of an application network graph. 
You can use the graph to explore your application network, identify problems, and make decisions.

[WARNING]
====
By default, Anypoint Visualizer is disabled when deploying an application to Mule runtime 4.x. 
See xref:visualizer::setup.adoc#enable-header-injection[Enable Header Injection] for more information.
Due to the impact on performance, enabling Anypoint Visualizer for application deployments with less than 0.2 vCPU is 
not supported.
====

== (Optional) Disable Anypoint Monitoring for a Mule App

When you deploy a Mule app to Runtime Fabric, Anypoint Monitoring is enabled by default. To disable Anypoint 
Monitoring, pass the following custom property when deploying your Mule app:

[source,copy]
----
anypoint.platform.config.analytics.agent.enabled=false
----

[NOTE]
For compliance or geospecific requirements if your team or organization cannot send metrics to Anypoint control plane, you can disable Anypoint metrics if you are not contractually obligated to send these metrics for Anypoint usage and billing purposes.

== Enable OpenTelemetry Exporter

Enable trace data collection for Mule apps running on Mule Runtime [versions tbd] by using the xref:monitoring::telemetry-exporter.adoc[OpenTelemetry Exporter] in Anypoint Monitoring. 

OpenTelemetry enables Mule runtime engine to bring observability to the behavior of Mule apps, and also, because of distributed tracing, to the interaction between different Mule apps. With the exporter, you can export traces to third-party observability and analytics apps.

There is no additional Runtime Fabric configuration to use OpenTelemetry.
