= Use Ops Center to Monitor Anypoint Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can use the built-in Ops Center to monitor the health of your Anypoint Runtime Fabric clusters.

== Access Ops Center
You can use the Ops Center to monitor dashboards, view logs, and download debugging information within Anypoint Runtime Fabric.

During the installation process for Runtime Fabric, one of the last outputs to the logs includes the following information required to log into Ops Center.

----
Ops Center access:
URL:      https://<any-node-ip>:32009/web
User:     admin@runtime-fabric
Password: ***********************
----

[NOTE]
You must retrieve the Ops Center URL from the logs on the installer node. Although the log file is available on all nodes of the cluster, only the installer node has the URL and credentials for the Ops Center. 

. Using a terminal, open a shell/SSH connection to the installer VM.
. Run this command to open the log file and search for the credentials:
+
----
cat /var/log/rtf-init.log | grep -B 1 -A 3 "Ops Center"
----
+
. Store the details in a safe location.
. Open a web browser and navigate to the URL, replacing `<any-node-ip>` with a public or private IP address
of any controller VM.
. Log into the Runtime Fabric Ops Center using the credentials obtained from the log.

[NOTE]
Verify port 32009 is open and accessible in your Security Group, Network Security Group or firewall rules.
If using a private IP address, ensure you have access to the same internal network as the VM resides in.

== Regain Access to the Ops Center
If you lose the install logs, perform the following steps:

. Open a terminal into one of the controller nodes.
. From the SSH terminal, run the following command to create a new user with admin rights to log into the
Ops Center. Provide the appropriate values for `--email` and `--password`.
----
sudo gravity planet enter -- --notty /usr/bin/gravity -- user create --ops-url=https://gravity-site.kube-system.svc.cluster.local:3009 --insecure --email=username@myorganization.com --password=myNewPassword --type=admin
----

== Viewing Dashboards

After logging into Ops Center, you'll see a list of tabs on the left of the page. Navigate to "Monitoring"
to view the dashboards available for viewing.

=== View Metrics from an Application

From Ops Center, you can view metrics from a deployed application.

. In Ops Center, click * *Monitoring* on the left sidebar.
. Click the * *Cluster*  tab to open the dashboards pane and click * *Applications*.
. Select the environment ID where the application was deployed on the Environment dropdown.
. Select the application name on the Application dropdown.

The dashboad should populate the metrics for your application. By default, Ops Center displays a set of
graphs that show CPU, JVM heap memory, total memory, network, and file system usage.

JVM Heap Memory is also displayed in Anypoint Monitoring.

=== Dashboards

The dashboards are divided into the following categories:

* *Cluster* shows metrics on the overall Runtime Fabric cluster. Filters include the `nodename`, allowing
you to filter by specific VM.
* *Applications* shows metrics on all the replicas for an application deployment. Filters include the
environment ID the application is deployed in, and the application deployment name.
* *Ingress* shows metrics on all the replicas running the internal load balancer.
* *Pods*  shows metrics on each individual service running within the Runtime Fabric cluster. Filters
include the `namespace` and `podname`, allowing you to specify the specific service to monitor.
** When selecting `namespace`, you'll see GUIDs which correspond to your Anypoint environment IDs under
which your applications are deployed.
** When selecting `podname`, you'll see values prefixed by the application name. These refer to replicas of
each application deployment.

== Viewing Logs

See xref:runtime-fabric-logs.adoc[View and Configure Logs in Runtime Fabric]

== Download Debug Info

If you encounter an issue with Runtime Fabric, MuleSoft Support team may ask for a packaged file 
containing debugging information. Follow these steps to generate the debug information package:

. From Ops Center, click *Admin* in the left side of the page.
. Click *Download Debug Info* in the upper right corner of the page.
+
A new tab might open while the request is being processed by Runtime Fabric. Generating this file can 
take several minutes.
+
Ops Center downloads a file named `report.tar.gz`.

== See Also

* xref:configure-alerting.adoc[Configure Alerting on Anypoint Runtime Fabric]
* xref:runtime-fabric-logs.adoc[Configure Log Forwarding on Anypoint Runtime Fabric]
