= Using Ops Center on Anypoint Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic describes how to use the built-in Ops Center to monitor dashboards, view logs, and download debugging information within Anypoint Runtime Fabric.

== Accessing Ops Center

During the installation process for Runtime Fabric, one of the last outputs to the logs includes the following information required to log into Ops Center.

----
Administrator access:
URL:      https://<any-node-ip>:32009/web
User:     admin@runtime-fabric
Password: ***********************
----

Retrieve this information from the log output on the installer VM:

. Using a terminal, open a shell/SSH connection to the installer VM.
. Run this command to open the log file and search for the credentials:
+
----
cat /var/log/rtf-init.log | grep -B 1 -A 3 "Administrator access"
----
+
. Store the details in a safe location.
. Open a web browser and navigate to the URL, replacing `<any-node-ip>` with a public or private IP address of any controller VM.
. Log into the Runtime Fabric Ops Center using the credentials obtained from the log.

[NOTE]
Verify port 32009 is open and accessible in your Security Group, Network Security Group or firewall rules. If using a private IP address, ensure you have access to the same internal network as the VM resides in.

== Viewing Dashboards

After logging into Ops Center, you'll see a list of tabs on the left of the page. Navigate to "Monitoring" to view the dashboards available for viewing.

=== View Metrics from an Application

With Ops Center, you can view metrics from a deployed application.

. On Ops Center, click on Kubernetes on the left sidebar.
. Click on the Pods tab.
. Select the environment ID where the application was deployed on the right dropdown, near the search input.
. Find the Pod name which begins with the name of your application.
. Click on the Pod name and select "Monitoring".

The page should redirect to the Monitoring tab with a filter applied to your application. By default, a set of graphs showing the CPU, Memory, Network, and Filesystem usage will be visible.


=== Cluster and Pods

The dashboards are divided into two main categories:

* _Cluster_ shows metrics on the overall Runtime Fabric cluster. Filters include the `nodename`, allowing you to filter by specific VM.
* _Pods_ show metrics on each individual service running within the Runtime Fabric cluster. Filters include the `namespace` and `podname`, allowing you to specify the specific service to monitor.
** When selecting `namespace`, you'll see GUIDs which correspond to your Anypoint environment IDs where your applications are deployed under.
** When selecting `podname`, you'll see values prefixed by the application name. These refer to replicas of each application deployment.

== Viewing Logs

Ops Center shows a stream of logs outputted by applications and services running on Runtime Fabric. Navigate to "Logging" on the left of the page to view the logging interface.

=== View Logs from an Application

With Ops Center, you can view the logs from a deployed application. This can be useful in cases where log forwarding is not set up.

. On Ops Center, click on Kubernetes on the left sidebar.
. Click on the Pods tab.
. Select the environment ID where the application was deployed on the right dropdown, near the search input.
. Find the Pod name which begins with the name of your application.
. Click on the Pod name and select "Logs".

The page should redirect to the Logs tab with a filter applied to your application.

[NOTE]
To view the latest logs, click the "Refresh" button on the upper right portion of the page.

=== Filters

There are two levels of filters to help drill down on the logs to make visible:

* _Containers_ filter on names of containers.
* _Pods_ filter on the names of pods. This is useful for specifying application names followed by a wildcard (`%`).

== Download Debug Info

If you encounter an issue with Runtime Fabric, MuleSoft Support team may ask for a packaged file containing debugging information. Follow these steps to generate the debug information package:

. On Ops Center, click on the Admin link on the left side of the page.
. Click "Download Debug Info" button on the upper right corner of the page.
+
* A new tab may open while the request is being processed by Runtime Fabric. Generating this file can take several minutes.
+
. A file will begin to download, named `report.tar.gz`.

== See Also

* xref:configure-alerting.adoc[Configure Alerting on Anypoint Runtime Fabric]
* xref:configure-log-forwarding.adoc[Configure Log Forwarding on Anypoint Runtime Fabric]