= Viewing Log Data for Deployed Applications

Runtime Fabric provides access to log data that includes deployment messages and events for each replica and Mule runtime engine logs.

For more advanced searching and log management, you can use Anypoint Monitoring (requires Titanium subscription).
See xref:manage-monitor-applications.adoc#logs-titanium[].

== View Logs

To view logs for deployed applications:

. From Anypoint Platform, select *Runtime Manager* > *Applications*.
. Click the app name.
. In the navigation menu, click *Logs*.

The logs page displays all logs for all replicas for the selected config, with the latest messages at the bottom. The config represents the deployment since the last update.

[NOTE]
When you update an application, a new configuration is created. In this case, the logs page might be empty.

The page streams log messages as they occur, unless the last deployed section is closed. Logs from before the last updated time appear in a drop-down containing previous deployments.

Each message includes the severity, time (relative and absolute), and replica name.

To view logs for a different config, click the *Config* drop-down list and select the config. The config label indicates the relative time of deployment, such as 10 hours ago.

== Search Logs

To search within the currently displayed config:

. From Anypoint Platform, select *Runtime Manager* > *Applications*.
. Click the app name.
. In the navigation menu, click *Logs*.
. Enter the search term in the *Search* field.
+
The results display includes the currently selected config, replica, and log levels.

== Filter Logs

To filter the log results:

. From Anypoint Platform, select *Runtime Manager* > *Applications*.
. Click the app name.
. In the navigation menu, click *Logs*.
. Select filter options:
+
** Filter logs by config ID
+
Click the *Config* drop-down menu and select the config to view.

** *Filter log by replica*
+
In a log message for the desired replica, click the name of the replica.
+
Only the logs for the selected replica appear.
+
To clear the replica filter and display logs for all replicas, click the *X* button for the selected replica.

** *Filter logs by time date and time range*
+
Click *Time Range*, select the date range, and optionally time, and click *Apply*.
+
The *Time range* button label changes to show the selected date and time range.

** *Filter logs by log level*
+
Click *Log Levels* and check the log levels to display:
+
--
** *Fatal*: Fatal messages for when an application fails
** *Error*: Error messages, such as when an exception occurs
** *Warn*: Warning messages
** *Info*: Informative messages
** *Debug*: Debugging messages
--
+
[NOTE]
Some log levels might not be available depending on the dynamic log level setting for the deployment.
+
The *Log Levels* button label changes to show the selected number of log levels.

== Download Logs

To download logs based on the current filters:

. From Anypoint Platform, select *Runtime Manager* > *Applications*.
. Click the app name.
. In the navigation menu, click *Logs*.
. Click the download button.

Runtime Fabric downloads the log output, using the current filters, using a hexadecimal naming convention and the `log` format, for example: `c6c671_462ccf_2022-07-21T20-08-32X.log`. Use a text editor to view the log file.