= View Runtime Fabric Health Details
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can use Anypoint Runtime Manager to view the health of your Anypoint Runtime Fabric clusters. 

== Health Details

For Runtime Fabric version 1.5 or later:

. Navigate to Runtime Manager and select *Runtime Fabric*.
. Select the name of your Runtime Fabric cluster to open the management page.
. Select *Health Details*.
+
The *Health Details* section indicates whether your Runtime Fabric cluster configuration meets the requirements for a production environment, a development environment, or neither. If your configuration fails to meet the minimum requirements of both production and development environments, `Not supported` is displayed. 


If you are using Runtime Fabric on VMs / Bare Metal, you can view additional performance and Runtime Fabric cluster health information using the Ops Center. See xref:using-opscenter[Use Ops Center to Monitor Runtime Fabric] for more information.
