// tag::licenseKey[]
== Insert the Mule License Key

If you didn’t add the Mule license key during install, you can add it using the `rtfctl` command line utility.

After the installation has completed succesfully, insert the Mule license key.

. Base64 encode the new Mule `.lic` license file provided by MuleSoft:
+
* On MacOS, run the following command:
+
[source,copy]
----
BASE64_ENCODED_LICENSE=$(base64 -b0 license.lic)
----
+
* On Unix, run the following command:
+
[source,copy]
----
BASE64_ENCODED_LICENSE=$(base64 -w0 license.lic)
----
+
* On Windows, choose one of the following:

** Use a WSL or Cygwin shell that includes the base64 tool and use the above Unix command.
** Use the base64.exe program included with Windows git (C:\Program Files\Git\usr\bin).
** Use the following Powershell command:
+
[source,copy]
----
$BASE64_ENCODED_LICENSE=[convert]::ToBase64String((Get-Content -path "license.lic" -Encoding byte))
----

. On the controller node acting as the leader during installation (the installer node), use the `rtfctl` utility with the Base64 value of your license key: 
+
[source,copy]
----
rtfctl apply mule-license $BASE64_ENCODED_LICENSE
----

. To verify the Mule license key has applied correctly, run:
+
[source,copy]
----
rtfctl get mule-license
----
// end::licenseKey[]

// tag::ingressResource[]

== Configure the Ingress Resource Template

If your ingress controller requires custom annotations and ingress class definition, follow the instructions in xref:custom-ingress-configuration.adoc[Defining a Custom Ingress Configuration].

[NOTE]
====
For GKE customers, the ingress controller included with GKE will provision a separate HTTP load balancer per application by default. Please read this link:https://help.mulesoft.com/s/article/Default-Ingress-Controller-Behavior-with-Runtime-Fabric-on-GKE[KB article] for more details.
====
// end::ingressResource[]

// tag::validate[]
== Validate Your Runtime Fabric

After completing the installation, your Runtime Fabric should be activated within your Anypoint organization. To validate your installation, go to Anypoint Runtime Manager and confirm that the status of the Runtime Fabric is `Active`.

Before deploying an application to your Runtime Fabric:

. Associate the Runtime Fabric with at least one Anypoint environment.
. Review and update the Inbound Traffic settings based upon your Kubernetes environment.
. Deploy an application to verify that Runtime Fabric is installed and configured correctly.
// end::validate[]
