// Partial content for managing Mule apps with RTFCTL
// Used by multiple navigation entry points

[%header%autowidth.spread,cols="a,a"]
|===
|Command |Description
|xref:delete[`delete`] | Deletes a secure property
|xref:describe[`describe`] | Displays details for an application
|xref:disk[`disk`] | Displays disk usage for an application
|xref:memory[`memory`] | Displays the JVM memory usage in a pod
|xref:package[`package`] | Creates a debugging information package for an application
|xref:restart[`restart`] | Restarts an application
|xref:heapdump[`heapdump`] | Captures a JVM heap dump
|xref:threaddump[`threaddump`] | Captures a JVM thread dump
|===

[[delete]]
= `delete`
Deletes a secure property
----
rtfctl delete secure-property <sample_key> -n <app_namespace>
----

[[describe]]
= `describe`

Displays details for an application in a specific namespace

----
rtfctl describe apps <app_name> --namespace <rtf_namespace>
rtfctl describe apps <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[disk]]
= `disk`

Displays disk usage for an application

* Displays the disk usage for an application, using the first replica by default
+
----
rtfctl disk <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Displays the disk usage for an application, using a specific replica
+
----
rtfctl disk <app_name> --details --pod <replica_name> --app-namespace <app_namespace> --namespace <rtf_namespace>

----

[[memory]]
= `memory`
Displays the JVM memory usage in a pod

* Gets the JVM memory for each replica
+
----
rtfctl memory <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Gets the JVM memory for a particular replica
+
----
rtfctl memory <app_name> --pod <replica_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[package]]
= `package`
Creates a debugging information package for an application

* Creates a package for an application using the first pod by default
+
----
rtfctl package <app_name> <application_package_filename> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Creates a package for an application containing the apps, policies, and `.mule` directories
+
----
rtfctl package <app_name> <application_package_filename> --apps --policies --dotmule --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Creates a package for an application containing a heap dump
+
----
rtfctl package <app_name> <application_package_filename> --heap-dump --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[restart]]
= `restart`
Restarts an application

----
rtfctl restart <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[heapdump]]
= `heapdump`
Triggers a JVM heap dump

* Performs a JVM heap dump for an application, saving it as ``/tmp/dump.hprof`, using the first replica by default
+
----
rtfctl heapdump <app_name> <destination_path> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Performs a JVM heap dump for an application, saving it as `/tmp/dump.hprof`, using a specific replica
+
----
rtfctl heapdump <app_name> <destination_path> --pod <replica_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[threaddump]]
= `threaddump`
Triggers a JVM threaddump

* Performs a JVM thread dump for an application using the first replica by default
+
----
rtfctl threaddump <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Performs a JVM thread dump for an application using a specific replica
+
----
rtfctl threaddump <app_name> --pod <replica_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

== See Also

* xref:using-rtfctl.adoc[]
