// Use leveloffset=+2 to change the H1s to H3s.
// Installing Runtime Fabric Using RTFCTL

tag::install-rtfctl[]
[%header%autowidth.spread,cols="a,a"]
|===
|Command |Description
|xref:install[`install`] | Installs Runtime Fabric
|xref:validate[`validate`] | Validates the cluster for Runtime Fabric installation
|xref:version[`version`] | Displays the Runtime Fabric version information
|===

[[install]]
= `install`

* Installs Runtime Fabric

----
rtfctl install <activation_data>
----

* Override the Docker image registry URL and secret 
+
----
rtfctl install <activation_data> --image-pull-registry <string>  --image-pull-secret <string>
----

[[validate]]
= `validate`
Validates the cluster for a Runtime Fabric installation

* Performs a validation check
+
----
rtfctl validate <activation_data>
----

* Performs a validation check and passes the `fabric.tf` configuration file that contains proxy settings
+
----
rtfctl validate -f <path_to_settings_file>
----
+
To validate installation with a proxy, you must specify proxy settings in your `settings` file:

----
MULE_LICENSE=<your-mule-license>
ACTIVATION_DATA=<activation_data>
HTTP_PROXY=http://<proxy_domain>.com:<port>
----

* Override the Docker image registry URL and secret 
+
----
rtfctl validate <activation_data> --image-pull-registry <string> --image-pull-secret <string>
----

[[version]]
= `version` 
Displays the Runtime Fabric version information

----
rtfctl version --namespace <rtf_namespace>
----

end::install-rtfctl[]

// Add H2 heading where included
// Use leveloffset=+2 to change the H1s to H3s.
// == Backing Up and Restoring Runtime Fabric 

tag::restore-rtfctl[]

[%header%autowidth.spread,cols="a,a"]
|===
|Command |Description
|xref:backup[`backup`] | Performs a back up of the local Runtime Fabric state
|xref:restore[`restore`] | Restores local Runtime Fabric state from a backup
|===

[[backup]]
= `backup`
Performs a back up of the local Runtime Fabric state.
----
rtfctl backup <backup_file_name>.tar.gz --namespace <rtf_namespace>
----

[[restore]]
= `restore`
Restores the local Runtime Fabric state from a backup 

----
rtfctl restore <backup_file_name>.tar.gz --namespace <rtf_namespace>
----

Restore only the core Runtime Fabric software components without triggering application synchronization from the control plane.

----
rtfctl restore <backup_file_name>.tar.gz --namespace <rtf_namespace> --core-software-only
----

end::restore-rtfctl[]


// Add H2 heading where included
// Use leveloffset=+2 to change the H1s to H3s.
// Managing Mule Apps Deployed to Runtime Fabric

tag::manage-apps-rtfctl[]

[%header%autowidth.spread,cols="a,a"]
|===
|Command |Description
|xref:delete[`delete`] | Deletes a secure property
|xref:describe[`describe`] | Displays details for an application
|xref:disk[`disk`] | Displays disk usage for an application
|xref:memory[`memory`] | Displays the JVM memory usage in a pod
|xref:package[`package`] | Creates a debugging information package for an application
|xref:restart[`restart`] | Restarts an application
|xref:heapdump[`heapdump`] | Captures a JVM heap dump
|xref:threaddump[`threaddump`] | Captures a JVM thread dump
|===

[[delete]]
= `delete`
Deletes a secure property
----
rtfctl delete secure-property <sample_key> -n <app_namespace>
----

[[describe]]
= `describe`

Displays details for an application in a specific namespace 

----
rtfctl describe apps <app_name> --namespace <rtf_namespace>
rtfctl describe apps <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[disk]]
= `disk`

Displays disk usage for an application

* Displays the disk usage for an application, using the first replica by default
+
----
rtfctl disk <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Displays the disk usage for an application, using a specific replica
+
----
rtfctl disk <app_name> --details --pod <replica_name> --app-namespace <app_namespace> --namespace <rtf_namespace>

----

[[memory]]
= `memory`
Displays the JVM memory usage in a pod

* Gets the JVM memory for each replica
+
----
rtfctl memory <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Gets the JVM memory for a particular replica
+
----
rtfctl memory <app_name> --pod <replica_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[package]]
= `package` 
Creates a debugging information package for an application

* Creates a package for an application using the first pod by default
+
----
rtfctl package <app_name> <application_package_filename> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Creates a package for an application containing the apps, policies, and `.mule` directories
+
----
rtfctl package <app_name> <application_package_filename> --apps --policies --dotmule --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Creates a package for an application containing a heap dump
+
----
rtfctl package <app_name> <application_package_filename> --heap-dump --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[restart]]
= `restart`
Restarts an application

----
rtfctl restart <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[heapdump]]
= `heapdump`
Triggers a JVM heap dump

* Performs a JVM heap dump for an application, saving it as ``/tmp/dump.hprof`, using the first replica by default
+
----
rtfctl heapdump <app_name> <destination_path> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Performs a JVM heap dump for an application, saving it as `/tmp/dump.hprof`, using a specific replica
+
----
rtfctl heapdump <app_name> <destination_path> --pod <replica_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[threaddump]]
= `threaddump`
Triggers a JVM threaddump

* Performs a JVM thread dump for an application using the first replica by default
+
----
rtfctl threaddump <app_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Performs a JVM thread dump for an application using a specific replica 
+
----
rtfctl threaddump <app_name> --pod <replica_name> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

end::manage-apps-rtfctl[]

// Configuring Runtime Fabric with RTFCTL
tag::configure-rtfctl[]

[%header%autowidth.spread,cols="a,a"]
|===
|Command |Description
|xref:apply[`apply`] | Applies changes to a Runtime Fabric configuration
|xref:update[`update`] | Updates rtfctl
|xref:wait[`wait`] | Waits for Runtime Fabric components to become ready
|xref:renew[`renew-expired-client-cert`] | Renews an expired client certificate using a pre-downloaded package
|===

[[apply]]
= `apply` 

Applies changes to a Runtime Fabric configuration.

[NOTE]
You can use the `rtfctl apply system-configuration` command to update OpenShift system-configuration values. Other rtfctl apply commands are not effective for OpenShift. For any other updates, modify the values in the OpenShift console.

* Applies an HTTP proxy configuration
+
----
rtfctl apply http-proxy http://<host>:<port> --namespace <rtf_namespace>
----

* Applies an HTTP proxy configuration with hostnames bypassing the proxy
+
----
rtfctl apply http-proxy http://<host>:<port> --no-proxy "DOMAIN1.com,DOMAIN2.com" --namespace <rtf_namespace>
----

* Applies an HTTP proxy configuration with authentication
+
----
rtfctl apply http-proxy http://<username>:<password>@<host>:<port> --namespace <rtf_namespace>
----

* Clears an HTTP proxy configuration
+
----
rtfctl apply http-proxy "" --no-proxy "" --namespace <rtf_namespace>
----

* Applies a secure property
+
----
rtfctl apply secure-property --key <key> --value <value> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Applies a system configuration on a host node
+
----
rtfctl apply system-configuration
----

* Applies a system configuration on a host node without downloading the latest scripts
+
----
rtfctl apply system-configuration --skip-download
----

* Applies a Mule license
+
----
rtfctl apply mule-license <base64_encoded_license> --namespace <rtf_namespace>
----
If Runtime Fabric is installed via Helm, you must update the `mule-license` property in the Helm values.

* Applies a monitoring proxy
+
----
rtfctl apply monitoring-proxy http://<host>:<port> --namespace <rtf_namespace>
----

* Clears a monitoring proxy configuration
+
----
rtfctl apply monitoring-proxy "" --namespace <rtf_namespace>
----

[[update]]
= `update`

Updates `rtfctl`.

* Updates `rtfctl` from the US Cloud
+
----
rtfctl update
----

* Updates `rtfctl` from the EU Cloud
+
----
rtfctl update --host eu1.anypoint.mulesoft.com
----

* Updates `rtfctl` from the Canada Cloud
+
----
rtfctl update --host ca1.platform.mulesoft.com
----

* Updates `rtfctl` from the Japan Cloud
+
----
rtfctl update --host jp1.platform.mulesoft.com
----

* Updates `rtfctl` from the India Cloud
+
----
rtfctl update --host in1.platform.mulesoft.com
----

[[wait]]
= `wait`
Waits for Runtime Fabric components to become ready

* Specifies the number of seconds to wait 
----
rtfctl wait <value_in_seconds> --namespace <rtf_namespace>
----

* Specifies the number of seconds to pass before timing out the wait (Default is 600 seconds)

----
rtfctl wait --timeout <value_in_seconds> --namespace <rtf_namespace>
----

[[renew]]
= `renew`

Renews an expired client certificate using a pre-downloaded package

----
rtfctl renew-expired-client-cert <cert-bundle-filename>
----
end::configure-rtfctl[]


// Troubleshooting Runtime Fabric with RTFCTL
tag::troubleshoot-rtfctl[]

[%header%autowidth.spread,cols="a,a"]
|===
|Command |Description
|xref:get[`get`] | Displays one or more resources
|xref:ping[`ping`] | Tests network connectivity
|xref:report[`report`] | Generates a diagnostics report
|xref:status[`status`] | Displays the status of Runtime Fabric
|xref:test[`test`] | Verifies outbound network connectivity to the Runtime Fabric control plane
|===

[[get]]
= `get`

Displays one or more resources

* Prints a list of all applications in all environments
+
----
rtfctl get apps --namespace <rtf_namespace>
----

* Prints a list of all applications in a specific environment 
+
----
rtfctl get apps --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Displays an HTTP proxy configurations
+
----
rtfctl get http-proxy --namespace <rtf_namespace>
----

* Displays a monitoring proxy configuration
+
----
rtfctl get monitoring-proxy --namespace <rtf_namespace>
----

* Displays secure properties
+
----
rtfctl get secure-properties --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Displays the Mule license
+
----
rtfctl get mule-license --namespace <rtf_namespace>
----

* Displays Runtime Fabric registry credentials
+
----
rtfctl get registry-credentials <activation_data>
----

[[ping]]
= `ping`
Tests network connectivity

* Pings example.com from inside an application, using the first replica by default
+
----
rtfctl ping <app_name> <host_or_ip_address> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

* Attempts to connect to example.com on port `12345` from inside an application, using the first replica by default
+
----
rtfctl ping <app_name> <host_or_ip_address> --port <port> --app-namespace <app_namespace> --namespace <rtf_namespace>
----

[[report]]
= `report`
Generates a diagnostics report at `rtf-report.tar.gz`

----
rtfctl report --namespace <rtf_namespace>
----

Run rtfctl report tasks in parallel by using the `workers` flag that controls the number of tasks to run in parallel. The default value is 10.

----
rtfctl report --workers <num_of_workers>
----

Faster compression of the tarball generated by `rtfctl report` with the `--use-fast-compression` flag. The default value is false.

----
rtfctl report --use-fast-compression=true
----

Select which application namespaces to include in the report besides the installation namespace by using the `--namespaces` flag. The flag controls what to include in the reports and can result in faster collection if only selected namespaces are reported.



----
  # Reports rtf installation default namespace (rtf)
  rtfctl report 
  # Reports only <rtf_namespace>
  rtfctl report -n <rtf_namespace>
  # Reports for <app_namespace_1> and <app_namespace_2> application namespaces that belong to <rtf_namespace>
  rtfctl report -n <rtf_namespace> --app-namespaces <app_namespace_1>,<app_namespace_2> 
  rtfctl report -n <rtf_namespace> --app-namespaces <app_namespace_1> --app-namespaces <app_namespace_2> 
  # Report for all application namespaces that belong to <rtf_namespace>
  rtfctl report -n <rtf_namespace> --app-namespaces all

----

Specifies the name of the helm release to support installations using custom release names.

----
rtfctl report --release-name <agentReleaseName>
----

[[status]]
= `status`

Displays the status of Runtime Fabric

* Displays status output in JSON
+
----
rtfctl status --output json --namespace <rtf_namespace>
----
	
* Checks Kubernetes DNS health
+
----
rtfctl status dns-check --node-label "<k>:<v>"
----

[[test]]
= `test`
Verifies outbound network connectivity to the Runtime Fabric control plane.

* Schedules a check on any nodes
+
----
rtfctl test outbound-network --namespace <rtf_namespace>
----

* Schedules a check the nodes satisfying the `node-label` parameter
+
----
rtfctl test outbound-network --node-label "<k>:<v>" --namespace <rtf_namespace>
----

* Schedules a check on all nodes
+
----
rtfctl test outbound-network --all --namespace <rtf_namespace>
----

end::troubleshoot-rtfctl[]


// Agent Truststore Management
tag::agent-truststore-rtfctl[]

[%header%autowidth.spread,cols="a,a"]
|===
|Command |Description
|xref:agent-truststore-info[`agent-truststore info`] | Print a summary of the agent truststore and `ca.pem`
|xref:agent-truststore-retrieve-truststore[`agent-truststore retrieve-agent-truststore`] | Download the PKCS#12 truststore from the cluster secret to a local file
|xref:agent-truststore-retrieve-ca-pem[`agent-truststore retrieve-ca-pem`] | Download the ca.pem bundle from the cluster secret to a local file
|xref:agent-truststore-merge-p12[`agent-truststore merge-pem-into-p12`] | Add certificates from a PEM file into a local PKCS#12 truststore
|xref:agent-truststore-merge-pem[`agent-truststore merge-pem-into-pem`] | Add certificates from one PEM file into another PEM bundle
|xref:agent-truststore-update-truststore[`agent-truststore update-truststore-in-secret`] | Upload a local PKCS#12 truststore into the cluster secret
|xref:agent-truststore-update-ca-pem[`agent-truststore update-ca-pem-in-secret`] | Upload a local PEM bundle into the cluster secret as ca.pem
|xref:agent-truststore-refresh[`agent-truststore refresh-secret-with-pem`] | Merge a PEM into the cluster truststore and ca.pem in one step
|===

[[agent-truststore-info]]
= `agent-truststore info`

Prints a summary of the agent keystore secret, including all certificates loaded in the PKCS#12 truststore and ca.pem, along with their subjects, expiry dates, and days remaining.

* Print a human-readable summary
+
----
rtfctl agent-truststore info --namespace rtf
----

* Print machine-readable JSON output
+
----
rtfctl agent-truststore info -o json --namespace rtf
----

[[agent-truststore-retrieve-truststore]]
= `agent-truststore retrieve-agent-truststore`

Downloads the `agent-truststore.p12` file from the cluster secret to a local file. The password is read automatically from the `truststore-password` key in the secret.

----
rtfctl agent-truststore retrieve-agent-truststore -o agent-truststore-bk.p12 --namespace rtf
----

* Override the secret name and the output file
+
----
rtfctl agent-truststore retrieve-agent-truststore --secret agent-keystore -o agent-truststore-bk.p12 --namespace rtf
----

[[agent-truststore-retrieve-ca-pem]]
= `agent-truststore retrieve-ca-pem`

Downloads the `ca.pem` bundle from the cluster secret to a local file.

----
rtfctl agent-truststore retrieve-ca-pem -o ca-bk.pem --namespace rtf
----

[[agent-truststore-merge-p12]]
= `agent-truststore merge-pem-into-p12`

Adds the certificates from a PEM file into a local PKCS#12 truststore file (certificates-only format). Duplicate certificates are detected by subject and skipped.

----
rtfctl agent-truststore merge-pem-into-p12 -i agent-truststore-bk.p12 -c new-ca.pem -o agent-truststore-new.p12
----

[[agent-truststore-merge-pem]]
= `agent-truststore merge-pem-into-pem`

Merges certificates from one PEM file into another PEM bundle. Duplicate certificates are detected by subject and skipped.

----
rtfctl agent-truststore merge-pem-into-pem -i ca-bk.pem -c new-ca.pem -o ca-new.pem
----

[[agent-truststore-update-truststore]]
= `agent-truststore update-truststore-in-secret`

Uploads a local PKCS#12 file into the agent keystore secret, replacing the `agent-truststore.p12` key.

----
rtfctl agent-truststore update-truststore-in-secret -i agent-truststore-new.p12 --namespace rtf
----

[[agent-truststore-update-ca-pem]]
= `agent-truststore update-ca-pem-in-secret`

Uploads a local PEM bundle into the agent keystore secret, replacing the `ca.pem` key.

----
rtfctl agent-truststore update-ca-pem-in-secret -i ca-new.pem --namespace rtf
----

[[agent-truststore-refresh]]
= `agent-truststore refresh-secret-with-pem`

Reads the current truststore and ca.pem from the cluster secret, merges the provided PEM into both, displays the certificate subjects that will be uploaded, and—after confirmation—patches the secret. Use `--yes` to skip the interactive prompts.

* Interactive (asks for confirmation before each upload)
+
----
rtfctl agent-truststore refresh-secret-with-pem -c new-ca.pem --namespace rtf
----

* Non-interactive (suitable for automation)
+
----
rtfctl agent-truststore refresh-secret-with-pem -c new-ca.pem --yes --namespace rtf
----

end::agent-truststore-rtfctl[]


// Uninstall Runtime Fabric Using RTFCTL
tag::uninstall-rtfctl[]
To uninstall Runtime Fabric using `rtfctl` commands, follow these steps:

. Using Runtime Manager, delete all Mule app and API gateways deployed on Runtime Fabric.
. Verify on all associated environments that you have removed all applications.
. In Runtime Manager, delete the Runtime Fabric.
. Run the `rtfctl uninstall` command to uninstall the Runtime Fabric services from the Kubernetes cluster.
. Run the `rtfctl uninstall --confirm` command to verify the uninstall operation.
. After the uninstall command finishes, verify that there are no Runtime Fabric applications or services running in the cluster.
end::uninstall-rtfctl[]